import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url);
const {createCampaignMeshy}=require("../desktop/campaign-meshy.cjs");
const {createCampaign}=await import("../desktop/campaign-schema.mjs");
function tetra(){const pts=[[0,0,0],[1,0,0],[0,1,0],[0,0,1]],faces=[[0,2,1],[0,1,3],[0,3,2],[1,2,3]],b=Buffer.alloc(84+faces.length*50);b.writeUInt32LE(faces.length,80);faces.forEach((f,i)=>{let o=96+i*50;for(const j of f)for(const v of pts[j]){b.writeFloatLE(v,o);o+=4;}});return b;}
function response(value,status=200){return new Response(typeof value==="string"?value:JSON.stringify(value),{status,headers:{"content-type":"application/json"}});}
test("Meshy accepts only an approved portrait, saves a centered 32 mm STL locally, and never sends credentials in URLs",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"tf-meshy-"));try{const campaign=createCampaign("Test");campaign.characters.push({id:"0123456789abcdef",name:"Test hero",details:"A brave explorer",portrait:"data:image/png;base64,iVBORw0KGgo=",abilities:"",equipment:"",spells:"",hp:1,ac:10,visible:false});const store={load:async()=>structuredClone(campaign),folder:async()=>root,save:async c=>c};let requests=[];const fetchImpl=async(url,options={})=>{requests.push({url:String(url),options});if(options.method==="POST")return response({result:"task-12345678"});if(String(url).includes("task-12345678"))return response({status:"SUCCEEDED",model_urls:{stl:"https://assets.meshy.ai/model.stl"}});return new Response(tetra());};const service=createCampaignMeshy({store,ai:{meshyKey:async()=>"test-secret-key-123"},fetchImpl});const result=await service.generate(campaign.id,"0123456789abcdef");assert.equal(result.heightMm,32);assert.equal(result.campaign.characters[0].modelFile,"models/0123456789abcdef.stl");const saved=await fs.readFile(path.join(root,"models/0123456789abcdef.stl"));assert.equal(saved.readUInt32LE(80),4);assert.ok(requests.every(r=>!r.url.includes("test-secret-key-123")));assert.equal(JSON.parse(requests[0].options.body).image_url,campaign.characters[0].portrait); }finally{await fs.rm(root,{recursive:true,force:true});}});
test("Meshy refuses a character without an approved portrait before making a request",async()=>{const campaign=createCampaign("No portrait");campaign.characters.push({id:"0123456789abcdef",name:"No portrait",details:"",portrait:null});let called=false;const service=createCampaignMeshy({store:{load:async()=>campaign},ai:{meshyKey:async()=>"test-secret-key-123"},fetchImpl:async()=>{called=true;throw Error("unexpected");}});await assert.rejects(service.generate(campaign.id,"0123456789abcdef"),/approve its portrait/);assert.equal(called,false);});
