const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
(async()=>{await fs.mkdir('test-results',{recursive:true});const output=await fs.mkdtemp(path.join(require('node:os').tmpdir(),'terrain-desktop-smoke-'));const priorPacks=new Set(await fs.readdir(output));const app=await electron.launch({executablePath:process.env.TERRAIN_EXECUTABLE,args:[...(process.env.TERRAIN_EXECUTABLE?[]:['.']),`--user-data-dir=${path.join(output,'profile-'+Date.now())}`]});try{const page=await app.firstWindow();await page.waitForSelector('#tutorial-dialog',{state:'attached'});if(await page.locator('#release-dialog').isVisible())await page.locator('#release-acknowledge').click();await page.waitForSelector('#tutorial-dialog',{state:'attached'});if(await page.locator('#tutorial-dialog').isVisible())await page.locator('#tutorial-close').click();await page.evaluate(()=>window.confirm=()=>true);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('canvas');await page.locator('.examples').evaluate(d=>d.open=true);await page.locator('#demo').click();await page.locator('#connectors').selectOption('none');await page.waitForTimeout(1500);await page.screenshot({path:path.join(output,'desktop.png')});assert.equal(await page.locator('#count').textContent(),'37');
await page.locator('#asset-category').selectOption('Floors');await page.locator('#search').fill('Small floor');await page.locator('#kit .asset').filter({hasText:'Small floor'}).click();const canvas=page.locator('canvas');const box=await canvas.boundingBox();await page.mouse.click(box.x+box.width*.6,box.y+box.height*.55);assert.equal(await page.locator('#count').textContent(),'38');assert.ok(await page.locator('#inspector').isHidden());await page.mouse.click(box.x+box.width*.6,box.y+box.height*.55);await page.locator('#x').fill('3.5');await page.locator('#x').press('Tab');assert.equal(await page.locator('#x').inputValue(),'3.5');await page.locator('#rotate').click();assert.equal(await page.locator('#angle').inputValue(),'90');await page.locator('#duplicate').click();assert.equal(await page.locator('#count').textContent(),'39');await page.locator('#undo').click();assert.equal(await page.locator('#count').textContent(),'38');await page.locator('#redo').click();assert.equal(await page.locator('#count').textContent(),'39');await page.locator('#delete').click();assert.equal(await page.locator('#count').textContent(),'38');
await app.evaluate(({dialog},dir)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:dir+'/smoke.terrain'});dialog.showOpenDialog=async(_,opts)=>opts.properties.includes('openDirectory')?{canceled:false,filePaths:[dir]}:{canceled:false,filePaths:[dir+'/smoke.terrain']};},output);await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready'));const saved=JSON.parse(await fs.readFile(path.join(output,'smoke.terrain'),'utf8'));assert.equal(saved.items.length,38);await page.locator('#new').click();assert.equal(await page.locator('#count').textContent(),'0');await page.locator('#open').click();await page.waitForFunction(()=>document.querySelector('#count').textContent==='38');await page.locator('#export').click();await page.locator('#confirm-print').click();await page.waitForFunction(()=>!document.querySelector('#print-dialog').open);const dirs=await fs.readdir(output);const pack=dirs.find(d=>d.startsWith('TerrainFoundry-')&&!priorPacks.has(d));assert.ok(pack);const files=await fs.readdir(path.join(output,pack));assert.ok(files.includes('floor.stl'));assert.ok(files.includes('quantities.csv'));const stl=await fs.readFile(path.join(output,pack,'floor.stl'));assert.equal(stl.length,84+stl.readUInt32LE(80)*50);assert.equal(errors.length,0,errors.join('\n'));await page.locator('#save').click();await page.waitForTimeout(200);await page.screenshot({path:path.join(output,'desktop-verified.png')});console.log('PASS: native desktop launch, placement, editing, undo/redo, file save/open, STL pack export, zero renderer errors.');}finally{await app.evaluate(({BrowserWindow})=>{for(const w of BrowserWindow.getAllWindows())w.destroy();});await app.close();}})().catch(e=>{console.error(e);process.exit(1);});







