const {_electron:electron}=require('playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createHash}=require('node:crypto');
const root=path.resolve('test-results','installer-'+Date.now()),profile=path.join(root,'profile'),projectDir=path.join(root,'User Projects'),projectFile=path.join(projectDir,'Preserved scene.terrain');
const exe=path.join(process.env.LOCALAPPDATA,'Programs','TerrainFoundry','TerrainFoundry.exe');
async function msi(args,label,expected=0){const log=path.join(root,label+'.log');const code=await new Promise((resolve,reject)=>{const child=spawn('msiexec.exe',[...args,'/qn','/norestart','/l*v',log],{windowsHide:true});child.on('error',reject);child.on('exit',resolve);});assert.equal(code,expected,`${label}: Windows Installer returned ${code}; see ${log}`);console.log('PASS MSI '+label);}
async function close(app){await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.destroy()));await app.close();}
async function launch(){const app=await electron.launch({executablePath:exe,args:['--user-data-dir='+profile]});const page=await app.firstWindow();await page.waitForFunction(()=>document.querySelector('#count')?.textContent!=='0'&&document.querySelector('#kit .asset'),null,{timeout:90000});page.on('dialog',d=>d.accept());await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},projectFile);return {app,page};}
(async()=>{await fs.mkdir(projectDir,{recursive:true});await fs.mkdir(profile,{recursive:true});
 const old=JSON.parse(await fs.readFile('installer/build/0.8.0/identity.json','utf8')),next=JSON.parse(await fs.readFile('installer/build/0.9.0/identity.json','utf8'));
 const fixture={version:1,name:'Existing saved environment',grid:25.4,connectors:'openlock',connectorRevision:2,board:32,printer:{x:256,y:256,z:256},assets:{'u-personal':{name:'My imported sculpture',positions:[0,0,0,5,0,0,0,5,0,0,0,5],colors:Array(12).fill(.6),indices:[0,2,1,0,1,3,0,3,2,1,2,3]}},items:[{id:'wall-kept',type:'c-window',x:3.5,z:-2.25,y:12,rotation:90,color:'#9a8765'},{id:'floor-kept',type:'o-grass',x:0,z:0,y:0,rotation:180,color:'#ffffff'},{id:'import-kept',type:'u-personal',x:-2,z:1,y:8,rotation:270,color:'#ffffff'}]};
 await fs.writeFile(projectFile,JSON.stringify(fixture,null,2));
 await msi(['/i',old.msi],'install-old');let session=await launch();let userData;
 try{assert.equal(await session.app.evaluate(({app})=>app.getVersion()),'0.8.0');userData=await session.app.evaluate(({app})=>app.getPath('userData'));await session.page.locator('#open').click();await session.page.waitForFunction(()=>document.querySelector('#count').textContent==='3');await session.page.locator('#save').click();await session.page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready'));await session.page.locator('#name').fill('Unsaved environment recovered after upgrade');await session.page.locator('#name').press('Tab');assert.equal(JSON.parse(await session.page.evaluate(()=>localStorage.getItem('terrain-foundry-recovery'))).name,'Unsaved environment recovered after upgrade');}finally{await close(session.app);}
 const before=await fs.readFile(projectFile),beforeHash=createHash('sha256').update(before).digest('hex');await msi(['/i',next.msi],'upgrade');assert.equal(createHash('sha256').update(await fs.readFile(projectFile)).digest('hex'),beforeHash);
 session=await launch();let info,recovered;
 try{assert.equal(await session.app.evaluate(({app})=>app.getVersion()),'0.9.0');assert.equal(await session.app.evaluate(({app})=>app.getPath('userData')),userData);await session.page.waitForFunction(()=>document.querySelector('#name').value==='Unsaved environment recovered after upgrade');info=await session.page.evaluate(()=>window.desktop.storageInfo());recovered=JSON.parse((await session.page.evaluate(()=>window.desktop.loadRecovery())).data);assert.deepEqual(recovered,{...fixture,name:'Unsaved environment recovered after upgrade'});await session.page.locator('#save').click();await session.page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready'));const backups=await fs.readdir(info.backups);assert.ok((await Promise.all(backups.map(f=>fs.readFile(path.join(info.backups,f))))).some(b=>b.equals(before)));await session.page.screenshot({path:path.join(root,'installed-upgrade.png')});}finally{await close(session.app);}
 console.log('PASS project bytes, imported mesh, placements, rotations, colours, printer settings, legacy recovery migration and pre-save backup');
 await msi(['/i',old.msi],'downgrade-blocked',1603);assert.deepEqual(JSON.parse(await fs.readFile(projectFile,'utf8')),recovered);
 await msi(['/x','{'+next.productCode+'}'],'uninstall');await assert.rejects(fs.stat(exe),{code:'ENOENT'});assert.deepEqual(JSON.parse(await fs.readFile(projectFile,'utf8')),recovered);assert.deepEqual(JSON.parse(await fs.readFile(info.recovery,'utf8')),recovered);assert.ok((await fs.readdir(info.backups)).length>0);
 await msi(['/i',next.msi],'reinstall');session=await launch();try{assert.equal(await session.page.locator('#name').inputValue(),recovered.name);assert.equal(await session.page.locator('#count').textContent(),'3');}finally{await close(session.app);}
 const report={passed:true,oldVersion:old.version,newVersion:next.version,installedExecutable:exe,projectFile,profile,checks:['offline old install','major upgrade','saved file byte preservation','imported mesh preservation','legacy recovery migration','backup before overwrite','downgrade blocked','uninstall preserves user files','reinstall restores recovery'],physicalPrintingTested:false};await fs.writeFile(path.join(root,'report.json'),JSON.stringify(report,null,2));await fs.writeFile('test-results/latest-installer-report.json',JSON.stringify(report,null,2));console.log('PASS installer lifecycle; report: '+root);
})().catch(e=>{console.error(e);process.exit(1);});
