import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';import {generateKeyPairSync,randomBytes,createHash,createCipheriv,createDecipheriv,sign,verify} from 'node:crypto';
const require=createRequire(import.meta.url),{createPremiumDevice}=require('../desktop/premium-device.cjs'),{createPremiumStore,verifyManifest}=require('../desktop/premium-store.cjs'),{createPremiumClient}=require('../desktop/premium-client.cjs');
const sha=b=>createHash('sha256').update(b).digest('hex');
test('signed high-definition print entries fit the bounded reader while oversized entries are rejected',()=>{
 const issuer=generateKeyPairSync('ed25519');
 function grant(length){const metadata={schemaVersion:1,issuer:'TerrainFoundry',packId:'tf-density',version:'1.0.0',size:length+1,sha256:'a'.repeat(64),files:[{path:'catalogue.json',offset:0,length:1,plainSize:1,sha256:'b'.repeat(64),iv:Buffer.alloc(12).toString('base64'),tag:Buffer.alloc(16).toString('base64')},{path:'print/stacked-barrels.stl',offset:1,length,plainSize:length,sha256:'c'.repeat(64),iv:Buffer.alloc(12).toString('base64'),tag:Buffer.alloc(16).toString('base64')}]};const payload=Buffer.from(JSON.stringify(metadata));return {payload:payload.toString('base64'),signature:sign(null,payload,issuer.privateKey).toString('base64')};}
 assert.equal(verifyManifest(grant(208330884),issuer.publicKey,'tf-density').files[1].length,208330884);
 assert.throws(()=>verifyManifest(grant(250000001),issuer.publicKey,'tf-density'),/Unsafe pack file/);
});
export function protectedStorage(){const key=randomBytes(32);return {isEncryptionAvailable:()=>true,encryptString(s){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(s),c.final(),c.getAuthTag()]);},decryptString(b){const d=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString();}};}
function fixture(issuer,asset='qa-001',badMesh=false,version='1.0.0'){
 const positions=new Float32Array([0,0,0,1,0,0,0,.1,1]),colors=new Float32Array(9).fill(.7),indices=new Uint32Array([0,1,2]);if(badMesh)positions[1]=NaN;const mesh=Buffer.concat([Buffer.from(positions.buffer),Buffer.from(colors.buffer),Buffer.from(indices.buffer)]),stl=Buffer.alloc(134);stl.writeUInt32LE(1,80);for(let i=0;i<9;i++)stl.writeFloatLE(positions[i],96+i*4);
 const catalogue={schemaVersion:1,packId:'tf-test',assets:[{id:asset,name:'Fixture tile',category:'Floors',subcategory:'Straight floors',raw:{path:'preview/raw.bin',vertices:3,indices:3},connected:{path:'preview/connected.bin',vertices:3,indices:3},dimensionsMm:{width:1,depth:1,height:.1},openlock:{kind:'floor',width:1,depth:1,height:.1,ports:[]},printFiles:[{path:'print/qa.stl',name:'qa.stl'}]}]};
 const files=[{path:'catalogue.json',bytes:Buffer.from(JSON.stringify(catalogue))},{path:'preview/raw.bin',bytes:mesh},{path:'preview/connected.bin',bytes:mesh},{path:'print/qa.stl',bytes:stl}],key=randomBytes(32),chunks=[],entries=[];let offset=0;
 for(const f of files){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);c.setAAD(Buffer.from('tf-test\n'+version+'\n'+f.path));const encrypted=Buffer.concat([c.update(f.bytes),c.final()]);entries.push({path:f.path,offset,length:encrypted.length,plainSize:f.bytes.length,sha256:sha(f.bytes),iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64')});chunks.push(encrypted);offset+=encrypted.length;}
 const blob=Buffer.concat(chunks),payload=Buffer.from(JSON.stringify({schemaVersion:1,issuer:'TerrainFoundry',packId:'tf-test',version,size:blob.length,sha256:sha(blob),files:entries})),manifest={payload:payload.toString('base64'),signature:sign(null,payload,issuer.privateKey).toString('base64')};return {blob,key:key.toString('base64'),manifest,mesh,stl,catalogue};
}
async function setup(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tf-pack-')),issuer=generateKeyPairSync('ed25519'),storage=protectedStorage(),device=createPremiumDevice({userData:dir,safeStorage:storage}),identity=await device.publicIdentity();const payload=Buffer.from(JSON.stringify({schemaVersion:1,issuer:'TerrainFoundry',packId:'tf-test',licenceId:'a'.repeat(64),deviceFingerprint:identity.fingerprint,issuedAt:Date.now(),offlineUse:true})),entitlement={payload:payload.toString('base64'),signature:sign(null,payload,issuer.privateKey).toString('base64')};const store=createPremiumStore({userData:dir,safeStorage:storage,device,issuerPublicKey:issuer.publicKey});await store.init();return {dir,issuer,storage,device,identity,entitlement,store,pack:fixture(issuer)};}
async function install(s,pack=s.pack){return s.store.install({...pack,entitlement:s.entitlement,download:file=>fs.writeFile(file,pack.blob)});}
test('verified pack installs atomically, renders and exports offline, persists ciphertext and protected keys only',async()=>{const s=await setup();try{const inventory=await install(s);assert.equal(inventory.assets[0].id,'qa-001');assert.deepEqual(s.store.readShape('qa-001',true).bytes,s.pack.mesh);assert.deepEqual(s.store.readPrint('qa-001')[0].data,s.pack.stl);const files=await fs.readdir(path.join(s.dir,'premium/packs'),{recursive:true});assert.ok(!files.some(f=>/\.(stl|bin)$/.test(f)));const record=files.find(f=>f.endsWith('record.json')),raw=await fs.readFile(path.join(s.dir,'premium/packs',record),'utf8');assert.ok(!raw.includes(s.pack.key));assert.ok(!raw.includes('TF-'));const reopened=createPremiumStore({userData:s.dir,safeStorage:s.storage,device:createPremiumDevice({userData:s.dir,safeStorage:s.storage}),issuerPublicKey:s.issuer.publicKey});assert.equal((await reopened.init()).packs.length,1);assert.deepEqual(reopened.readPrint('qa-001')[0].data,s.pack.stl);}finally{await fs.rm(s.dir,{recursive:true});}});
test('tamper, wrong key, invalid geometry and interrupted update preserve the working pack',async()=>{const s=await setup();try{await install(s);const old=await fs.readFile(path.join(s.dir,'premium/packs/tf-test.json'),'utf8');await assert.rejects(install(s,{...s.pack,blob:Buffer.from('broken')}),/size/);await assert.rejects(install(s,{...s.pack,key:randomBytes(32).toString('base64')}));await assert.rejects(install(s,fixture(s.issuer,'qa-001',true,'1.1.0')),/coordinate/);await assert.rejects(s.store.install({...s.pack,entitlement:s.entitlement,download:async file=>{await fs.writeFile(file,s.pack.blob.subarray(0,20));throw Error('interrupted');}}),/interrupted/);assert.equal(await fs.readFile(path.join(s.dir,'premium/packs/tf-test.json'),'utf8'),old);assert.deepEqual(s.store.readPrint('qa-001')[0].data,s.pack.stl);assert.ok(!(await fs.readdir(path.join(s.dir,'premium/packs'))).some(f=>f.startsWith('.pending')));}finally{await fs.rm(s.dir,{recursive:true});}});
test('signed malicious inventory is rejected before download: traversal, overlapping ranges, file count and size',async()=>{const s=await setup();try{for(const change of [m=>m.files[0].path='../escape',m=>m.files[1].offset=0,m=>m.size=1000000001,m=>m.files=Array(10001).fill(m.files[0])]){const m=JSON.parse(Buffer.from(s.pack.manifest.payload,'base64'));change(m);const bytes=Buffer.from(JSON.stringify(m)),manifest={payload:bytes.toString('base64'),signature:sign(null,bytes,s.issuer.privateKey).toString('base64')};assert.throws(()=>verifyManifest(manifest,s.issuer.publicKey,'tf-test'));}assert.throws(()=>verifyManifest({...s.pack.manifest,signature:randomBytes(64).toString('base64')},s.issuer.publicKey,'tf-test'),/signature/);}finally{await fs.rm(s.dir,{recursive:true});}});
test('copied cache is not usable by another protected Windows identity and corrupt files remain unavailable',async()=>{const s=await setup();try{await install(s);const copied=createPremiumStore({userData:s.dir,safeStorage:protectedStorage(),device:createPremiumDevice({userData:s.dir,safeStorage:protectedStorage()}),issuerPublicKey:s.issuer.publicKey});assert.equal((await copied.init()).packs.length,0);assert.equal(copied.inventory().warnings.length,1);const names=await fs.readdir(path.join(s.dir,'premium/packs'));const folder=names.find(n=>n.startsWith('installed-'));await fs.writeFile(path.join(s.dir,'premium/packs',folder,'archive.tfc'),s.pack.blob.subarray(1));assert.throws(()=>s.store.readShape('qa-001',false),/size/);}finally{await fs.rm(s.dir,{recursive:true});}});
test('login, activation and proof-bound download send secrets only through native transport and expose status-only results',async()=>{const s=await setup();try{const code='TF-'+'A'.repeat(32),token='s'.repeat(43),activation=`TerrainFoundry.activate.v1\n${'a'.repeat(64)}\n${s.identity.fingerprint}\n${randomBytes(32).toString('base64url')}`,download=`TerrainFoundry.download.v1\n${'a'.repeat(64)}\n${s.identity.fingerprint}\n${randomBytes(32).toString('base64url')}`,progress=[],calls=[];const url=`https://storage.example/premium-packs/packs/tf-test/1.0.0/${sha(s.pack.blob)}.tfc?sp=r&sig=fixture`;
 const fetchImpl=async(u,options)=>{calls.push({u,options});if(u===url)return new Response(s.pack.blob);const action=u.split('/').at(-1),a=JSON.parse(options.body);if(['challenge','activate','download-challenge','download'].includes(action))assert.equal(options.headers.Authorization,'Bearer '+token);let result;if(action==='login-start')result={requestId:'r'.repeat(43)};if(action==='login-verify')result={session:token,expires:Date.now()+3600000};if(action==='challenge')result={challengeId:'c'.repeat(32),message:activation};if(action==='activate'){assert.ok(verify(null,Buffer.from(activation),s.identity.publicKey,Buffer.from(a.signature,'base64')));result={packId:'tf-test',entitlement:s.entitlement};}if(action==='download-challenge')result={challengeId:'d'.repeat(43),message:download};if(action==='download'){assert.ok(verify(null,Buffer.from(download),s.identity.publicKey,Buffer.from(a.signature,'base64')));result={manifest:s.pack.manifest,key:s.pack.key,url,entitlement:s.entitlement};}return Response.json(result);};
 const client=createPremiumClient({device:s.device,store:s.store,fetchImpl,issuerPublicKey:s.issuer.publicKey,serviceBase:'https://service.example/',storageHost:'storage.example',onProgress:p=>progress.push(p)});const start=await client.loginStart('buyer@example.com'),verified=await client.loginVerify('123456'),installed=await client.activate(code);assert.deepEqual(start,{sent:true});assert.deepEqual(verified,{verified:true});assert.deepEqual(installed,{installed:true,packId:'tf-test',pieceCount:1});for(const secret of [s.pack.key,token,code,url])assert.ok(!JSON.stringify([start,verified,installed,progress]).includes(secret));assert.equal(progress.at(-1).stage,'Ready offline');assert.ok(calls.every(c=>c.options.redirect==='error'));assert.ok(calls.every(c=>!c.options.headers?.['Content-Length']));}finally{await fs.rm(s.dir,{recursive:true});}});
test('download proof rejects a different licence or activation purpose',async()=>{const s=await setup();try{const msg=`TerrainFoundry.download.v1\n${'b'.repeat(64)}\n${s.identity.fingerprint}\n${randomBytes(32).toString('base64url')}`;await assert.rejects(s.device.signDownloadChallenge(msg,'a'.repeat(64)),/does not match/);await assert.rejects(s.device.signChallenge(msg),/does not match/);}finally{await fs.rm(s.dir,{recursive:true});}});

test('pack upgrades preserve saved asset IDs and reject downgrade or changed same-version payload',async()=>{const s=await setup();try{await install(s);await assert.rejects(install(s,fixture(s.issuer)),/newer/);await assert.rejects(install(s,fixture(s.issuer,'qa-002',false,'1.1.0')),/removes/);await install(s,fixture(s.issuer,'qa-001',false,'1.1.0'));assert.equal(s.store.inventory().packs[0].version,'1.1.0');await assert.rejects(install(s),/newer/);assert.ok(s.store.has('qa-001'));}finally{await fs.rm(s.dir,{recursive:true});}});

test('cancellation and a conflicting free asset cannot commit an installation',async()=>{const s=await setup();try{const signal=AbortSignal.abort();await assert.rejects(s.store.install({...s.pack,entitlement:s.entitlement,signal,download:file=>fs.writeFile(file,s.pack.blob)}),/cancelled/);assert.equal(s.store.inventory().packs.length,0);const store=createPremiumStore({userData:s.dir,safeStorage:s.storage,device:s.device,issuerPublicKey:s.issuer.publicKey,isReserved:id=>id==='qa-001'});await store.init();await assert.rejects(store.install({...s.pack,entitlement:s.entitlement,download:file=>fs.writeFile(file,s.pack.blob)}),/conflicting/);assert.equal(store.inventory().packs.length,0);}finally{await fs.rm(s.dir,{recursive:true});}});

test('signed catalogue cannot override free geometry or export duplicate filenames',async()=>{const s=await setup();try{const {validateCatalogue}=require('../desktop/premium-store.cjs'),m=verifyManifest(s.pack.manifest,s.issuer.publicKey,'tf-test');const c=structuredClone(s.pack.catalogue);c.assets.push({...c.assets[0],id:'qa-002'});assert.throws(()=>validateCatalogue(Buffer.from(JSON.stringify(c)),m),/printable/);}finally{await fs.rm(s.dir,{recursive:true});}});
