const {chromium}=require('playwright'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{
 await fs.mkdir('test-results',{recursive:true});
 const browser=await chromium.launch({...(!process.env.CI?{channel:'msedge'}:{}),headless:true});
 const q={id:'a'.repeat(32),status:'quoted',preview:true,expiresAt:Date.now()+86400000,colour:{label:'Stone grey'},items:Array.from({length:23},(_,i)=>({name:'Detailed dungeon curved wall '+(i+1),file:'custom-'+i+'.stl',quantity:2})),price:{pieceCount:46,filamentPence:606,machinePence:3880,handlingPence:1700,discountPence:100,discount:{code:'TEST10'},shippingPence:495,vatPence:0,totalPence:6581,estimate:{material:'Basic PLA',printer:'Bambu H2S',grams:387.91,hours:19.4}}};
 q.items[0]={name:'a-001',file:'a-001.stl',quantity:6,sha256:'a'.repeat(64),sizeMm:[50.8,50.8,50.8]};q.items[1]={name:'a-002',file:'a-002.stl',quantity:3,sha256:'b'.repeat(64)};
 const catalog={schema:1,assets:{'a-001':{name:'Curved stone wall',category:'Walls',sha256:['a'.repeat(64)]},'a-002':{name:'Wide curved stone wall',category:'Walls',sha256:[]}}};
 const page=await browser.newPage({acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));let calls=0;
 await page.route('https://terrainfoundry.co.uk/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1);if(name==='terrain-catalog.json')return route.fulfill({json:catalog});if(name==='print-config.js')return route.fulfill({body:"window.TERRAIN_PRINT_API='https://quote.test';",contentType:'text/javascript'});return route.fulfill({body:await fs.readFile('site/'+name),contentType:name.endsWith('.css')?'text/css':name.endsWith('.js')?'text/javascript':name.endsWith('.webp')?'image/webp':'text/html'});});
 await page.route('https://quote.test/**',route=>{if(route.request().method()==='POST'){assert.ok(route.request().url().includes('/test-order/'));calls++;return route.fulfill({json:{...q,status:'test-requested'}});}return route.fulfill({json:q});});
 try{
 for(const [width,height] of [[1920,1080],[1366,768],[390,844],[390,667],[667,390]]){
  await page.setViewportSize({width,height});await page.goto('https://terrainfoundry.co.uk/print-order.html#'+q.id+'.'+'b'.repeat(64));await page.reload();await page.waitForSelector('.quote-summary');await page.waitForFunction(()=>window.TerrainQuoteCatalog?.lookup({file:'a-001.stl'}));
  const layout=await page.evaluate(()=>({height:document.documentElement.scrollHeight,width:document.documentElement.scrollWidth,viewport:innerHeight,actions:document.querySelector('.quote-actions').getBoundingClientRect().bottom, panelBottom:document.querySelector('#order-details').getBoundingClientRect().bottom, contentBottom:Math.max(...[...document.querySelectorAll('.quote-column:not([hidden]) > *')].map(e=>e.getBoundingClientRect().bottom))}));
  assert.ok(layout.height<=height+1,JSON.stringify({width,height,layout}));assert.ok(layout.width<=width);assert.ok(layout.actions<height);assert.ok(layout.contentBottom<=layout.panelBottom,JSON.stringify({width,height,layout}));
  assert.doesNotMatch(await page.locator('body').innerText(),/manufacturing markup|filament cost|machine time cost/i);
  if(width<700)await page.getByRole('button',{name:'Pieces'}).click();
  const matches=await page.evaluate(()=>({renamed:window.TerrainQuoteCatalog.lookup({file:'renamed.stl',sha256:'a'.repeat(64)})?.matched,altered:window.TerrainQuoteCatalog.lookup({file:'a-001.stl',sha256:'b'.repeat(64)})?.matched,unknown:window.TerrainQuoteCatalog.lookup({file:'../../a-001.stl',sha256:'b'.repeat(64)})}));assert.deepEqual(matches,{renamed:true,altered:false,unknown:null});
  const assertPiecesFit=async()=>{const bounds=await page.evaluate(()=>({panel:document.querySelector('#order-details').getBoundingClientRect().bottom,content:Math.max(...[...document.querySelectorAll('.quote-part-column > *, .quote-pieces li')].map(e=>e.getBoundingClientRect().bottom))}));assert.ok(bounds.content<=bounds.panel,JSON.stringify({width,height,bounds}));};await assertPiecesFit();
  await page.getByRole('button',{name:'Preview Curved stone wall',exact:true}).click();await page.locator('.piece-preview-dialog').waitFor();assert.match(await page.locator('.piece-preview-dialog').innerText(),/Matched to the registered model/);await page.waitForFunction(()=>{const img=document.querySelector('.piece-preview-dialog img');return img?.complete&&img.naturalWidth>0;});await page.keyboard.press('Escape');
  const seen=new Set();do{for(const name of await page.locator('.quote-pieces li').evaluateAll(rows=>rows.map(r=>r.dataset.file)))seen.add(name);await assertPiecesFit();if(await page.getByRole('button',{name:'Next',exact:true}).isDisabled())break;await page.getByRole('button',{name:'Next',exact:true}).click();}while(true);assert.equal(seen.size,23);
  if(width<700)await page.getByRole('button',{name:'Price',exact:true}).click();
  await page.screenshot({path:`test-results/compact-quote-${width}-${height}.png`});console.log(`PASS ${width}x${height}: fits viewport; all pieces accessible`);
 }
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Save quotation',exact:true}).click();const download=await downloadPromise;const text=await fs.readFile(await download.path(),'utf8');assert.ok(text.includes('#'+q.id+'.'+'b'.repeat(64)));assert.doesNotMatch(text,/markup|filament cost|machine time cost/i);
 await page.getByRole('button',{name:'PayPal-style test'}).click();await page.getByRole('status').filter({hasText:'Test request saved'}).waitFor();assert.equal(calls,1);assert.deepEqual(errors,[]);console.log('PASS private saved link and test request; no PayPal call');
 q.preview=false;q.status='payment-review';q.sandbox=true;await page.reload();await page.getByRole('status').filter({hasText:'payment review'}).waitFor();assert.match(await page.getByRole('status').innerText(),/SANDBOX/);assert.equal(await page.locator('#pay-button').isVisible(),false);const reviewDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Save quotation',exact:true}).click();await reviewDownload;assert.match(await page.locator('#quote-reference').innerText(),/Payment review required.*Sandbox/);console.log('PASS payment review and sandbox remain visible after saving');
 await page.route('**/assets/terrain/a-001.webp',route=>route.fulfill({status:404,body:''}));await page.reload();await page.waitForSelector('.quote-summary');if(await page.getByRole('button',{name:'Pieces',exact:true}).isVisible())await page.getByRole('button',{name:'Pieces',exact:true}).click();await page.getByRole('button',{name:'Preview unavailable for Curved stone wall',exact:true}).waitFor();assert.equal(await page.locator('.quote-total strong').innerText(),'£65.81');
 await page.route('**/terrain-catalog.json',route=>route.fulfill({status:503,body:''}));await page.reload();await page.waitForSelector('.quote-summary');await page.evaluate(()=>window.TerrainQuoteCatalog.ready);if(await page.getByRole('button',{name:'Pieces',exact:true}).isVisible())await page.getByRole('button',{name:'Pieces',exact:true}).click();assert.equal(await page.locator('button.piece-thumbnail').count(),0);assert.equal(await page.locator('.quote-total strong').innerText(),'£65.81');console.log('PASS failed images and unavailable catalogue preserve quote and totals');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
