const {_electron:electron}=require('playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const dir=await fs.mkdtemp(path.join(require('node:os').tmpdir(),'terrain-remaster-'));
const app=await electron.launch({executablePath:process.env.TERRAIN_EXECUTABLE,args:[...(process.env.TERRAIN_EXECUTABLE?[]:['.']),`--user-data-dir=${dir}/profile`]});
try{const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.waitForSelector('canvas',{timeout:120000});await page.waitForSelector('#tutorial-dialog',{state:'attached'});if(await page.locator('#tutorial-dialog').isVisible())await page.locator('#tutorial-close').click();
await app.evaluate(({dialog},dir)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:dir+'/saved.terrain'});dialog.showOpenDialog=async(_,o)=>({canceled:false,filePaths:[o.properties.includes('openDirectory')?dir:dir+'/saved.terrain']});},dir);
await page.locator('.examples summary').click();await page.locator('#garden-demo').click();assert.equal(await page.locator('#count').textContent(),'9');assert.match(await page.locator('#connection-status').textContent(),/12 matched connections · 0 overlapping/);await page.waitForTimeout(600);await page.screenshot({path:path.resolve('test-results/remaster-garden.png')});
await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready'));const garden=JSON.parse(await fs.readFile(dir+'/saved.terrain','utf8'));assert.ok(garden.items.some(i=>i.type==='o-daisies'));await page.locator('#new').click();await page.locator('#open').click();await page.waitForFunction(()=>document.querySelector('#count').textContent==='9');
await page.locator('#export').click();await page.locator('#confirm-print').click();await page.waitForFunction(()=>!document.querySelector('#print-dialog').open);let pack=(await fs.readdir(dir)).find(n=>n.startsWith('TerrainFoundry-'));assert.ok((await fs.stat(path.join(dir,pack,'o-daisies.stl'))).size>1000);
await page.locator('#curves-demo').click();assert.equal(await page.locator('#count').textContent(),'8');assert.match(await page.locator('#connection-status').textContent(),/4 matched connections · 0 overlapping/);assert.match(await page.locator('#library-count').textContent(),/24 of 72/);await page.locator('#family').selectOption('Hollowdeep');assert.equal(await page.locator('#kit .asset').count(),3);await page.locator('#family').selectOption('All families');await page.waitForTimeout(700);await page.screenshot({path:path.resolve('test-results/remaster-curves.png')});
await page.locator('#export').click();await page.locator('#confirm-print').click();await page.waitForFunction(()=>!document.querySelector('#print-dialog').open);const packs=(await fs.readdir(dir)).filter(n=>n.startsWith('TerrainFoundry-'));assert.ok((await Promise.all(packs.map(p=>fs.readdir(path.join(dir,p))))).flat().some(f=>f.startsWith('a-')&&f.endsWith('.stl')));
await page.locator('#cave-demo').click();await page.locator('#front').click();await page.waitForTimeout(500);await page.screenshot({path:path.resolve('test-results/remaster-caves.png')});
await page.locator('#new').click();await page.locator('#collection').selectOption('a-');await page.locator('#family').selectOption('Fortress');await page.locator('#search').fill('gentle');assert.equal(await page.locator('#kit .asset').count(),1);await page.locator('#kit .asset').click();const b=await page.locator('#stage > canvas').boundingBox();await page.keyboard.down('Shift');await page.mouse.click(b.x+b.width/2,b.y+b.height/2);await page.keyboard.up('Shift');await page.locator('#rotate').click();assert.equal(await page.locator('#angle').inputValue(),'45');await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready'));const saved=JSON.parse(await fs.readFile(dir+'/saved.terrain','utf8'));assert.equal(saved.items[0].rotation,45);assert.deepEqual(errors,[]);
console.log('PASS: garden renders, 9-piece save/reopen/STL export, 72 curves and family filter, matching floors, curve STL export, caves, 45-degree rotation.');
}finally{await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.destroy()));await app.close();}
})().catch(e=>{console.error(e);process.exit(1);});
