const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
(async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'terrain-world-')),file=path.join(dir,'building.scene.terrain'),worldFile=path.join(dir,'table.world.terrain'),encounterFile=path.join(dir,'reused.scene.terrain');
 const fixture={version:1,name:'Village workshop',grid:25.4,board:24,connectors:'openlock',printer:{x:180,y:180,z:180},items:[]};
 for(const x of [-2,0,2])for(const z of [-1,1])fixture.items.push({id:`floor-${x}-${z}`,type:'floor',x,z,y:0,rotation:0,color:'#ffffff'});
 fixture.items.push({id:'wall',type:'wall',x:0,z:-2.25,y:0,rotation:0,color:'#ffffff'},{id:'crate',type:'crate',x:0,z:0,y:8,rotation:0,color:'#997351'});await fs.writeFile(file,JSON.stringify(fixture));
 const app=await electron.launch({executablePath:process.env.TERRAIN_EXECUTABLE,args:[...(process.env.TERRAIN_EXECUTABLE?[]:['.']),'--user-data-dir='+path.join(dir,'profile')]});
 try{
  const p=await app.firstWindow(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route(/^https?:/,r=>r.abort());await p.waitForSelector('#release-dialog[open]');await p.locator('#release-acknowledge').click();await p.waitForSelector('#tutorial-dialog[open]');await p.locator('#tutorial-close').click();await p.evaluate(()=>window.confirm=()=>true);
  await app.evaluate(({dialog},o)=>{global.__open=o.file;global.__save=o.worldFile;dialog.showOpenDialog=async()=>({canceled:false,filePaths:[global.__open]});dialog.showSaveDialog=async()=>({canceled:false,filePath:global.__save});}, {file,worldFile});
  await p.locator('#world-settings').click();await p.locator('#world-new').click();await p.locator('#world-preset').selectOption('1');await p.locator('#world-size-apply').click();await p.locator('#world-add-level').click();assert.equal(await p.locator('#world-level-list .world-level-row').count(),2);await p.locator('#world-level-list input[aria-label="Level name"]').nth(1).fill('Village above caves');await p.locator('#world-level-list input[type=number]').nth(1).fill('76.2');await p.locator('#world-level-list input[type=number]').nth(1).press('Tab');assert.ok(Math.abs(Number(await p.locator('#place-height').inputValue())-76.2)<1e-8,'placement='+await p.locator('#place-height').inputValue()+' level='+await p.locator('#world-level-list input[type=number]').nth(1).inputValue()+' option='+await p.locator('#world-level option:checked').textContent());await p.locator('#world-close').click();await p.locator('#undo').click();assert.ok(Math.abs(Number(await p.locator('#place-height').inputValue())-50.8)<1e-8);await p.locator('#redo').click();assert.ok(Math.abs(Number(await p.locator('#place-height').inputValue())-76.2)<1e-8);
  await p.locator('#world-import').click();await p.waitForSelector('.encounter-card');assert.equal(await p.locator('.encounter-card').count(),1);await p.locator('.encounter-card').click();await p.locator('#world-fit').click();const box=await p.locator('canvas').boundingBox();await p.mouse.click(box.x+box.width*.5,box.y+box.height*.52);await p.waitForFunction(()=>document.querySelector('#count').textContent==='8');assert.ok(await p.locator('#world-group').isVisible());assert.match(await p.locator('#world-group-count').innerText(),/8 pieces/);
  await app.evaluate(()=>{const fs=process.mainModule.require('node:fs/promises'),rename=fs.rename;fs.rename=async(a,b)=>{if(String(b).endsWith('recovery.terrain'))await new Promise(r=>setTimeout(r,250));return rename(a,b);};fs.rename.__original=rename;});
  await p.locator('#x').fill('10');await p.locator('#x').press('Tab');await p.locator('#rotate').click();await p.locator('#height').fill('101.6');await p.waitForFunction(()=>document.querySelector('#status').textContent.includes('recovery kept'));assert.equal(await p.locator('#height').inputValue(),'101.6','Autosave must not reset the field while it is being edited');await app.evaluate(()=>{const fs=process.mainModule.require('node:fs/promises');fs.rename=fs.rename.__original||fs.rename;});await p.locator('#height').press('Tab');await p.locator('#save').click();await p.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Ready'));
  const saved=JSON.parse(await fs.readFile(worldFile,'utf8'));assert.equal(saved.version,2);assert.equal(saved.kind,'world');assert.equal(saved.world.widthMm,1219.2);assert.equal(saved.world.depthMm,1219.2);assert.equal(saved.items.length,8);assert.deepEqual(saved.items.map(i=>i.color),fixture.items.map(i=>i.color));assert.equal(new Set(saved.items.map(i=>i.encounterId)).size,1);assert.ok(saved.items.every(i=>i.rotation===90));assert.ok(Math.abs(saved.items.at(-1).y-109.6)<1e-8);assert.equal(saved.world.encounters[0].scene.items[0].y,0);
  await app.evaluate(({},f)=>global.__save=f,encounterFile);await p.locator('#world-save-encounter').click();await p.waitForTimeout(400);const encounter=JSON.parse(await fs.readFile(encounterFile,'utf8'));assert.equal(encounter.version,1);assert.equal(Math.min(...encounter.items.map(i=>i.y)),0);assert.ok(Math.abs(encounter.items.at(-1).y-8)<1e-8);const recovery=await p.evaluate(()=>window.desktop.loadRecovery());assert.equal(JSON.parse(recovery.data).kind,'world');
  await p.locator('#world-levels').click();await p.locator('#world-level-list .world-level-row').nth(1).getByRole('button',{name:'Hide',exact:true}).click();await p.locator('#world-close').click();assert.equal(await p.locator('#count').textContent(),'8');assert.ok(await p.locator('#world-group').isHidden());
  await app.evaluate(({},f)=>global.__save=f,worldFile);await p.locator('#save').click();await app.evaluate(({},f)=>global.__open=f,worldFile);await p.locator('#new').click();await p.locator('#open').click();assert.equal(await p.locator('#project-kind').textContent(),'WORLD / TABLE');assert.equal(await p.locator('.encounter-card').count(),1);assert.equal(await p.locator('#world-level option').count(),2);assert.equal(await p.locator('#count').textContent(),'8');
  await p.locator('#world-levels').click();await p.locator('#world-level-list .world-level-row').nth(1).getByRole('button',{name:'Show',exact:true}).click();await p.locator('#world-close').click();await p.locator('#top').click();await p.waitForTimeout(500);const b=await p.locator('canvas').boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;await p.mouse.click(cx,cy);await p.mouse.move(cx,cy);await p.mouse.down();await p.mouse.move(cx+70,cy+30,{steps:10});await p.mouse.up();await p.locator('#save').click();await p.waitForTimeout(300);const dragged=JSON.parse(await fs.readFile(worldFile,'utf8'));const delta=dragged.items[0].x-saved.items[0].x;assert.notEqual(delta,0);assert.ok(dragged.items.every((i,n)=>Math.abs((i.x-saved.items[n].x)-delta)<1e-6));
  await p.locator('#undo').click();await p.locator('#save').click();await p.waitForTimeout(300);assert.deepEqual(JSON.parse(await fs.readFile(worldFile,'utf8')).items,saved.items);
  await p.locator('#export').click();assert.match(await p.locator('#export-summary').textContent(),/8 pieces/);await p.locator('#close-print').click();await p.setViewportSize({width:1366,height:768});await p.locator('#world-fit').click();await p.evaluate(()=>document.querySelector('.toast')?.remove());await p.screenshot({path:'test-results/world-builder.png'});assert.deepEqual(errors,[]);
  console.log('PASS offline world: preset table, named elevated level, local encounter import, grouped placement/rotation/elevation/drag, undo, save/reopen, hidden levels retained in print export, separate encounter save preserves world recovery.');
 }finally{await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.destroy()));await app.close();}
})().catch(e=>{console.error(e);process.exit(1)});
