using System;using System.IO;using System.IO.Compression;using System.Net;using System.Net.Http;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;using System.Diagnostics;using System.Threading;using System.Threading.Tasks;using System.Web.Script.Serialization;using System.Windows.Forms;
[assembly:System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly:System.Reflection.AssemblyProduct("Terrain Foundry Launcher")]
namespace TerrainFoundry {
 public class Launcher:Form {
  const string Repo="MGN-Consultancy/TerrainFoundry",Publisher="MGN CONSULTANCY LIMITED";
  #if TEST_TRANSPORT
  static string Root=Environment.GetEnvironmentVariable("TERRAIN_TEST_ROOT"),StateFile=Path.Combine(Root,"state.json");
#else
  static string Root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"TerrainFoundryLauncher"),StateFile=Path.Combine(Root,"state.json");
#endif
  static JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=4194304};
  Label status=new Label{Dock=DockStyle.Fill,Text="Your worlds stay on this computer.",Padding=new Padding(24),AutoSize=false};
  Button update=new Button{Text="Install / check for updates",Dock=DockStyle.Bottom,Height=48},play=new Button{Text="Open installed editor (offline)",Dock=DockStyle.Bottom,Height=48};
  bool busy,launchAfterCancel; CancellationTokenSource cancellation=new CancellationTokenSource(); static HttpClient http=new HttpClient{Timeout=TimeSpan.FromMinutes(30)};
  [STAThread] public static void Main(string[] args){ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;Directory.CreateDirectory(Root);using(var mutex=new Mutex(false,"Local\\TerrainFoundryLauncher")){if(!mutex.WaitOne(0))return;Application.EnableVisualStyles();Application.Run(new Launcher());}}
  Launcher(){Text="Terrain Foundry — MGN Consultancy";Width=560;Height=275;StartPosition=FormStartPosition.CenterScreen;Controls.Add(status);Controls.Add(play);Controls.Add(update);play.Enabled=File.Exists(StateFile);play.Click+=(s,e)=>{if(busy){launchAfterCancel=true;cancellation.Cancel();status.Text="Stopping the update; your installed editor will open offline…";}else Launch();};update.Click+=async(s,e)=>await Update();FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};Shown+=async(s,e)=>{await Update();
#if TEST_TRANSPORT
 File.WriteAllText(Path.Combine(Root,"integration-result.txt"),status.Text);Environment.ExitCode=File.Exists(StateFile)?0:1;Close();
#endif
};}
  static Dictionary<string,object> Obj(object v){return (Dictionary<string,object>)v;}
  static string Str(Dictionary<string,object> o,string k){return Convert.ToString(o[k]);}
  static string Hash(string f){using(var s=File.OpenRead(f))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(s)).Replace("-","").ToLowerInvariant();}
  static string SafeHash(string s){if(s.Length!=64||s.Any(c=>!"0123456789abcdef".Contains(c)))throw new Exception("Invalid package digest.");return s;}
  static void Atomic(string p,string text){string t=p+".new";File.WriteAllText(t,text,new UTF8Encoding(false));if(File.Exists(p))File.Replace(t,p,p+".previous");else File.Move(t,p);}
  static Dictionary<string,object> ReadState(){return Json.Deserialize<Dictionary<string,object>>(File.ReadAllText(StateFile));}
  static string Under(string root,string relative){string p=Path.GetFullPath(Path.Combine(root,relative));if(!p.StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new Exception("Unsafe package path.");return p;}
  static void VerifyPublisher(string file){var p=new ProcessStartInfo("powershell.exe"){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,RedirectStandardOutput=true};string script="$s=Get-AuthenticodeSignature -LiteralPath '"+file.Replace("'","''")+"';if($s.Status -ne 'Valid' -or !$s.TimeStamperCertificate -or $s.SignerCertificate.GetNameInfo([System.Security.Cryptography.X509Certificates.X509NameType]::SimpleName,$false) -ne '"+Publisher+"'){exit 1}";p.Arguments="-NoProfile -NonInteractive -EncodedCommand "+Convert.ToBase64String(Encoding.Unicode.GetBytes(script));using(var process=Process.Start(p)){if(!process.WaitForExit(90000)){process.Kill();throw new Exception("Publisher verification timed out.");}if(process.ExitCode!=0)throw new Exception("The package does not have a valid MGN Consultancy publisher signature.");}}
  async Task<byte[]> Download(Dictionary<string,object> p,string destination){string url=Str(p,"url"),hash=SafeHash(Str(p,"sha256"));if(!url.StartsWith("https://github.com/"+Repo+"/releases/download/",StringComparison.Ordinal))throw new Exception("Unapproved package source.");long size=Convert.ToInt64(p["size"]);if(size<=0||size>2147483648L)throw new Exception("Invalid package size.");
   #if TEST_TRANSPORT
   string fixture=Path.Combine(Environment.GetEnvironmentVariable("TERRAIN_TEST_RELEASE"),Path.GetFileName(new Uri(url).AbsolutePath));await Task.Run(()=>File.Copy(fixture,destination,true));if(new FileInfo(destination).Length!=size||Hash(destination)!=hash)throw new Exception("Fixture checksum mismatch.");return null;
#else
   using(var response=await http.GetAsync(url,HttpCompletionOption.ResponseHeadersRead,cancellation.Token)){response.EnsureSuccessStatusCode();using(var input=await response.Content.ReadAsStreamAsync())using(var output=new FileStream(destination,FileMode.Create,FileAccess.Write)){byte[] buffer=new byte[131072];long total=0;int n;while((n=await input.ReadAsync(buffer,0,buffer.Length,cancellation.Token))>0){total+=n;if(total>size)throw new Exception("Package exceeds signed size.");await output.WriteAsync(buffer,0,n,cancellation.Token);status.Text="Downloading "+Str(p,"name")+" — "+(total*100/size)+"%";}if(total!=size)throw new Exception("Incomplete package.");}}
   if(await Task.Run(()=>Hash(destination))!=hash)throw new Exception("Package checksum mismatch.");return null;
#endif
  }
  async Task<string> Install(Dictionary<string,object> package,bool client){string hash=SafeHash(Str(package,"sha256")),target=Path.Combine(Root,"packages",hash),complete=Path.Combine(target,"verified.json");if(File.Exists(complete)){await Task.Run(()=>CheckInventory(target,package));return target;}
   string stage=target+".partial-"+Guid.NewGuid().ToString("N"),zip=stage+".zip";Directory.CreateDirectory(stage);
   try{await Download(package,zip);status.Text="Verifying and unpacking "+Str(package,"name")+"…";await Task.Run(()=>{using(var archive=ZipFile.OpenRead(zip)){long total=0;foreach(var entry in archive.Entries){if((entry.ExternalAttributes&0x400)!=0||(entry.ExternalAttributes>>16&0xF000)==0xA000)throw new Exception("Links are not allowed in packages.");if(entry.FullName.Contains(':')||entry.FullName.Contains('\\'))throw new Exception("Unsafe archive entry.");string path=Under(stage,entry.FullName);total+=entry.Length;if(total>8589934592L)throw new Exception("Unpacked package exceeds limit.");if(entry.FullName.EndsWith("/")){Directory.CreateDirectory(path);continue;}Directory.CreateDirectory(Path.GetDirectoryName(path));entry.ExtractToFile(path,false);}}
    CheckInventory(stage,package);if(client)VerifyPublisher(Path.Combine(stage,"TerrainFoundry.exe"));var inventory=Directory.GetFiles(stage,"*",SearchOption.AllDirectories).ToDictionary(f=>f.Substring(stage.Length+1).Replace('\\','/'),f=>Hash(f));File.WriteAllText(Path.Combine(stage,"verified.json"),Json.Serialize(inventory));if(Directory.Exists(target))throw new Exception("Incomplete prior package exists; previous editor remains available.");Directory.Move(stage,target);});return target;
   }finally{if(File.Exists(zip))File.Delete(zip);if(Directory.Exists(stage))Directory.Delete(stage,true);}
  }
  static void CheckInventory(string folder,Dictionary<string,object> package){var entries=Obj(package["files"]);foreach(var file in Directory.GetFiles(folder,"*",SearchOption.AllDirectories)){string rel=file.Substring(folder.Length+1).Replace('\\','/');if(rel!="verified.json"&&!entries.ContainsKey(rel))throw new Exception("Unexpected installed file.");}foreach(var kv in entries)if(Hash(Under(folder,kv.Key))!=Convert.ToString(kv.Value))throw new Exception("Installed files changed; reinstall the affected package before opening it.");}
  static Dictionary<string,object> VerifyEnvelope(string envelope){var outer=Json.Deserialize<Dictionary<string,object>>(envelope);byte[] payload=Convert.FromBase64String(Str(outer,"payload")),signature=Convert.FromBase64String(Str(outer,"signature"));using(var rsa=new RSACryptoServiceProvider()){using(var stream=typeof(Launcher).Assembly.GetManifestResourceStream("update-public.xml"))using(var reader=new StreamReader(stream))rsa.FromXmlString(reader.ReadToEnd());if(!rsa.VerifyData(payload,"SHA256",signature))throw new Exception("Release signature invalid.");}return Json.Deserialize<Dictionary<string,object>>(Encoding.UTF8.GetString(payload));}
  async Task<string> FetchManifest(){
#if TEST_TRANSPORT
 return await Task.Run(()=>File.ReadAllText(Path.Combine(Environment.GetEnvironmentVariable("TERRAIN_TEST_RELEASE"),"channel.json")));
#else
 using(var limited=CancellationTokenSource.CreateLinkedTokenSource(cancellation.Token)){limited.CancelAfter(TimeSpan.FromSeconds(12));using(var response=await http.GetAsync("https://github.com/"+Repo+"/releases/latest/download/channel.json",HttpCompletionOption.ResponseHeadersRead,limited.Token)){response.EnsureSuccessStatusCode();using(var input=await response.Content.ReadAsStreamAsync())using(var output=new MemoryStream()){byte[] b=new byte[16384];int n;while((n=await input.ReadAsync(b,0,b.Length,limited.Token))>0){if(output.Length+n>4194304)throw new Exception("Manifest too large.");output.Write(b,0,n);}return Encoding.UTF8.GetString(output.ToArray());}}}
#endif
}
  new async Task Update(){if(busy)return;busy=true;cancellation=new CancellationTokenSource();update.Enabled=false;play.Enabled=File.Exists(StateFile);try{status.Text="Checking the signed GitHub release…";http.DefaultRequestHeaders.UserAgent.ParseAdd("TerrainFoundryLauncher/1.0");string envelope=await FetchManifest();if(envelope.Length>4194304)throw new Exception("Manifest too large.");var outer=Json.Deserialize<Dictionary<string,object>>(envelope);byte[] payload=Convert.FromBase64String(Str(outer,"payload")),signature=Convert.FromBase64String(Str(outer,"signature"));using(var rsa=new RSACryptoServiceProvider()){using(var stream=typeof(Launcher).Assembly.GetManifestResourceStream("update-public.xml"))using(var reader=new StreamReader(stream))rsa.FromXmlString(reader.ReadToEnd());if(!rsa.VerifyData(payload,"SHA256",signature))throw new Exception("Release signature invalid.");}
    var release=VerifyEnvelope(envelope);if(Convert.ToInt32(release["schema"])!=1||Str(release,"repository")!=Repo)throw new Exception("Unsupported release.");long sequence=Convert.ToInt64(release["sequence"]);if(File.Exists(StateFile)&&sequence<Convert.ToInt64(ReadState()["sequence"]))throw new Exception("Refusing an older update manifest.");
    var launcher=Obj(release["launcher"]);if(new Version(Str(launcher,"version"))>typeof(Launcher).Assembly.GetName().Version){string next=Path.Combine(Root,"TerrainFoundryLauncher-next.exe");await Download(launcher,next);await Task.Run(()=>VerifyPublisher(next));string destination=Path.Combine(Root,"TerrainFoundryLauncher.exe");File.Copy(next,destination+".pending",true);WriteRestart(destination);status.Text="Launcher update verified. Restarting…";busy=false;Close();return;}
    string client=await Install(Obj(release["client"]),true);var assets=new Dictionary<string,string>();foreach(var p in (System.Collections.IEnumerable)release["assets"]){var asset=Obj(p);assets.Add(Str(asset,"id"),await Install(asset,false));}
    var state=new Dictionary<string,object>{{"schema",1},{"sequence",sequence},{"version",release["version"]},{"client",client},{"assets",assets},{"envelope",envelope}};Atomic(StateFile,Json.Serialize(state));status.Text="Ready — "+Str(release,"version")+". Your scenes remain on this PC. Updates apply the next time you open the editor.";
   }catch(Exception e){status.Text="Update unavailable: "+e.Message+(File.Exists(StateFile)?"\nYour installed editor is still available offline.":"\nFirst installation requires a published release and an internet connection.");}finally{busy=false;update.Enabled=true;play.Enabled=File.Exists(StateFile);if(launchAfterCancel){launchAfterCancel=false;Launch();}}}
  static void WriteRestart(string target){string script=Path.Combine(Root,"finish-launcher-update.ps1");string t=target.Replace("'","''");File.WriteAllText(script,"$ErrorActionPreference='Stop';Wait-Process -Id "+Process.GetCurrentProcess().Id+" -ErrorAction SilentlyContinue;Move-Item -LiteralPath '"+t+".pending' -Destination '"+t+"' -Force;Start-Process -FilePath '"+t+"'");Process.Start(new ProcessStartInfo("powershell.exe","-NoProfile -NonInteractive -WindowStyle Hidden -File \""+script+"\""){UseShellExecute=false,CreateNoWindow=true});}
  async void Launch(){if(busy)return;busy=true;play.Enabled=false;try{var state=ReadState();string client=Str(state,"client");var release=VerifyEnvelope(Str(state,"envelope"));await Task.Run(()=>CheckInventory(client,Obj(release["client"])));var assets=Obj(state["assets"]);foreach(var a in (System.Collections.IEnumerable)release["assets"]){var pack=Obj(a);await Task.Run(()=>CheckInventory(Convert.ToString(assets[Str(pack,"id")]),pack));}var start=new ProcessStartInfo(Path.Combine(client,"TerrainFoundry.exe")){UseShellExecute=false,WorkingDirectory=client};start.EnvironmentVariables["TERRAIN_ASSET_PACKS"]=Json.Serialize(assets);Process.Start(start);status.Text="Editor opened. Projects are saved locally.";}catch(Exception e){status.Text=e.Message;}finally{busy=false;play.Enabled=File.Exists(StateFile);}}
 }
}





