using System;using System.IO;using System.Collections.Generic;using System.Linq;using System.Reflection;using System.Web.Script.Serialization;
namespace TerrainFoundry {public class LauncherTests{
 static object Call(string name,params object[] args){try{return typeof(Launcher).GetMethod(name,BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,args);}catch(TargetInvocationException e){throw e.InnerException;}}
 static void Reject(Action action,string name){try{action();}catch{Console.WriteLine("PASS rejection: "+name);return;}throw new Exception("Not rejected: "+name);}
 public static int Main(string[] args){try{string manifest=File.ReadAllText(args[0]);var parsed=(Dictionary<string,object>)Call("VerifyEnvelope",manifest);if(parsed.ContainsKey("assets")){var packs=(System.Collections.ICollection)parsed["assets"];if(packs.Count==0)throw new Exception("No scenery packs");}Console.WriteLine("PASS signed manifest");var json=new JavaScriptSerializer();var envelope=json.Deserialize<Dictionary<string,object>>(manifest);var bytes=Convert.FromBase64String((string)envelope["payload"]);bytes[bytes.Length/2]^=1;envelope["payload"]=Convert.ToBase64String(bytes);Reject(()=>Call("VerifyEnvelope",json.Serialize(envelope)),"tampered manifest");string root=Path.Combine(Path.GetTempPath(),"terrain-launcher-test-"+Guid.NewGuid());Directory.CreateDirectory(root);Reject(()=>Call("Under",root,"../escape.exe"),"zip traversal");Reject(()=>Call("Under",root,Path.GetPathRoot(root)+"outside.exe"),"absolute zip path");Reject(()=>Call("SafeHash","../bad"),"unsafe digest path");string file=Path.Combine(root,"client.exe");File.WriteAllText(file,"original");string hash=(string)Call("Hash",file);var package=new Dictionary<string,object>{{"files",new Dictionary<string,object>{{"client.exe",hash}}}};Call("CheckInventory",root,package);File.WriteAllText(file,"tampered");Reject(()=>Call("CheckInventory",root,package),"tampered installed client");File.Delete(file);Reject(()=>Call("CheckInventory",root,package),"missing installed client");
 string content=Path.Combine(root,"content");Directory.CreateDirectory(Path.Combine(content,"models"));byte[] model={1,2,3,4,5,6};File.WriteAllBytes(Path.Combine(content,"models","r-001.bin"),model);string modelHash=(string)Call("Hash",Path.Combine(content,"models","r-001.bin"));var part=new Dictionary<string,object>{{"vertices",1},{"indices",0},{"length",24}};var piece=new Dictionary<string,object>{{"file","models/r-001.bin"},{"raw",part},{"connected",part}};var index=new Dictionary<string,object>{{"r-001",piece}};File.WriteAllText(Path.Combine(content,"index.json"),json.Serialize(index));var files=new Dictionary<string,object>{{"models/r-001.bin",new Dictionary<string,object>{{"sha256",modelHash},{"size",model.Length},{"name","model.bin"},{"url","https://github.com/MGN-Consultancy/TerrainFoundry/releases/download/v-test/model.bin"}}}};var contentPack=new Dictionary<string,object>{{"id","starter"},{"files",files},{"index",index}};Call("CheckContent",content,contentPack);Console.WriteLine("PASS file-level scenery integrity");File.WriteAllBytes(Path.Combine(content,"models","r-001.bin"),new byte[]{9,9,9});Reject(()=>Call("CheckContent",content,contentPack),"changed scenery file");string legacy=Path.Combine(root,"legacy");Directory.CreateDirectory(legacy);byte[] packed={99,98,1,2,3,4,5,6,97};File.WriteAllBytes(Path.Combine(legacy,"meshes.bin"),packed);var legacyPiece=new Dictionary<string,object>{{"offset",2},{"raw",new Dictionary<string,object>{{"length",2}}},{"connected",new Dictionary<string,object>{{"length",4}}}};File.WriteAllText(Path.Combine(legacy,"index.json"),json.Serialize(new Dictionary<string,object>{{"r-001",legacyPiece}}));string migrated=Path.Combine(root,"migrated.bin");if(!(bool)Call("MigrateLegacyPiece",legacy,"models/r-001.bin",migrated,modelHash)||!File.ReadAllBytes(migrated).SequenceEqual(model))throw new Exception("Legacy pack migration did not preserve the selected model bytes");Console.WriteLine("PASS local migration from combined scenery packs");string client=Path.Combine(root,"client-files");Directory.CreateDirectory(client);File.WriteAllText(Path.Combine(client,"client.exe"),"original");var clientFiles=new Dictionary<string,object>{{"client.exe",new Dictionary<string,object>{{"sha256",hash}}}};var clientSet=new Dictionary<string,object>{{"files",clientFiles}};Call("CheckClient",client,clientSet);Console.WriteLine("PASS file-level editor integrity");Directory.Delete(root,true);Console.WriteLine("PASS launcher trust and local integrity checks");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}}


