import test from 'node:test';import assert from 'node:assert/strict';import {randomBytes,generateKeyPairSync,sign} from 'node:crypto';import {premiumDelivery} from '../src/premium-delivery.mjs';import {encryptPack,readPackFile} from '../src/premium-pack.mjs';
function setup(options={}){const values=new Map(),tails=new Map(),mail=[],issuer=generateKeyPairSync('ed25519'),device=generateKeyPairSync('ed25519'),publicKey=device.publicKey.export({format:'pem',type:'spki'});let time=1000000,settled=false;
 const store={async put(p,v,o){if(o?.conditions?.ifNoneMatch==='*'&&values.has(p))throw Object.assign(Error('exists'),{statusCode:412});values.set(p,structuredClone(v));},async get(p){return structuredClone(values.get(p)||null);},async remove(p){values.delete(p);},async *list(prefix){for(const key of values.keys())if(key.startsWith(prefix))yield key;},async lock(p,fn){const previous=tails.get(p)||Promise.resolve();let release;tails.set(p,new Promise(r=>release=r));await previous;try{return await fn(await store.get(p),v=>store.put(p,v));}finally{release();}},async budget(p,max){const key='limit/'+p,v=values.get(key)||0;if(v>=max)throw Object.assign(Error('limited'),{status:429});values.set(key,v+1);}};
 const env={PREMIUM_TOKEN_SECRET:randomBytes(32).toString('base64'),PREMIUM_CODE_HASH_KEY:randomBytes(32).toString('base64'),PREMIUM_OUTBOX_KEY:randomBytes(32).toString('base64'),PREMIUM_SIGNING_KEY:issuer.privateKey.export({format:'pem',type:'pkcs8'}),PAYPAL_MERCHANT_ID:'MERCHANT',PREMIUM_SITE_ORIGIN:'https://terrainfoundry.co.uk',PREMIUM_SERVICE_ENABLED:'true',PREMIUM_PRODUCTS_JSON:JSON.stringify([options.product||{id:'tf-test',name:'Test pack',currency:'GBP',priceMinor:999,deviceAllowance:2,readyForSale:true}])};
 const paypal={async call(_p,_m,body){values.set('created-unit',body.purchase_units[0]);return {id:'ORDER1',links:[{rel:'approve',href:'https://paypal.example/approve'}]};},async get(){const u=values.get('created-unit');return {id:'ORDER1',status:settled?'COMPLETED':'CREATED',purchase_units:[{...u,payments:{captures:[{id:'CAPTURE1',status:'COMPLETED',amount:u.amount,final_capture:true}]}}]};},async verifiedEvent(){return true;}};
 const service=premiumDelivery({store,paypal,env,now:()=>time,sendMail:async m=>{mail.push(m);return {id:'MAIL1'};},downloadLink:async()=> 'https://private.blob.core.windows.net/premium-packs/blob?temporary-token'});
 return {values,service,mail,issuer,device,publicKey,settle:()=>settled=true,expire:()=>time+=3600001,async login(){const r=await service.loginStart({email:'buyer@example.com',publicKey},'127.0.0.1');const otp=mail.at(-1).text.match(/\b\d{6}\b/)[0];return (await service.loginVerify({requestId:r.requestId,otp,publicKey})).session;}};
}
test('pack ciphertext, signature, hash and authenticated entry prevent tampering',()=>{const issuer=generateKeyPairSync('ed25519'),pack=encryptPack({packId:'tf-test',version:'1.0.0',files:[{path:'editor/piece.bin',bytes:Buffer.from('PRIVATE MESH')}],signingKey:issuer.privateKey});assert.equal(pack.blob.includes(Buffer.from('PRIVATE MESH')),false);const args={...pack,publicKey:issuer.publicKey,path:'editor/piece.bin'};assert.equal(readPackFile(args).toString(),'PRIVATE MESH');const corrupt=Buffer.from(pack.blob);corrupt[0]^=1;assert.throws(()=>readPackFile({...args,blob:corrupt}),/inventory/);assert.throws(()=>readPackFile({...args,key:randomBytes(32)}));assert.throws(()=>readPackFile({...args,publicKey:generateKeyPairSync('ed25519').publicKey}),/signature/);});
test('OTP is one-use, device bound, has bounded attempts and expires sessions',async()=>{const f=setup(),start=await f.service.loginStart({email:'buyer@example.com',publicKey:f.publicKey},'peer'),otp=f.mail.at(-1).text.match(/\b\d{6}\b/)[0];await assert.rejects(f.service.loginVerify({...start,otp,publicKey:generateKeyPairSync('ed25519').publicKey.export({format:'pem',type:'spki'})}),/expired/);await f.service.loginVerify({...start,otp,publicKey:f.publicKey});await assert.rejects(f.service.loginVerify({...start,otp,publicKey:f.publicKey}),/expired/);const t=await f.login();f.expire();await assert.rejects(f.service.checkout(t,{packId:'tf-test',publicKey:f.publicKey}),/again/);});
test('payment settlement -> one emailed code -> proof activation -> scoped download; replay and other devices fail',async()=>{const f=setup(),t=await f.login(),pack=encryptPack({packId:'tf-test',version:'1.0.0',files:[{path:'editor/one.bin',bytes:Buffer.from('mesh')}],signingKey:f.issuer.privateKey});f.values.set('catalogue/tf-test.json',{approved:true,blob:'packs/tf-test/1.0.0/'+JSON.parse(Buffer.from(pack.manifest.payload,'base64')).sha256+'.tfc',manifest:pack.manifest,key:pack.key.toString('base64')});await f.service.checkout(t,{packId:'tf-test',publicKey:f.publicKey});await assert.rejects(f.service.confirm(t,{orderId:'ORDER1'}),/settled/);assert.equal(f.values.has('premium/orders/ORDER1.json'),false);f.settle();const r=await f.service.confirm(t,{orderId:'ORDER1'});await f.service.outbox();const code=f.mail.at(-1).text.match(/TF-[A-Z2-7]{32}/)[0];assert.ok(!JSON.stringify([...f.values]).includes(code));const challenge=await f.service.challenge(t,{code,publicKey:f.publicKey}),sig=sign(null,Buffer.from(challenge.message),f.device.privateKey).toString('base64');const {entitlement}=await f.service.activate(t,{code,publicKey:f.publicKey,...challenge,signature:sig});const d=await f.service.downloadChallenge(t,{entitlement,publicKey:f.publicKey}),args={entitlement,publicKey:f.publicKey,...d,signature:sign(null,Buffer.from(d.message),f.device.privateKey).toString('base64')};const result=await f.service.download(t,args);assert.equal(result.key,pack.key.toString('base64'));await assert.rejects(f.service.download(t,args),/expired/);await assert.rejects(f.service.downloadChallenge(t,{entitlement,publicKey:generateKeyPairSync('ed25519').publicKey.export({format:'pem',type:'spki'})}),/another computer/);assert.equal((await f.service.confirm(t,{orderId:'ORDER1'})).licenceId,r.licenceId);await f.service.webhook(new Headers(),{event_type:'PAYMENT.CAPTURE.REFUNDED',resource:{id:'REFUND1',supplementary_data:{related_ids:{capture_id:'CAPTURE1'}}}});await assert.rejects(f.service.downloadChallenge(t,{entitlement,publicKey:f.publicKey}),/unavailable/);await assert.rejects(f.service.confirm(t,{orderId:'ORDER1'}),/revoked/);});
test('unfinished pack never opens checkout',async()=>{const f=setup(),t=await f.login();await assert.rejects(f.service.checkout(t,{packId:'tf-test',publicKey:f.publicKey}),/not ready/);});

test('one paid collection issues a code for signed child bundles and permits a scoped STL download',async()=>{
 const product={id:'tf-collection',name:'Collection',currency:'GBP',priceMinor:999,deviceAllowance:2,readyForSale:true,bundleIds:['tf-child-one','tf-child-two'],licenceVersion:'2026-10-06',stlBlob:'digital/tf-collection/1.0.0/'+ 'a'.repeat(64)+'.zip',stlSha256:'a'.repeat(64)};
 const f=setup({product}),t=await f.login();
 for(const id of product.bundleIds){const pack=encryptPack({packId:id,version:'1.0.0',files:[{path:'catalogue.json',bytes:Buffer.from('{}')}],signingKey:f.issuer.privateKey});const m=JSON.parse(Buffer.from(pack.manifest.payload,'base64'));f.values.set('catalogue/'+id+'.json',{approved:true,blob:'packs/'+id+'/1.0.0/'+m.sha256+'.tfc',manifest:pack.manifest,key:pack.key.toString('base64')});}
 const checkout={packId:product.id,publicKey:f.publicKey};await assert.rejects(f.service.checkout(t,checkout),/accept/);
 await f.service.checkout(t,{...checkout,licenceVersion:product.licenceVersion,acceptLicence:true,immediateSupply:true});assert.equal(f.values.get('checkout/ORDER1.json').consent.immediateSupply,true);f.settle();await f.service.confirm(t,{orderId:'ORDER1'});await f.service.outbox();
 const email=f.mail.at(-1).text,code=email.match(/TF-[A-Z2-7]{32}/)[0];assert.match(email,/GBP 9.99/);assert.match(email,/physical models/);assert.match(email,/cancellation/);
 const c=await f.service.challenge(t,{code,publicKey:f.publicKey}),activated=await f.service.activate(t,{code,publicKey:f.publicKey,...c,signature:sign(null,Buffer.from(c.message),f.device.privateKey).toString('base64')});
 async function download(bundleId){const d=await f.service.downloadChallenge(t,{entitlement:activated.entitlement,publicKey:f.publicKey});return f.service.download(t,{entitlement:activated.entitlement,publicKey:f.publicKey,...d,signature:sign(null,Buffer.from(d.message),f.device.privateKey).toString('base64'),bundleId});}
 const result=await download();assert.equal(result.bundles.length,2);for(const b of result.bundles){const payload=JSON.parse(Buffer.from(b.entitlement.payload,'base64'));assert.equal(payload.parentPackId,product.id);assert.ok(product.bundleIds.includes(payload.packId));}
 assert.equal((await download('tf-child-one')).bundles.length,1);await assert.rejects(download('tf-unrelated'),/not part/);
 assert.equal((await f.service.files(t,{code})).sha256,product.stlSha256);await assert.rejects(f.service.files(t,{code:'TF-'+'A'.repeat(32)}),/code/);
 await f.service.webhook(new Headers(),{event_type:'PAYMENT.CAPTURE.REFUNDED',resource:{supplementary_data:{related_ids:{capture_id:'CAPTURE1'}}}});await assert.rejects(f.service.files(t,{code}),/available/);
});
