import test from 'node:test';import assert from 'node:assert/strict';import {randomBytes,generateKeyPairSync,sign,verify} from 'node:crypto';import {premiumLicensing} from '../src/premium-licensing.mjs';import {premiumDeliveryEmail} from '../src/premium-email.mjs';
function fixture(){const values=new Map(),tails=new Map(),issuer=generateKeyPairSync('ed25519');let clock=1000000,receipt={id:'ORDER1',status:'COMPLETED',merchantId:'MERCHANT',packId:'tf-willowbrook-village',currency:'GBP',amountMinor:999,buyerEmail:'buyer@example.com'};
 const store={async put(p,v,o){if(o?.conditions?.ifNoneMatch==='*'&&values.has(p))throw Object.assign(Error('exists'),{statusCode:412});values.set(p,structuredClone(v));},async get(p){return structuredClone(values.get(p)||null);},async lock(p,fn){const tail=tails.get(p)||Promise.resolve();let release;const next=new Promise(r=>release=r);tails.set(p,next);await tail;try{return await fn(await store.get(p),v=>store.put(p,v));}finally{release();}}};
 const service=premiumLicensing({store,payments:{verifiedSettlement:async()=>receipt},buyers:{verify:async session=>session==='buyer'?{email:'buyer@example.com',emailVerified:true}:{email:'other@example.com',emailVerified:true},verifySupport:async s=>s==='operator'?{authorised:true,id:'operator-1'}:null},codeHashKey:randomBytes(32),outboxKey:randomBytes(32),signingKey:issuer.privateKey,merchantId:'MERCHANT',now:()=>clock});
 return {service,values,issuer,setReceipt:r=>receipt=r,expire:()=>clock+=400000};
}
const key=()=>{const k=generateKeyPairSync('ed25519');return {privateKey:k.privateKey,publicKey:k.publicKey.export({type:'spki',format:'pem'})};};
async function activation(f,code,k){const c=await f.service.challenge({code,session:'buyer',publicKey:k.publicKey});return f.service.activate({code,session:'buyer',publicKey:k.publicKey,challengeId:c.challengeId,signature:sign(null,Buffer.from(c.message),k.privateKey).toString('base64')});}
test('verified settlement issues one durable grant and resends the same encrypted code',async()=>{const f=fixture();const r=await Promise.all([f.service.settle('ORDER1'),f.service.settle('ORDER1')]);assert.equal(r[0].licenceId,r[1].licenceId);const first=await f.service.deliveryForOrder('ORDER1');await f.service.resend({code:first.code,session:'buyer'});assert.equal((await f.service.deliveryForOrder('ORDER1')).code,first.code);assert.ok(!JSON.stringify([...f.values.values()]).includes(first.code));const mail=premiumDeliveryEmail(first);assert.match(mail.text,/two computers/);assert.match(mail.text,/no extra charge/);assert.match(mail.text,/nigel\.webster@mgnconsultancy\.co\.uk/);});
test('amount, currency, merchant, product and pending payment cannot issue codes',async()=>{for(const change of [{amountMinor:998},{currency:'USD'},{merchantId:'OTHER'},{packId:'other-pack'},{status:'PENDING'}]){const f=fixture();f.setReceipt({id:'ORDER1',status:'COMPLETED',merchantId:'MERCHANT',packId:'tf-willowbrook-village',currency:'GBP',amountMinor:999,buyerEmail:'buyer@example.com',...change});await assert.rejects(f.service.settle('ORDER1'),/Payment has not been confirmed/);assert.equal(f.values.size,0);}});
test('concurrent devices cannot exceed two; same-device repair consumes no extra slot',async()=>{const f=fixture();await f.service.settle('ORDER1');const {code}=await f.service.deliveryForOrder('ORDER1'),keys=[key(),key(),key()];const attempts=await Promise.allSettled(keys.map(k=>activation(f,code,k)));assert.equal(attempts.filter(x=>x.status==='fulfilled').length,2);assert.equal(attempts.filter(x=>x.status==='rejected').length,1);const granted=attempts.findIndex(x=>x.status==='fulfilled');const grant=await activation(f,code,keys[granted]);assert.equal(verify(null,Buffer.from(grant.payload,'base64'),f.issuer.publicKey,Buffer.from(grant.signature,'base64')),true);assert.equal(JSON.parse(Buffer.from(grant.payload,'base64')).offlineUse,true);});
test('purchase email verification and device signature prevent stolen-code activation',async()=>{const f=fixture();await f.service.settle('ORDER1');const {code}=await f.service.deliveryForOrder('ORDER1'),k=key();await assert.rejects(f.service.challenge({code,session:'stranger',publicKey:k.publicKey}),/Verify the purchase email/);const c=await f.service.challenge({code,session:'buyer',publicKey:k.publicKey});await assert.rejects(f.service.activate({code,session:'buyer',publicKey:k.publicKey,challengeId:c.challengeId,signature:sign(null,Buffer.from(c.message),key().privateKey).toString('base64')}),/Device proof/);});
test('challenge replay/expiry fail and authenticated support releases old activation without a new licence',async()=>{const f=fixture();await f.service.settle('ORDER1');const {code}=await f.service.deliveryForOrder('ORDER1'),k=key(),c=await f.service.challenge({code,session:'buyer',publicKey:k.publicKey}),args={code,session:'buyer',publicKey:k.publicKey,challengeId:c.challengeId,signature:sign(null,Buffer.from(c.message),k.privateKey).toString('base64')};const grant=await f.service.activate(args);await assert.rejects(f.service.activate(args),/challenge expired/);const fingerprint=JSON.parse(Buffer.from(grant.payload,'base64')).deviceFingerprint;await assert.rejects(f.service.supportReset({operatorSession:'stranger',orderId:'ORDER1',deviceFingerprint:fingerprint}),/Support authorisation/);assert.equal((await f.service.supportReset({operatorSession:'operator',orderId:'ORDER1',deviceFingerprint:fingerprint})).remainingDevices,0);assert.equal((await f.service.deliveryForOrder('ORDER1')).code,code);const stale=await f.service.challenge({code,session:'buyer',publicKey:k.publicKey});f.expire();await assert.rejects(f.service.activate({...args,challengeId:stale.challengeId}),/challenge expired/);});
