import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {createPortal,playerSnapshot} from '../core.mjs';import {FileStore} from '../store.mjs';import {portalServer} from '../server.mjs';
const origin='http://127.0.0.1:5190';
const record=(title,visible=true)=>({id:randomUUID(),title,category:'Lore',body:'Original story',visible});
const handout=()=>({schema:1,kind:'campaign-player-handout',sourceCampaignId:randomUUID(),sourceRevision:1,name:'Test adventure',items:[record('A public clue'),record('Secret villain',false)],relationships:[],timeline:[],notes:[],maps:[],pins:[],characters:[],cover:null,apiKey:'not-stored',chat:['private-chat'],summary:'private-summary'});
async function fixture(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'terrain-portal-test-'));const mail=[];let clock=Date.now();const store=new FileStore(path.join(dir,'state.json')),portal=createPortal({store,sendMail:async m=>mail.push(m),origin,now:()=>clock});const tokenFrom=m=>/\#(?:login|invite)=([\w-]+)/.exec(m.text)[1];const login=async email=>{await portal.loginLink(email,'loopback-test');return portal.login(tokenFrom(mail.at(-1)));};try{await fn({portal,store,mail,login,tokenFrom,advance:n=>clock+=n,dir});}finally{await fs.rm(dir,{recursive:true,force:true});}}
test('sign-in requires expiring one-use email proof; state never stores plaintext tokens',()=>fixture(async({portal,login,mail,tokenFrom,store,advance})=>{const u=await login('dm@example.test'),t=tokenFrom(mail[0]);assert.equal(u.user.email,'dm@example.test');await assert.rejects(portal.login(t),e=>e.status===403);assert.doesNotMatch(JSON.stringify(await store.load()),new RegExp(t));await portal.loginLink('late@example.test','peer');const late=tokenFrom(mail.at(-1));advance(16*60000);await assert.rejects(portal.login(late),e=>e.status===403);await portal.logout(u.sessionToken,u.csrf);await assert.rejects(portal.me(u.sessionToken),e=>e.status===401);}));
test('server projection drops secrets and hidden relationship descendants',()=>{const h=handout(),hidden=h.items[1];h.relationships=[{id:randomUUID(),from:h.items[0].id,to:hidden.id,label:'Secret relationship',body:'',visible:true}];h.notes=[{id:randomUUID(),title:'Hidden child',body:'Secret note',itemId:hidden.id,visible:true}];const p=playerSnapshot(h);assert.equal(p.items.length,1);assert.equal(p.notes.length,0);assert.equal(p.relationships.length,0);assert.doesNotMatch(JSON.stringify(p),/Secret|apiKey|private-chat|private-summary/);});
test('invite binds verified email, grants membership once and revoked membership loses access immediately',()=>fixture(async({portal,login,mail,tokenFrom})=>{const dm=await login('dm@example.test'),player=await login('player@example.test'),other=await login('other@example.test');const c=await portal.publish(dm.sessionToken,dm.csrf,handout());await assert.rejects(portal.get(other.sessionToken,c.id),e=>e.status===404);await portal.invite(dm.sessionToken,dm.csrf,c.id,'player@example.test');const t=tokenFrom(mail.at(-1));await assert.rejects(portal.accept(other.sessionToken,other.csrf,t),e=>e.status===403);await portal.accept(player.sessionToken,player.csrf,t);await assert.rejects(portal.accept(player.sessionToken,player.csrf,t),e=>e.status===403);assert.equal((await portal.get(player.sessionToken,c.id)).role,'player');await assert.rejects(portal.invite(player.sessionToken,player.csrf,c.id,'other@example.test'),e=>e.status===403);await portal.revoke(dm.sessionToken,dm.csrf,c.id,player.user.id);await assert.rejects(portal.get(player.sessionToken,c.id),e=>e.status===404);}));
test('stale publish and stale note edits conflict, players cannot edit other authors notes',()=>fixture(async({portal,login,mail,tokenFrom})=>{const dm=await login('dm@example.test'),player=await login('player@example.test'),h=handout(),c=await portal.publish(dm.sessionToken,dm.csrf,h);h.sourceRevision=2;await assert.rejects(portal.publish(dm.sessionToken,dm.csrf,h,0),e=>e.status===409);assert.equal((await portal.publish(dm.sessionToken,dm.csrf,h,1)).revision,2);await portal.invite(dm.sessionToken,dm.csrf,c.id,'player@example.test');await portal.accept(player.sessionToken,player.csrf,tokenFrom(mail.at(-1)));const note=await portal.saveNote(dm.sessionToken,dm.csrf,c.id,{title:'Session note',body:'Shared'});await assert.rejects(portal.saveNote(player.sessionToken,player.csrf,c.id,{...note,body:'Changed'}),e=>e.status===403);await portal.saveNote(dm.sessionToken,dm.csrf,c.id,{...note,body:'Updated'});await assert.rejects(portal.saveNote(dm.sessionToken,dm.csrf,c.id,{...note,body:'Stale'}),e=>e.status===409);}));
test('CSRF is required for authenticated writes and email link requests are rate limited',()=>fixture(async({portal,login})=>{const dm=await login('dm@example.test');await assert.rejects(portal.publish(dm.sessionToken,'wrong',handout()),e=>e.status===403);await assert.rejects(portal.publish(dm.sessionToken,'é'.repeat(43),handout()),e=>e.status===403);await portal.loginLink('dm@example.test','peer');await portal.loginLink('dm@example.test','peer');await assert.rejects(portal.loginLink('dm@example.test','peer'),e=>e.status===429);}));
test('HTTP rejects foreign-origin writes and creates only HttpOnly scoped session cookies',()=>fixture(async({portal,mail,tokenFrom})=>{const server=portalServer({portal,origin,secureCookies:false});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;try{const call=(route,body,headers={})=>fetch(base+'/api/portal/'+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:origin,...headers},body:body===undefined?undefined:JSON.stringify(body)});assert.equal((await call('login-link',{email:'dm@example.test'},{Origin:'https://foreign.example'})).status,403);assert.equal((await call('me')).status,401);await call('login-link',{email:'dm@example.test'});const response=await call('login',{token:tokenFrom(mail.at(-1))}),cookie=response.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.match(cookie,/Path=\/api\/portal/);const state=await response.json();assert.equal(state.sessionToken,undefined);assert.equal((await call('me',undefined,{Cookie:cookie.split(';')[0]})).status,200);}finally{await new Promise(resolve=>server.close(resolve));}}));
