import Module from 'manifold-3d';
import fs from 'node:fs/promises';
const wasm=await Module();wasm.setup();const M=wasm.Manifold;
const G=25.4,assets={},stone=[.48,.45,.38],wood=[.32,.17,.075],plaster=[.81,.72,.53],slate=[.25,.31,.33];
let seed=9231;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const paint=(solid,c)=>solid.setProperties(3,(p)=>{p[0]=c[0];p[1]=c[1];p[2]=c[2];});
const box=(w,h,d,x=0,y=h/2,z=0,c=stone)=>paint(M.cube([w,h,d],true).translate([x,y,z]),c);
const union=p=>M.union(p);
function block(w,h,d,x,y,z){const bevel=Math.min(.6,h*.15);const pts=[];for(const yy of [-h/2,-h/2+bevel,h/2-bevel,h/2])for(const [xx,zz]of [[-1,-1],[-1,1],[1,-1],[1,1]]){const inset=Math.abs(yy)===h/2?bevel:0;pts.push([xx*(w/2-inset)+(rand()-.5)*.18,yy,zz*(d/2-inset)+(rand()-.5)*.2]);}const shade=.85+rand()*.28;return paint(M.hull(pts).translate([x,y,z]),stone.map(v=>v*shade));}
function stoneWall(width=2*G,opening=null){const height=2*G;const p=[box(width,height,4,0,height/2,0,[.30,.28,.23])];for(let row=0;row<9;row++){const rh=height/9;let x=-width/2;while(x<width/2-.2){const w=Math.min(width/2-x,(row%2&&x===-width/2?5:8)+rand()*5);p.push(block(w-.3,rh-.25,6,x+w/2,row*rh+rh/2,0));x+=w;}}let result=union(p);if(opening==='window'){result=result.subtract(box(16,22,20,0,29));const rim=[box(21,2,8,0,17),box(21,2,8,0,41),box(2,25,8,-9.5,29),box(2,25,8,9.5,29)];result=union([result,...rim]);}if(opening==='door'){const cut=union([box(21,27,20,0,13.5),paint(M.cylinder(20,10.5,10.5,32,true).rotate([90,0,0]).translate([0,27,0]),stone)]);result=result.subtract(cut);}return result;}
function timberWall(opening=null,width=2*G){const h=2*G;let body=box(width,h,4,0,h/2,0,plaster);const beams=[box(3.5,h,7,-width/2+1.75,h/2,0,wood),box(3.5,h,7,width/2-1.75,h/2,0,wood),box(width,3.5,7,0,1.75,0,wood),box(width,3.5,7,0,h-1.75,0,wood),box(width,3,7,0,h*.48,0,wood)];if(!opening){beams.push(box(3,h,7,0,h/2,0,wood));if(width>40)for(const sign of [-1,1])beams.push(box(2.7,width<40?17:26,6,0,0,0,wood).rotate([0,0,sign*32]).translate([sign*width*.24,13,0]));}let result=union([body,...beams]);if(opening==='window'){result=result.subtract(box(18,20,20,0,31));result=union([result,box(23,2.5,9,0,20,0,wood),box(23,2.5,8,0,42,0,wood),box(2.5,24,8,-10,31,0,wood),box(2.5,24,8,10,31,0,wood),box(1.5,20,5,0,31,0,wood),box(18,1.5,5,0,31,0,wood)]);}if(opening==='door'){result=result.subtract(box(20,36,20,0,18));result=union([result,box(3,39,8,-11,19.5,0,wood),box(3,39,8,11,19.5,0,wood),box(25,3,8,0,37.5,0,wood)]);}return result;}
function floor(timber=false){const p=[box(2*G,3,2*G,0,1.5,0,timber?wood:stone)];if(timber){for(let i=0;i<8;i++)p.push(box(2*G-.2,1.2,G/4-.3,0,3.1,-G+(i+.5)*G/4,wood.map(v=>v*(.8+rand()*.5))));}else{for(let x=0;x<4;x++)for(let z=0;z<4;z++){const b=block(G/2-.35,1.5,G/2-.35,-G+(x+.5)*G/2,3.25,-G+(z+.5)*G/2);p.push(b);}}return union(p);}
function roof(){const p=[];const angle=26.565,run=53,slant=Math.sqrt(run*run+26.5*26.5);for(const sign of [-1,1]){const section=[box(slant,2,2*G+6,0,0,0,slate)];for(let row=0;row<7;row++)for(let col=0;col<8;col++){const tw=(2*G+6)/8;section.push(box(slant/7+1.2,.9,tw-.22,-slant/2+(row+.5)*slant/7,1.1,-(2*G+6)/2+(col+.5)*tw,slate.map(v=>v*(.85+rand()*.35))));}p.push(union(section).rotate([0,0,sign*angle]).translate([-sign*run/2,14,0]));}p.push(box(3,3,2*G+6,0,28,0,slate));return union(p);}
function gable(){const shape=paint(M.hull([[-G*2,0,-2],[-G*2,0,2],[G*2,0,-2],[G*2,0,2],[0,G,-2],[0,G,2]]),plaster);const p=[shape,box(4,G,7,0,G/2,0,wood),box(G*4,3,7,0,1.5,0,wood)];const len=Math.sqrt((G*2)**2+G**2);for(const sign of [-1,1])p.push(box(len,3,7,0,0,0,wood).rotate([0,0,sign*26.565]).translate([-sign*G,G/2,0]));return union(p);}
function barrel(){const points=[];for(let i=0;i<24;i++){const a=i/24*Math.PI*2;for(const [y,r]of [[0,7],[3,8],[10,9],[17,8],[20,7]])points.push([Math.cos(a)*r,y,Math.sin(a)*r]);}const body=paint(M.hull(points),wood);const p=[body];for(const y of [3,16])p.push(paint(M.cylinder(1.7,8.4,8.4,32,true).rotate([90,0,0]).translate([0,y,0]),[.16,.18,.18]));return union(p);}
function stairs(){const p=[];for(let i=0;i<8;i++)p.push(box(G,3.5*(i+1),G/4+.15,0,3.5*(i+1)/2,-G+(i+.5)*G/4,stone));return union(p);}
function chimney(){return union([stoneWall(13).scale([1,.55,2]),box(17,3,16,0,29,0,stone)]);}
const specs=[['v-stone-wall','Fieldstone wall','Walls',()=>stoneWall()],['v-stone-short','Narrow fieldstone wall','Walls',()=>stoneWall(G)],['v-stone-window','Stone window','Walls',()=>stoneWall(2*G,'window')],['v-stone-door','Stone archway','Walls',()=>stoneWall(2*G,'door')],['v-tudor-wall','Timber & plaster wall','Walls',()=>timberWall()],['v-tudor-short','Narrow timber wall','Walls',()=>timberWall().scale([.5,1,1])],['v-tudor-window','Timber window','Walls',()=>timberWall('window')],['v-tudor-door','Timber doorway','Walls',()=>timberWall('door')],['v-stone-floor','Flagstone floor','Floors',()=>floor()],['v-timber-floor','Plank floor','Floors',()=>floor(true)],['v-roof','Slate roof section','Roofs',roof],['v-gable','Timber gable','Roofs',gable],['v-barrel','Banded barrel','Props',barrel],['v-stairs','Village steps','Details',stairs],['v-chimney','Stone chimney','Roofs',chimney]];
for(const [id,name,category,build]of specs){seed=9231;let solid=build();const bounds=solid.boundingBox();solid=solid.translate([0,-bounds.min[1],0]);if(solid.status()!=='NoError')throw Error(id+': '+solid.status());if(solid.decompose().length!==1)throw Error(id+' is disconnected');const mesh=solid.getMesh();const positions=[],colors=[];for(let i=0;i<mesh.vertProperties.length;i+=mesh.numProp){positions.push(...mesh.vertProperties.slice(i,i+3));colors.push(...mesh.vertProperties.slice(i+3,i+6));}assets[id]={name,category,positions,colors,indices:Array.from(mesh.triVerts),volume:solid.volume()};console.log(id,mesh.triVerts.length/3,'triangles');solid.delete();}
await fs.mkdir('src/generated',{recursive:true});await fs.writeFile('src/generated/village.json',JSON.stringify(assets));await fs.writeFile('src/village-kit.js','export const VILLAGE_KIT = '+JSON.stringify(specs.map(([id,name,category])=>({id,name,category,icon:'',hint:'Village collection · sculpted'})),null,2)+';\n');



export {M,G,box,block,paint,union,stoneWall,floor,stairs};
