// Original Terrain Foundry grotto sculpts. CC0; connector derivatives use the bundled OpenLOCK terms.
import fs from 'node:fs/promises';
import * as THREE from 'three';
import {wasm,M,noise,paint} from './sculpt-library.mjs';
import {naturalRock} from './natural-rock.mjs';
import {solidData,connectAsset} from '../src/openlock-build.js';
import {repairMeshData} from './clean-mesh-data.mjs';
const G=25.4,stone=[.43,.42,.36];
const tint=(s,c=stone)=>s.setProperties(3,(a,p)=>{const n=.9+.15*noise(p[0]*.25,p[1]*.3,p[2]*.25);c.forEach((v,i)=>a[i]=v*n);});
function lump(x,y,z,w,h,d,seed=1){return tint(M.sphere(1,24).refineToLength(.23).warp(p=>{const n=1+.16*noise(p[0]*4+seed,p[1]*4,p[2]*4);p[0]*=w*n;p[1]*=h*n;p[2]*=d*n;}).translate([x,y,z]));}
function floor(){return tint(M.cube([2*G,9,2*G],true).refineToLength(.85).warp(p=>{if(p[1]>4.49){const fade=Math.min(1,(G-Math.max(Math.abs(p[0]),Math.abs(p[2])))/3);p[1]+=.55*fade*noise(p[0]*.3,5,p[2]*.3);}}).translate([0,4.5,0]));}
function crystal(x,y,z,r,h,tilt=0){const stem=M.cylinder(h*.7,r,r*.86,6,false),tip=M.cylinder(h*.3,r*.86,.25,6,false).translate([0,0,h*.7]);return paint(stem.add(tip).rotate([-90,0,tilt]).translate([x,y,z]),[.34,.65,.68]);}
function drip(x,y,z,r,h){return tint(M.cylinder(h,r,.65,28,false).rotate([-90,0,0]).refineToLength(.7).warp(p=>{const t=p[1]/h,angle=Math.atan2(p[2],p[0]),ripple=1+.12*Math.sin(angle*9+t*3)+.045*noise(p[0],p[1]*.6,p[2]);p[0]*=ripple;p[2]*=ripple;}).translate([x,y,z]),[.60,.53,.39]);}
function mushroom(x,y,z,r,h,seed){const stem=tint(M.cylinder(h,1.9,1.3,24,false).rotate([-90,0,0]).translate([x,y,z]),[.66,.58,.40]);const cap=paint(M.sphere(1,48).warp(p=>{const angle=Math.atan2(p[2],p[0]),n=1+.05*Math.sin(angle*13+seed);p[0]*=r*n;p[2]*=r*n;p[1]=p[1]*r*.36+.13*Math.cos(angle*18);}).translate([x,y+h,z]),[.52,.31,.22]);const dots=[];for(let i=0;i<9;i++){const a=i*2.4+seed,rr=r*.65*Math.sqrt((i+1)/10);dots.push(paint(M.sphere(.7,12).scale([1,.5,1]).translate([x+Math.cos(a)*rr,y+h+r*.29,z+Math.sin(a)*rr]),[.80,.71,.49]));}return M.union([stem,cap,...dots]);}
function wall(kind){const parts=[naturalRock(2*G,43,10.8,31).translate([0,21.5,0])];for(let i=0;i<8;i++){const x=-21+i*6;parts.push(lump(x,14+(i%3)*7,3.3,4,10+(i%4)*2,3.8,i+21));parts.push(drip(x,3,4,2.3,18+(i%4)*6));}if(kind==='crystal')for(const [x,h,t]of [[-15,17,-14],[-8,24,8],[14,19,-8]])parts.push(crystal(x,8,6,2.6,h,t));if(kind==='fungi')for(const [x,y,r]of [[-15,16,5],[-8,27,4],[11,20,6],[17,31,3]])parts.push(paint(M.sphere(1,40).scale([r,1.5,r*.85]).translate([x,y,5]),[.49,.37,.25]));return M.union(parts);}
function entrance(){let rock=naturalRock(2*G,54,16,71).translate([0,27,0]);const tunnel=M.union([M.cube([25,30,40],true).translate([0,18,0]),M.cylinder(40,12.5,12.5,48,true).translate([0,33,0])]);rock=rock.subtract(tunnel);const chunks=[rock];for(let i=0;i<9;i++){const a=i*Math.PI/8;chunks.push(lump(Math.cos(a)*18,29+Math.sin(a)*18,5,4.5,5,5,i+5));}return M.union(chunks);}
function terrain(kind){const parts=[floor()];
 if(kind==='crystals'){for(let i=0;i<9;i++){const a=i*2.4,r=4+Math.sqrt(i)*5;parts.push(lump(Math.cos(a)*r,10,Math.sin(a)*r,5,2.2,4,i));parts.push(crystal(Math.cos(a)*r,10,Math.sin(a)*r,2.6+(i%3)*.7,10+(i%4)*6,(i%3-1)*11));}}
 if(kind==='fungi'){for(const [x,z,r,h]of [[-12,-9,8,19],[10,-9,7,14],[-4,10,6,11],[16,12,4,7],[-18,14,3,6]]){parts.push(lump(x,9,z,6,2,5,5));parts.push(mushroom(x,9,z,r,h,x));}}
 if(kind==='column'){parts.push(lump(0,13,0,13,6,11,8));for(let i=0;i<9;i++){const a=i*2.4,r=i?7:0;parts.push(drip(Math.cos(a)*r,9,Math.sin(a)*r,i?3.4:7,i?24+(i%4)*5:48));}}
 if(kind==='floor'){for(let i=0;i<11;i++){const x=-19+(i%4)*12,z=-18+Math.floor(i/4)*15;parts.push(lump(x,8.5,z,5.2,1.8+(i%3)*.5,5,i));}}
 if(kind==='pool'){for(let i=0;i<16;i++){const a=i*Math.PI/8;parts.push(lump(Math.cos(a)*19,10,Math.sin(a)*16,4.5,2.5,4,i));}parts.push(paint(M.cylinder(.7,14,14,80,false).rotate([-90,0,0]).scale([1,1,.8]).translate([0,9,0]),[.19,.43,.43]));for(let i=0;i<3;i++)parts.push(drip(-17+i*4,9,-15,2.4,8+i*4));}
 if(kind==='ramp'){parts.push(naturalRock(44,18,44,91).warp(p=>{p[1]=8.5+(p[1]+9)*(.14+(p[2]+22)/44*.86);}).setProperties(3,(c,p)=>{const shade=.9+.14*noise(p[0]*.4,p[1]*.4,p[2]*.4);stone.forEach((v,i)=>c[i]=v*shade);}));for(let i=0;i<6;i++){parts.push(lump(-20,10+i*2.3,i*7-18,3,3,4,i));parts.push(lump(20,10+i*2.3,i*7-18,3,2.5,4,i+7));}for(let i=0;i<7;i++)parts.push(lump((i%3-1)*11,12+i*1.6,-15+i*5,4,1.3,3,i));}
 return M.union(parts);
}
const specs=[['flowstone-wall','Flowstone grotto wall','Walls',()=>wall('plain')],['crystal-wall','Crystal-veined grotto wall','Walls',()=>wall('crystal')],['shelf-wall','Shelf-fungus grotto wall','Walls',()=>wall('fungi')],['arch','Weathered grotto entrance','Walls',entrance],['flagstone','Fractured grotto floor','Floors',()=>terrain('floor')],['crystals','Quartz grotto crystal bed','Terrain',()=>terrain('crystals')],['mushrooms','Spotted grotto mushroom grove','Terrain',()=>terrain('fungi')],['column','Fluted grotto stalagmite column','Terrain',()=>terrain('column')],['pool','Mineral grotto pool','Water',()=>terrain('pool')],['ramp','Eroded grotto ramp','Terrain',()=>terrain('ramp')]];
const raw=JSON.parse(await fs.readFile('src/generated/caves.json','utf8')),connected=JSON.parse(await fs.readFile('src/generated/openlock.json','utf8'));
const {CAVE_KIT}=await import('../src/cave-kit.js');const kit=CAVE_KIT.filter(k=>!k.id.startsWith('n-grotto-'));
for(const [slug,name,category,build]of specs){const id='n-grotto-'+slug;let solid=build();if(solid.status()!=='NoError')throw Error(id+solid.status());const d=repairMeshData({...solidData(solid),volume:solid.volume()},wasm);raw[id]={name,category,...d};const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(d.positions,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(d.colors,3));geo.setIndex(d.indices);connected[id]=repairMeshData(connectAsset(wasm,geo,category,id),wasm);if(!connected[id].openlock.ports.length)throw Error('Missing sockets '+id);kit.push({id,name,category,icon:'',hint:'Grotto / sculpted mineral layers, fractures and organic relief / integrated OpenLOCK'});solid.delete();geo.dispose();console.log(id,connected[id].indices.length/3,'triangles');}
await fs.writeFile('src/generated/caves.json',JSON.stringify(raw));await fs.writeFile('src/generated/openlock.json',JSON.stringify(connected));await fs.writeFile('src/cave-kit.js','export const CAVE_KIT = '+JSON.stringify(kit,null,2)+';\n');
