import {M,G,box,block,paint,union,stoneWall,floor,stairs} from './generate-village.mjs';
import fs from 'node:fs/promises';
const stone=[.38,.40,.39],iron=[.12,.15,.16],wood=[.31,.18,.08],assets={};
const heavy=(w=2*G)=>union([stoneWall(w).scale([1,1,1.25]),box(w,3,9,0,1.5,0,stone),box(w,3,9,0,2*G-1.5,0,stone)]);
function arch(gate=false){let s=stoneWall(2*G,'door').scale([1,1,1.3]);s=union([s,box(5,2*G,10,-G+2.5,G,0,stone),box(5,2*G,10,G-2.5,G,0,stone)]);if(gate){const p=[s,box(23,2,5,0,1,0,iron),box(23,2,3,0,17,0,iron)];for(let x=-9;x<=9;x+=4.5)p.push(box(1.7,40,2,x,20,0,iron));s=union(p);}return s;}
function curve(){const r=2*G,w=Math.PI*r/2;return stoneWall(w).warp(p=>{const a=(p[0]/w+.5)*Math.PI/2,rr=r+p[2];p[0]=Math.sin(a)*rr-r/2;p[2]=Math.cos(a)*rr-r/2;});}
function sewerWall(grate=false){let s=heavy();const cut=paint(M.cylinder(20,11,11,32,true).rotate([90,0,0]).translate([0,17,0]),stone);s=s.subtract(cut);const ring=paint(M.cylinder(10,13.5,13.5,32,true).subtract(M.cylinder(12,11,11,32,true)).rotate([90,0,0]).translate([0,17,0]),stone);const p=[s,ring];if(grate)for(let x=-8;x<=8;x+=4)p.push(box(1.8,26,2,x,17,0,iron));return union(p);}
function channel(){const p=[box(2*G,3,2*G,0,1.5,0,[.23,.29,.24])];for(const x of [-G+6,G-6]){p.push(box(12,9,2*G,x,4.5,0,stone));for(let z=0;z<4;z++)p.push(block(11.6,1.5,G/2-.3,x,9,-G+(z+.5)*G/2));}return union(p);}
function crypt(){let s=heavy();for(const x of [-13,13]){s=s.subtract(box(15,28,8,x,25,5));s=union([s,box(19,2.5,10,x,10,0,stone),box(19,2.5,10,x,40,0,stone),box(2.5,32,10,x-8.5,25,0,stone),box(2.5,32,10,x+8.5,25,0,stone)]);}return s;}
function tomb(){return union([box(22,3,38,0,1.5,0,stone),box(19,11,34,0,7,0,stone),box(22,3,38,0,13.5,0,[.48,.49,.46]),box(2,1.5,18,0,15,0,stone),box(11,1.5,2,0,15,4,stone)]);}
function column(){const p=[box(14,4,14,0,2,0,stone),box(10,42,10,0,25,0,stone),box(15,4,15,0,48,0,stone)];for(const y of [12,23,34])p.push(box(12,2,12,0,y,0,stone));return union(p);}
function mine(){return union([box(2*G,2.5,12,0,1.25,0,stone),box(6,2*G,8,-G+5,G,0,wood),box(6,2*G,8,G-5,G,0,wood),box(2*G,7,10,0,2*G-3,0,wood),box(3,19,7,0,0,0,wood).rotate([0,0,-40]).translate([-G+11,40,0]),box(3,19,7,0,0,0,wood).rotate([0,0,40]).translate([G-11,40,0])]);}
function mineFloor(){const p=[floor()];for(let z=-20;z<=20;z+=10)p.push(box(36,2,4,0,4,z,wood));for(const x of [-11,11])p.push(box(2,3,2*G,x,5,0,iron));return union(p);}
const specs=[['d-heavy-wall','Heavy dungeon wall','Walls',()=>heavy()],['d-heavy-short','Narrow dungeon wall','Walls',()=>heavy(G)],['d-heavy-low','Low dungeon wall','Walls',()=>heavy().scale([1,.5,1])],['d-arch','Reinforced archway','Walls',()=>arch()],['d-gate','Iron portcullis','Walls',()=>arch(true)],['d-curved-wall','Curved masonry wall','Walls',curve],['d-corner','Dungeon corner wall','Walls',()=>union([heavy(),heavy().rotate([0,90,0]).translate([-G,0,G])])],['d-floor','Dungeon flagstones','Floors',()=>floor()],['d-riser','Raised dungeon floor','Floors',()=>union([box(2*G,18,2*G,0,9,0,stone),floor().translate([0,17,0])])],['d-column','Banded stone column','Details',column],['d-stairs','Dungeon stair flight','Details',stairs],['d-sewer-wall','Sewer outfall','Walls',()=>sewerWall()],['d-sewer-grate','Barred sewer outfall','Walls',()=>sewerWall(true)],['d-channel','Sewer channel floor','Floors',channel],['d-crypt','Recessed crypt wall','Walls',crypt],['d-tomb','Raised stone tomb','Props',tomb],['d-mine','Timber mine support','Walls',mine],['d-track','Mine track floor','Floors',mineFloor]];
for(const [id,name,category,build]of specs){let s=build();s=s.translate([0,-s.boundingBox().min[1],0]);if(s.status()!=='NoError'||s.decompose().length!==1)throw Error(id+' is not one valid solid');const m=s.getMesh(),positions=[],colors=[];for(let i=0;i<m.vertProperties.length;i+=m.numProp){positions.push(...m.vertProperties.slice(i,i+3));colors.push(...m.vertProperties.slice(i+3,i+6));}assets[id]={name,category,positions,colors,indices:Array.from(m.triVerts),volume:s.volume()};console.log(id,m.triVerts.length/3,'triangles');s.delete();}
await fs.writeFile('src/generated/dungeon.json',JSON.stringify(assets));await fs.writeFile('src/dungeon-kit.js','export const DUNGEON_KIT = '+JSON.stringify(specs.map(([id,name,category])=>({id,name,category,icon:'',hint:'Dungeon collection · sculpted'})),null,2)+';\n');
