// Microphone media stays in WebRTC; only bounded tool calls cross the desktop bridge.
export function setupCampaignVoice({api,getCampaign,getTerrain,getView,getAudioDevices=()=>({}),onTranscript,onProposal,onAgentResult,onDictation,onStatus}){
 let pc=null,channel=null,stream=null,audio=null,timer=null,dictating=false,queue=Promise.resolve(),engine='realtime',liveText={user:'',assistant:''},liveTimers={},liveHistory='',closed=null,stopping=false;
 const send=event=>{if(channel?.readyState==='open')channel.send(JSON.stringify(event));};
 async function flushLive(role){clearTimeout(liveTimers[role]);const text=liveText[role];liveText[role]='';if(text)await onTranscript(role,text);}
 async function stop(){if(stopping)return;stopping=true;clearTimeout(timer);timer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;if(engine==='live'&&channel?.readyState==='open'){await new Promise(resolve=>{const timeout=setTimeout(resolve,3000);closed=()=>{clearTimeout(timeout);resolve();};send({type:'session.close'});});}if(channel)channel.onmessage=null;channel?.close();channel=null;await api.campaignVoiceStop();await queue;await flushLive('user');await flushLive('assistant');pc?.close();pc=null;if(audio){audio.pause();audio.srcObject=null;audio.remove();audio=null;}if(dictating){await api.campaignDictationStop();dictating=false;}stopping=false;onStatus('Microphone off');}
 async function talk(mode='talk'){
  if(pc||dictating)throw Error('Stop the current microphone session first');liveHistory='';liveText={user:'',assistant:''};engine='realtime';const id=getCampaign()?.id;if(!id)throw Error('Open a campaign first');
  try{const devices=getAudioDevices()||{},audioOptions={echoCancellation:true,noiseSuppression:true};if(devices.inputId)audioOptions.deviceId={exact:devices.inputId};stream=await navigator.mediaDevices.getUserMedia({audio:audioOptions,video:false});pc=new RTCPeerConnection();audio=document.createElement('audio');audio.autoplay=true;document.body.append(audio);pc.ontrack=e=>{audio.srcObject=e.streams[0];const play=async()=>{if(devices.outputId&&typeof audio.setSinkId==='function')await audio.setSinkId(devices.outputId);await audio.play();};play().catch(()=>onStatus('Voice is connected. Check the selected speaker or use Resume audio.'));};for(const track of stream.getTracks())pc.addTrack(track,stream);channel=pc.createDataChannel('oai-events');const pending=new Map();
   channel.onmessage=event=>{if(event.data.length>200000)return;let e;try{e=JSON.parse(event.data);}catch{return;}
    if(e.type==='session.closed')closed?.();queue=queue.then(async()=>{if(!pc||getCampaign()?.id!==id)return;
     if(['session.input_transcript.delta','session.output_transcript.delta'].includes(e.type)&&typeof e.delta==='string'){const role=e.type==='session.input_transcript.delta'?'user':'assistant';liveText[role]+=e.delta;if(liveText[role].length>30000)await flushLive(role);if(role==='user')liveHistory=(liveHistory+e.delta).slice(-5800);clearTimeout(liveTimers[role]);liveTimers[role]=setTimeout(()=>{queue=queue.then(()=>flushLive(role)).catch(error=>onStatus(error.message));},1200);}
     if(e.type==='session.started')onStatus('GPT-Live conversation listening · voice and backend AI billed');
     if(e.type==='session.delegation.created'&&e.delegation?.target==='client'){const delegation=e.delegation.id;if(typeof delegation!=='string'||pending.has(delegation))return;pending.set(delegation,true);await flushLive('user');await flushLive('assistant');let result;try{result=await api.campaignVoiceTool(id,'live_delegate',{transcript:liveHistory},getTerrain?.(),getView?.());if(result.agent)await onAgentResult?.(result.agent);for(const action of result.actions||[])onProposal(action);}catch{result={text:'The app could not complete this request. No change was applied. Check your backend AI settings or clarify the request.'};}send({type:'session.commentary.append',event_id:crypto.randomUUID(),delegation_id:delegation,content:(result.actions?.length?'Proposals are ready in the app for human review; nothing has been applied. ':'')+String(result.text||'Please clarify the request.').slice(0,1000)});}
     if(e.type==='conversation.item.input_audio_transcription.completed' &&e.transcript){if(mode==='dictate')onDictation(e.transcript);else await onTranscript('user',e.transcript);}
     if(e.type==='response.output_audio_transcript.done'&&e.transcript&&mode==='talk')await onTranscript('assistant',e.transcript);
     if(e.type==='response.function_call_arguments.done'&&mode==='talk'){
      if(pending.has(e.call_id))return;pending.set(e.call_id,true);let result;try{result=await api.campaignVoiceTool(id,e.name,JSON.parse(e.arguments),getTerrain?.(),getView?.());if(result.agent){await onAgentResult?.(result.agent);result={applied:result.applied===true,message:result.message};}if(result.proposed)onProposal(result.action);}catch{result={error:'The app rejected this request. Refresh context or ask for a simpler supported proposal.'};}
      send({type:'conversation.item.create',item:{type:'function_call_output',call_id:e.call_id,output:JSON.stringify(result)}});send({type:'response.create'});
     }
     if(e.type==='error')onStatus('Voice provider reported an error. Stop and check your API account.');
    }).catch(error=>onStatus(error.message));
   };
   channel.onopen=()=>onStatus(mode==='dictate'?'Online dictation listening · API billed':'Live conversation listening · API billed');
   pc.onconnectionstatechange=()=>{if(['failed','disconnected'].includes(pc?.connectionState))void stop();};
   await pc.setLocalDescription(await pc.createOffer());const reply=await api.campaignVoiceStart(id,pc.localDescription.sdp,mode,getTerrain?.(),getView?.());if(!reply){await stop();return;}engine=reply.provider||'realtime';await pc.setRemoteDescription({type:'answer',sdp:reply.sdp});timer=setTimeout(()=>void stop(),reply.maximumSeconds*1000);
  }catch(e){await stop();throw e;}
 }
 const unsubscribe=api.onCampaignDictation?.(event=>{if(event.text)onDictation(event.text);if(event.error){dictating=false;onStatus(event.error);}if(event.stage==='stopped'){dictating=false;onStatus('Dictation stopped');}});
 async function dictate(){if(pc||dictating)throw Error('Stop the current microphone session first');await api.campaignDictationStart();dictating=true;onStatus('Offline Windows dictation listening · words stay in your draft');}
 function mute(){if(dictating){onStatus('Offline dictation is listening. Use Stop microphone to stop it.');return;}for(const track of stream?.getAudioTracks()||[])track.enabled=!track.enabled;onStatus(stream?.getAudioTracks()[0]?.enabled?'Microphone listening':'Microphone muted');}
 return {talk,dictate,stop,mute,resume:()=>audio?.play(),active:()=>!!pc||dictating,activeMode:()=>dictating?'dictation':pc?'voice':'',dispose:async()=>{unsubscribe?.();await stop();}};
}
