// Original curved companions. Radius measures the floor edge, not the outside wall.
export const CURVE_KIT = [
  {
    "id": "a-001",
    "name": "Fortress curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-041",
      "r-206",
      "r-298"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 50.8 mm / fits r-041, r-206, r-298"
  },
  {
    "id": "a-002",
    "name": "Fortress curved wall · 1.50 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 76.19999999999999,
    "innerDepth": 76.19999999999999,
    "sweep": 90,
    "matches": [
      "r-047",
      "r-426"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 76.2 mm / fits r-047, r-426"
  },
  {
    "id": "a-003",
    "name": "Fortress curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 63.5,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-048"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 63.5 mm / fits r-048"
  },
  {
    "id": "a-004",
    "name": "Fortress curved wall · 0.50 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 25.4,
    "innerDepth": 25.4,
    "sweep": 90,
    "matches": [
      "r-049"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 25.4 mm / fits r-049"
  },
  {
    "id": "a-005",
    "name": "Fortress curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 63.5,
    "innerDepth": 63.5,
    "sweep": 90,
    "matches": [
      "r-050",
      "r-427"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 63.5 mm / fits r-050, r-427"
  },
  {
    "id": "a-006",
    "name": "Sewer curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Sewer",
    "recipe": "Sewer",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-078",
      "r-088"
    ],
    "shape": "curved-wall",
    "hint": "Sewer / 90° curve / inner radius 50.8 mm / fits r-078, r-088"
  },
  {
    "id": "a-007",
    "name": "Mine curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Mine",
    "recipe": "Mine",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-107",
      "r-108"
    ],
    "shape": "curved-wall",
    "hint": "Mine / 90° curve / inner radius 50.8 mm / fits r-107, r-108"
  },
  {
    "id": "a-008",
    "name": "Crypt curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Crypt",
    "recipe": "Crypt",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-146"
    ],
    "shape": "curved-wall",
    "hint": "Crypt / 90° curve / inner radius 50.8 mm / fits r-146"
  },
  {
    "id": "a-009",
    "name": "Crypt curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Crypt",
    "recipe": "Crypt",
    "radius": 63.5,
    "innerDepth": 63.5,
    "sweep": 90,
    "matches": [
      "r-147"
    ],
    "shape": "curved-wall",
    "hint": "Crypt / 90° curve / inner radius 63.5 mm / fits r-147"
  },
  {
    "id": "a-010",
    "name": "Ossuary wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ossuary",
    "recipe": "Ossuary",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [
      "r-187"
    ],
    "shape": "curved-wall",
    "hint": "Ossuary / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles / fits r-187"
  },
  {
    "id": "a-011",
    "name": "Ossuary curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ossuary",
    "recipe": "Ossuary",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-188",
      "r-377"
    ],
    "shape": "curved-wall",
    "hint": "Ossuary / 90° curve / inner radius 50.8 mm / fits r-188, r-377"
  },
  {
    "id": "a-012",
    "name": "Fortress wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [
      "r-207",
      "r-292"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles / fits r-207, r-292"
  },
  {
    "id": "a-013",
    "name": "Ruins curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ruins",
    "recipe": "Ruins",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-216"
    ],
    "shape": "curved-wall",
    "hint": "Ruins / 90° curve / inner radius 50.8 mm / fits r-216"
  },
  {
    "id": "a-014",
    "name": "Timber curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Timber",
    "recipe": "Timber",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-230",
      "r-251"
    ],
    "shape": "curved-wall",
    "hint": "Timber / 90° curve / inner radius 50.8 mm / fits r-230, r-251"
  },
  {
    "id": "a-015",
    "name": "Timber wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Timber",
    "recipe": "Timber",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [
      "r-237",
      "r-252"
    ],
    "shape": "curved-wall",
    "hint": "Timber / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles / fits r-237, r-252"
  },
  {
    "id": "a-016",
    "name": "Timber curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Timber",
    "recipe": "Timber",
    "radius": 63.5,
    "innerDepth": 63.5,
    "sweep": 90,
    "matches": [
      "r-253"
    ],
    "shape": "curved-wall",
    "hint": "Timber / 90° curve / inner radius 63.5 mm / fits r-253"
  },
  {
    "id": "a-017",
    "name": "Cavern curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Cavern",
    "recipe": "Cavern",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-268"
    ],
    "shape": "curved-wall",
    "hint": "Cavern / 90° curve / inner radius 50.8 mm / fits r-268"
  },
  {
    "id": "a-018",
    "name": "Cavern curved wall · 1.50 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Cavern",
    "recipe": "Cavern",
    "radius": 76.19999999999999,
    "innerDepth": 76.19999999999999,
    "sweep": 90,
    "matches": [
      "r-274"
    ],
    "shape": "curved-wall",
    "hint": "Cavern / 90° curve / inner radius 76.2 mm / fits r-274"
  },
  {
    "id": "a-019",
    "name": "Grating wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Grating",
    "recipe": "Grating",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [
      "r-321"
    ],
    "shape": "curved-wall",
    "hint": "Grating / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles / fits r-321"
  },
  {
    "id": "a-020",
    "name": "Grating curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Grating",
    "recipe": "Grating",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-327"
    ],
    "shape": "curved-wall",
    "hint": "Grating / 90° curve / inner radius 50.8 mm / fits r-327"
  },
  {
    "id": "a-021",
    "name": "Grating curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Grating",
    "recipe": "Grating",
    "radius": 63.5,
    "innerDepth": 63.5,
    "sweep": 90,
    "matches": [
      "r-330"
    ],
    "shape": "curved-wall",
    "hint": "Grating / 90° curve / inner radius 63.5 mm / fits r-330"
  },
  {
    "id": "a-022",
    "name": "Grating curved wall · 1.50 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Grating",
    "recipe": "Grating",
    "radius": 76.19999999999999,
    "innerDepth": 76.19999999999999,
    "sweep": 90,
    "matches": [
      "r-332"
    ],
    "shape": "curved-wall",
    "hint": "Grating / 90° curve / inner radius 76.2 mm / fits r-332"
  },
  {
    "id": "a-023",
    "name": "Grating wide curved wall · 2.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Grating",
    "recipe": "Grating",
    "radius": 114.3,
    "innerDepth": 114.3,
    "sweep": 90,
    "matches": [
      "r-333"
    ],
    "shape": "curved-wall",
    "hint": "Grating / 90° curve / inner radius 114.3 mm / spans two or more 50.8 mm tiles / fits r-333"
  },
  {
    "id": "a-024",
    "name": "Ossuary curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ossuary",
    "recipe": "Ossuary",
    "radius": 63.5,
    "innerDepth": 63.5,
    "sweep": 90,
    "matches": [
      "r-382"
    ],
    "shape": "curved-wall",
    "hint": "Ossuary / 90° curve / inner radius 63.5 mm / fits r-382"
  },
  {
    "id": "a-025",
    "name": "Smallstone wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Smallstone",
    "recipe": "Smallstone",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [
      "r-388",
      "r-400"
    ],
    "shape": "curved-wall",
    "hint": "Smallstone / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles / fits r-388, r-400"
  },
  {
    "id": "a-026",
    "name": "Smallstone curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Smallstone",
    "recipe": "Smallstone",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [
      "r-390",
      "r-398"
    ],
    "shape": "curved-wall",
    "hint": "Smallstone / 90° curve / inner radius 50.8 mm / fits r-390, r-398"
  },
  {
    "id": "a-027",
    "name": "Smallstone curved wall · 1.50 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Smallstone",
    "recipe": "Smallstone",
    "radius": 76.19999999999999,
    "innerDepth": 76.19999999999999,
    "sweep": 90,
    "matches": [
      "r-394"
    ],
    "shape": "curved-wall",
    "hint": "Smallstone / 90° curve / inner radius 76.2 mm / fits r-394"
  },
  {
    "id": "a-028",
    "name": "Smallstone wide curved wall · 2.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Smallstone",
    "recipe": "Smallstone",
    "radius": 114.3,
    "innerDepth": 114.3,
    "sweep": 90,
    "matches": [
      "r-397"
    ],
    "shape": "curved-wall",
    "hint": "Smallstone / 90° curve / inner radius 114.3 mm / spans two or more 50.8 mm tiles / fits r-397"
  },
  {
    "id": "a-029",
    "name": "Smallstone curved wall · 1.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Smallstone",
    "recipe": "Smallstone",
    "radius": 63.5,
    "innerDepth": 63.5,
    "sweep": 90,
    "matches": [
      "r-399"
    ],
    "shape": "curved-wall",
    "hint": "Smallstone / 90° curve / inner radius 63.5 mm / fits r-399"
  },
  {
    "id": "a-030",
    "name": "Fortress wide curved wall · 2.25 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 114.3,
    "innerDepth": 114.3,
    "sweep": 90,
    "matches": [
      "r-428"
    ],
    "shape": "curved-wall",
    "hint": "Fortress / 90° curve / inner radius 114.3 mm / spans two or more 50.8 mm tiles / fits r-428"
  },
  {
    "id": "a-031",
    "name": "Fortress gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Fortress",
    "recipe": "Fortress",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Fortress / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-032",
    "name": "Sewer wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Sewer",
    "recipe": "Sewer",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Sewer / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-033",
    "name": "Sewer gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Sewer",
    "recipe": "Sewer",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Sewer / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-034",
    "name": "Crypt wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Crypt",
    "recipe": "Crypt",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Crypt / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-035",
    "name": "Crypt gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Crypt",
    "recipe": "Crypt",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Crypt / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-036",
    "name": "Ossuary gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ossuary",
    "recipe": "Ossuary",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Ossuary / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-037",
    "name": "Mine wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Mine",
    "recipe": "Mine",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Mine / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-038",
    "name": "Mine gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Mine",
    "recipe": "Mine",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Mine / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-039",
    "name": "Baths curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Baths",
    "recipe": "Baths",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Baths / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-040",
    "name": "Baths wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Baths",
    "recipe": "Baths",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Baths / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-041",
    "name": "Baths gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Baths",
    "recipe": "Baths",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Baths / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-042",
    "name": "Ruins wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ruins",
    "recipe": "Ruins",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Ruins / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-043",
    "name": "Ruins gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Ruins",
    "recipe": "Ruins",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Ruins / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-044",
    "name": "Timber gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Timber",
    "recipe": "Timber",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Timber / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-045",
    "name": "Cavern wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Cavern",
    "recipe": "Cavern",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Cavern / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-046",
    "name": "Cavern gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Cavern",
    "recipe": "Cavern",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Cavern / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-047",
    "name": "Gothic curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Gothic",
    "recipe": "Gothic",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Gothic / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-048",
    "name": "Gothic wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Gothic",
    "recipe": "Gothic",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Gothic / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-049",
    "name": "Gothic gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Gothic",
    "recipe": "Gothic",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Gothic / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-050",
    "name": "Grating gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Grating",
    "recipe": "Grating",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Grating / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-051",
    "name": "Manor curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Manor",
    "recipe": "Manor",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Manor / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-052",
    "name": "Manor wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Manor",
    "recipe": "Manor",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Manor / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-053",
    "name": "Manor gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Manor",
    "recipe": "Manor",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Manor / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-054",
    "name": "Smallstone gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Smallstone",
    "recipe": "Smallstone",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Smallstone / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-055",
    "name": "Hollowdeep curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Hollowdeep",
    "recipe": "Cavern",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Hollowdeep / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-056",
    "name": "Hollowdeep wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Hollowdeep",
    "recipe": "Cavern",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Hollowdeep / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-057",
    "name": "Hollowdeep gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Hollowdeep",
    "recipe": "Cavern",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Hollowdeep / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-058",
    "name": "Blackwater curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Blackwater",
    "recipe": "Crypt",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Blackwater / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-059",
    "name": "Blackwater wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Blackwater",
    "recipe": "Crypt",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Blackwater / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-060",
    "name": "Blackwater gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Blackwater",
    "recipe": "Crypt",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Blackwater / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-061",
    "name": "Greywatch curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Greywatch",
    "recipe": "Gothic",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Greywatch / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-062",
    "name": "Greywatch wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Greywatch",
    "recipe": "Gothic",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Greywatch / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-063",
    "name": "Greywatch gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Greywatch",
    "recipe": "Gothic",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Greywatch / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-064",
    "name": "Quarry curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Quarry",
    "recipe": "Fortress",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Quarry / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-065",
    "name": "Quarry wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Quarry",
    "recipe": "Fortress",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Quarry / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-066",
    "name": "Quarry gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Quarry",
    "recipe": "Fortress",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Quarry / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-067",
    "name": "Village stone curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Village stone",
    "recipe": "Smallstone",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Village stone / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-068",
    "name": "Village stone wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Village stone",
    "recipe": "Smallstone",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Village stone / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-069",
    "name": "Village stone gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Village stone",
    "recipe": "Smallstone",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Village stone / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-070",
    "name": "Village timber curved wall · 1 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Village timber",
    "recipe": "Timber",
    "radius": 50.8,
    "innerDepth": 50.8,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Village timber / 90° curve / inner radius 50.8 mm"
  },
  {
    "id": "a-071",
    "name": "Village timber wide curved wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Village timber",
    "recipe": "Timber",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 90,
    "matches": [],
    "shape": "curved-wall",
    "hint": "Village timber / 90° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  },
  {
    "id": "a-072",
    "name": "Village timber gentle 45° wall · 2 tile radius",
    "category": "Walls",
    "icon": "",
    "family": "Village timber",
    "recipe": "Timber",
    "radius": 101.6,
    "innerDepth": 101.6,
    "sweep": 45,
    "matches": [],
    "shape": "gentle-curve",
    "hint": "Village timber / 45° curve / inner radius 101.6 mm / spans two or more 50.8 mm tiles"
  }
];
