const icons={
 new:'M12 5v14M5 12h14',open:'M3 7h7l2 3h9l-3 10H3V7Zm0 0V4h7l2 3',save:'M5 3h12l4 4v14H3V3h2Zm2 0v7h10V3M7 21v-7h10v7',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4M12 18h.01',select:'m5 3 14 9-7 1-3 7-4-17Z',rotate:'M5 8a8 8 0 1 1-1 8M5 3v5h5',duplicate:'M8 8h13v13H8V8ZM4 16H2V2h14v2',delete:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',undo:'M9 5 3 11l6 6M3 11h11a6 6 0 0 1 6 6',redo:'m15 5 6 6-6 6M21 11h-11a6 6 0 0 0-6 6',export:'M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6',estimate:'M4 3h16v18H4V3ZM7 7h10M8 12h1m6 0h1m-8 5h1m6 0h1'};
export function setupEditorChrome(){
 const $=id=>document.getElementById(id);
 const help=document.createElement('button');help.id='tutorial-help';document.querySelector('.header-actions').append(help);
 const labels={'tutorial-help':['Guide','Open the getting-started guide · F1'],new:['New scene','Start a new scene'],open:['Open','Open a saved project'],save:['Save','Save your project · Ctrl+S'],export:['Prepare print pack','Export models, quantities and your editable project'], 'estimate-print':['Print estimate','Optional online price estimate'],select:['Select','Select an existing piece, then drag to move it'],rotate:['Rotate','Rotate the selected piece · R'],duplicate:['Duplicate','Duplicate the selected piece · D'],delete:['Delete','Delete the selected piece · Delete'],undo:['Undo','Undo the last edit · Ctrl+Z'],redo:['Redo','Redo the last edit · Ctrl+Shift+Z']};
 for(const [id,[label,title]]of Object.entries(labels)){const b=$(id);b.textContent=label;b.title=title;b.setAttribute('aria-label',title);const key=id==='estimate-print'?'estimate':id==='tutorial-help'?'help':id;const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+icons[key]+'"/></svg>';b.classList.add('icon-button');b.style.setProperty('--tool-icon','url("data:image/svg+xml,'+encodeURIComponent(svg)+'")');}
 $('rotate').dataset.shortcut='R';$('duplicate').dataset.shortcut='D';
 const examples=document.querySelector('.examples');for(const id of ['dungeon-demo','village-demo','demo','openlock-demo'])examples.append($(id));for(const b of examples.querySelectorAll('button'))b.classList.remove('primary');examples.querySelector('summary').textContent='Example scenes';
 const note=$('socket-note'),hint=note.nextElementSibling,intro=document.createElement('p');intro.className='library-intro';intro.textContent='Choose a piece. Click or drag it into your scene.';note.before(intro);const tips=document.createElement('details');tips.className='library-tips';tips.innerHTML='<summary>Placement & snapping tips</summary>';tips.append(note,hint);examples.after(tips);
 const credit=document.querySelector('.openlock-attribution'),detail=document.createElement('details');detail.innerHTML='<summary>Licence & credits</summary>';for(const el of [...credit.children].slice(1))detail.append(el);credit.append(detail);
 document.querySelector('.stage-bottom').setAttribute('aria-label','Scene editing tools');document.querySelector('.view-buttons').setAttribute('aria-label','Camera and inspection tools');
 const titles={perspective:'Perspective camera',top:'Top-down camera',fit:'Frame every piece in the scene',roofs:'Show or hide roofs',clay:'Switch between material and clay previews',front:'Inspect a piece from the front',sockets:'Inspect connector sockets from below'};for(const [id,title]of Object.entries(titles))$(id).title=title;
}
