import encounters from './tutorial-images/encounters.png';
import world from './tutorial-images/world.png';
import overview from './tutorial-images/overview.png';
import place from './tutorial-images/place.png';
import move from './tutorial-images/move.png';
import views from './tutorial-images/views.png';
import printing from './tutorial-images/print.png';
import {showReleaseHighlights} from './release-highlights.js';
// Old dismissal was automatic; only an explicit opt-out suppresses the guide now.
const skipKey='terrain-foundry-tutorial-skip-v2';
const steps=[
 {title:'Welcome to your offline workshop',image:overview,alt:'The desktop editor with a terrain library on the left, a 3D courtyard in the middle and settings on the right.',body:'<p>Build on your PC, save on your PC, and keep creating without an internet connection.</p><ul><li><strong>Left:</strong> browse terrain by category.</li><li><strong>Centre:</strong> arrange your scene in 3D.</li><li><strong>Right:</strong> adjust the selected piece and build settings.</li></ul><p>This guide uses example screenshots. It does not change your current scene.</p>'},
 {title:'Choose a piece and place it',image:place,alt:'A floor selected from the library, with a placement preview over the courtyard.',body:'<p>Choose a category and subcategory, or search for a piece. Use <strong>Expand library</strong> for a larger browsing space. Click its thumbnail, then click the board—or drag it from the library.</p><p>A normal placement returns to <strong>Select</strong>. Hold <kbd>Shift</kbd> while placing to keep adding the same piece.</p><p>Nearby OpenLOCK sockets snap together. Press <kbd>Esc</kbd> to cancel placement.</p>'},
 {title:'Move, rotate and raise pieces',image:move,alt:'A courtyard floor selected, with position, elevation and rotation controls in the inspector.',body:'<p>In <strong>Select</strong> mode, click an existing piece and drag it across the board.</p><p>Hold <kbd>Alt</kbd> while dragging up or down to change elevation. Use the inspector for exact values: position is in squares; elevation is in millimetres.</p><p><kbd>R</kbd> rotates, <kbd>D</kbd> duplicates, and <kbd>Delete</kbd> removes the selected piece. <kbd>Ctrl</kbd> + <kbd>Z</kbd> undoes an edit.</p>'},
 {title:'Find the right view',image:views,alt:'The 3D scene with the camera controls above it and the editing tools below.',body:'<p>Drag empty space to orbit. Right-drag to pan, and scroll to zoom.</p><p>Use <strong>Top view</strong> to line up a layout and <strong>Fit scene</strong> to bring every piece back into view.</p><p><strong>Clay view</strong> shows sculpted detail without colour. <strong>Inspect sockets</strong> looks underneath a piece; return with <strong>3D view</strong>.</p>'},
 {title:'Keep your worlds on your computer',image:encounters,alt:'The local encounters and scenes library with a preview of a complete assembled workshop.',body:'<p>Name your scene at the top, then use <strong>Save</strong> or <kbd>Ctrl</kbd> + <kbd>S</kbd> to choose a local project file.</p><p>Saved nonempty scenes also appear in <strong>Encounters & scenes…</strong> with a preview of the whole build. Click a preview to reopen it, or drag it onto a world. Use <strong>Open</strong> to return to any local project file. Recovery helps protect work in progress, but save named files to keep separate scenes.</p><p>No account or cloud save is required. Internet access is optional for updates and print estimates after installation.</p>'},
 {title:'Combine encounters into a world',image:world,alt:'World builder showing a table grid, a saved workshop encounter and an elevated village level.',body:'<p>Open <strong>World builder…</strong> above the terrain library. Start an empty world or use your current scene, then choose a standard table size or custom dimensions.</p><p><strong>Add saved scene…</strong> puts a local encounter or building into your world library. Click or drag it onto the table. Each placement moves, rotates and rises as a group.</p><p>Use <strong>Levels & table</strong> for caves below a village, and hide upper levels while working underground. <strong>Fit table</strong> shows your whole gaming table.</p><p>Save your world locally, or save an encounter or a complete level as a reusable scene. Hidden levels remain in print exports.</p>'},
 {title:'Prepare a print pack',image:printing,alt:'The Prepare your print pack dialog showing quantities, connector counts and printer-size checks.',body:'<p>Check your printer build volume in the right-hand settings, then choose <strong>Prepare print pack</strong>.</p><p>The export contains STL models, a quantity list, your editable project, and the OpenLOCK clips and fit-test parts when connectors are enabled.</p><p>Open the STLs together in Bambu Studio, apply the listed quantities, arrange, slice and check supports. Print the small connector fit test first.</p><p><strong>Print estimate</strong> is an optional online service. Your scene is not uploaded automatically.</p>'}
];
export function setupTutorial(){
 const dialog=document.createElement('dialog');dialog.id='tutorial-dialog';dialog.setAttribute('aria-labelledby','tutorial-title');dialog.innerHTML='<div class="tutorial-heading"><div><div class="eyebrow">YOUR FIRST WORLD STARTS HERE</div><p class="tutorial-progress" aria-live="polite"></p></div><button id="tutorial-close" title="Close guide" aria-label="Close guide">×</button></div><div class="tutorial-layout"><div class="tutorial-visual"><button id="tutorial-enlarge" aria-label="Enlarge the example screenshot"><img id="tutorial-image" alt=""></button><span>Actual editor screenshots · Click to enlarge</span></div><div class="tutorial-copy"><h2 id="tutorial-title"></h2><div id="tutorial-body"></div></div></div><div class="tutorial-footer"><div class="tutorial-steps" aria-label="Guide steps"></div><div class="tutorial-navigation"><button id="tutorial-back">Back</button><button id="tutorial-next" class="primary">Next →</button></div></div><label class="tutorial-preference"><input id="tutorial-skip" type="checkbox"> Skip this tutorial next time</label><p class="tutorial-local">Always available from Guide or F1. Everything in this guide is included offline.</p>';
 document.body.append(dialog);
 const zoom=document.createElement('dialog');zoom.id='tutorial-zoom';zoom.setAttribute('aria-label','Enlarged tutorial screenshot');zoom.innerHTML='<button id="tutorial-zoom-close" aria-label="Close enlarged screenshot">Close image</button><img alt="">';document.body.append(zoom);
 const find=id=>dialog.querySelector('#'+id);let current=0,returnFocus=null;
 function render(){const step=steps[current];find('tutorial-title').textContent=step.title;find('tutorial-body').innerHTML=step.body;find('tutorial-image').src=step.image;find('tutorial-image').alt=step.alt;dialog.querySelector('.tutorial-progress').textContent='Step '+(current+1)+' of '+steps.length;find('tutorial-back').disabled=current===0;find('tutorial-next').textContent=current===steps.length-1?'Start building':'Next →';for(const [i,b]of [...dialog.querySelectorAll('.tutorial-steps button')].entries()){b.classList.toggle('active',i===current);if(i===current)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');}}
 function open(){if(dialog.open)return;try{find('tutorial-skip').checked=localStorage.getItem(skipKey)==='true';}catch{}returnFocus=document.activeElement;current=0;render();dialog.showModal();find('tutorial-next').focus();}
 function close(){dialog.close();}
 for(const [i,step]of steps.entries()){const b=document.createElement('button');b.textContent=String(i+1);b.title=step.title;b.setAttribute('aria-label','Step '+(i+1)+': '+step.title);b.onclick=()=>{current=i;render();};dialog.querySelector('.tutorial-steps').append(b);}
 find('tutorial-next').onclick=()=>{if(current===steps.length-1)close();else{current++;render();}};find('tutorial-back').onclick=()=>{if(current){current--;render();}};find('tutorial-close').onclick=close;
 dialog.addEventListener('close',()=>{if(zoom.open)zoom.close();if(returnFocus?.isConnected)returnFocus.focus();});
 find('tutorial-enlarge').onclick=()=>{const image=zoom.querySelector('img');image.src=steps[current].image;image.alt=steps[current].alt;zoom.showModal();};zoom.querySelector('button').onclick=()=>zoom.close();
 find('tutorial-skip').addEventListener('change',()=>{try{localStorage.setItem(skipKey,String(find('tutorial-skip').checked));}catch{}});
 document.getElementById('tutorial-help').onclick=open;
 document.addEventListener('keydown',e=>{if(e.key==='F1'){e.preventDefault();if(!document.querySelector('dialog[open]'))open();}if(!dialog.open||zoom.open)return;if(e.key==='ArrowRight'){e.preventDefault();if(current<steps.length-1){current++;render();}}if(e.key==='ArrowLeft'){e.preventDefault();if(current){current--;render();}}});
 if(!new URLSearchParams(location.search).has('demo'))showReleaseHighlights(()=>{let skip=false;try{skip=localStorage.getItem(skipKey)==='true';}catch{}if(!skip)open();});
}
