import {TABLES,toWorld,addEncounter,extractEncounter,extractLevel,activeLevel,selectionItems,transformSelection,tableSize} from './world.js';
import {defaults,validateProject} from './model.js';
export function setupWorldUI({getProject,getSelected,change,replace,armEncounter,saveCopy,toast,fitTable}){
 const $=id=>document.getElementById(id),button=(label,action)=>{const b=document.createElement('button');b.textContent=label;b.onclick=action;return b;};
 const panel=document.createElement('section');panel.className='world-panel';panel.innerHTML=`<div class="world-mode"><span id="project-kind">ENCOUNTER / SCENE</span><button id="world-settings">World builder…</button></div><div id="world-controls" hidden><label>Active level<select id="world-level"></select></label><div class="world-tools"><button id="world-fit">Fit table</button><button id="world-levels">Levels & table</button></div><h3>Saved encounters</h3><p>Click or drag an encounter onto your table. Each placement moves as a group.</p><button id="world-import" class="full">Add saved scene…</button><div id="world-encounters"></div><input id="world-scene-file" type="file" accept=".terrain" hidden></div>`;
 document.querySelector('.workspace>aside').prepend(panel);const saveLevel=button('Save this level as a scene…',async()=>{try{await saveCopy(extractLevel(getProject()));}catch(e){toast(e.message,true);}});saveLevel.className='full';$('world-controls').append(saveLevel);
 const dialog=document.createElement('dialog');dialog.id='world-dialog';dialog.innerHTML=`<div class="eyebrow">YOUR ENTIRE GAMING TABLE</div><div class="world-dialog-title"><h2>World builder</h2><button id="world-close">Done</button></div><p>Save encounters and buildings as scenes, then combine them into a world. World files include their encounter library and imported geometry, all on your computer.</p><div id="world-start"><button id="world-convert" class="primary">Build a world from this scene</button><button id="world-new">New empty world</button></div><div id="world-edit" hidden><h3>Table dimensions</h3><label>Preset<select id="world-preset"></select></label><div class="world-fields"><label>Width · mm<input id="world-width" type="number" min="203.2" max="10000" step="0.1"></label><label>Depth · mm<input id="world-depth" type="number" min="203.2" max="10000" step="0.1"></label><button id="world-size-apply">Apply size</button></div><p id="world-size-note"></p><h3>Levels</h3><p>Use a lower level for caves and an upper level for a village. Elevation is in millimetres; changing a level elevation moves its pieces together. Visibility affects the preview; exports include every level.</p><div id="world-level-list"></div><button id="world-add-level">Add level</button></div>`;document.body.append(dialog);
 const group=document.createElement('section');group.id='world-group';group.className='section';group.hidden=true;group.innerHTML=`<h3 id="world-group-name"></h3><p id="world-group-count"></p><label>Move to level<select id="world-group-level"></select></label><div class="world-tools"><button id="world-save-encounter">Save encounter…</button><button id="world-ungroup">Edit pieces separately</button></div>`;document.querySelector('.right').prepend(group);
 let dialogRevision='';
 const run=fn=>()=>{try{fn();}catch(e){toast(e.message,true);}};
 const mutate=fn=>change(fn);
 function levelOptions(target,current){target.replaceChildren(...getProject().world.levels.map(l=>{const o=document.createElement('option');o.value=l.id;o.textContent=l.name+' · '+l.elevation+' mm'+(l.visible?'':' · hidden');return o;}));target.value=current;}
 function sync(){const p=getProject(),world=p.kind==='world';$('project-kind').textContent=world?'WORLD / TABLE':'ENCOUNTER / SCENE';$('world-controls').hidden=!world;$('world-start').hidden=world;$('world-edit').hidden=!world;group.hidden=true;
  if(!world)return;
  levelOptions($('world-level'),p.world.activeLevel);
  $('world-encounters').replaceChildren(...p.world.encounters.map(e=>{const b=button(e.scene.name,()=>armEncounter(e.id));b.className='encounter-card';b.draggable=true;b.dataset.encounter=e.id;const small=document.createElement('small');small.textContent=e.scene.items.length+' pieces · reusable scene';b.append(small);b.ondragstart=ev=>{armEncounter(e.id);ev.dataTransfer.setData('application/x-terrain-encounter',e.id);};return b;}));
  const item=getSelected(),instance=p.world.instances.find(g=>g.id===item?.encounterId);if(item){group.hidden=false;$('world-group-name').textContent=instance?.name||'World scenery';$('world-group-count').textContent=selectionItems(p,item).length+' pieces · drag, rotate and elevate together';levelOptions($('world-group-level'),item.levelId);$('world-ungroup').hidden=!instance;}
  const signature=JSON.stringify([p.world.widthMm,p.world.depthMm,p.world.levels]);if(dialog.open&&signature!==dialogRevision){dialogRevision=signature;if(!document.activeElement?.closest('#world-level-list'))renderSettings();}
 }
 function renderSettings(){const p=getProject();if(p.kind!=='world')return;$('world-width').value=p.world.widthMm;$('world-depth').value=p.world.depthMm;$('world-preset').value=String(TABLES.findIndex(t=>t[1]===p.world.widthMm&&t[2]===p.world.depthMm));const [w,d]=tableSize(p);$('world-size-note').textContent=`${(w/p.grid).toFixed(1)} × ${(d/p.grid).toFixed(1)} grid squares · ${(w/1000).toFixed(2)} × ${(d/1000).toFixed(2)} metres`;
  $('world-level-list').replaceChildren(...p.world.levels.map(l=>{const row=document.createElement('div');row.className='world-level-row';const name=document.createElement('input');name.value=l.name;name.maxLength=80;name.setAttribute('aria-label','Level name');name.onchange=run(()=>mutate(()=>l.name=name.value.trim()||'Level'));const elevation=document.createElement('input');elevation.type='number';elevation.value=l.elevation;elevation.min=0;elevation.max=9000;elevation.setAttribute('aria-label',l.name+' elevation in mm');elevation.onchange=run(()=>{const n=Number(elevation.value),delta=n-l.elevation;if(!Number.isFinite(n)||n<0||n>9000||p.items.some(i=>i.levelId===l.id&&(i.y+delta<0||i.y+delta>10000)))throw Error('Level elevation would move pieces outside the allowed height.');mutate(()=>{p.items.filter(i=>i.levelId===l.id).forEach(i=>i.y+=delta);l.elevation=n;if(p.world.activeLevel===l.id)$('place-height').value=Math.max(0,Math.min(10000,(Number($('place-height').value)||0)+delta));});});const visibility=button(l.visible?'Hide':'Show',run(()=>{mutate(()=>l.visible=!l.visible);visibility.textContent=l.visible?'Hide':'Show';}));row.append(name,elevation,visibility);return row;}));
 }
 function open(){dialogRevision='';sync();dialog.showModal();renderSettings();}
 $('world-settings').onclick=open;$('world-levels').onclick=open;$('world-close').onclick=()=>dialog.close();$('world-fit').onclick=fitTable;
 $('world-convert').onclick=run(()=>{const old=getProject(),p=toWorld(old);if(old.items.length){addEncounter(p,old);const instance={id:crypto.randomUUID(),name:old.name};p.world.instances.push(instance);p.items.forEach(i=>i.encounterId=instance.id);}replace(validateProject(p));sync();renderSettings();});
 $('world-new').onclick=()=>{if(getProject().items.length&&!confirm('Start an empty world? Save your current scene first if you want to keep it.'))return;const p=toWorld(defaults());p.name='Untitled world';replace(p);sync();renderSettings();};
 $('world-preset').replaceChildren(...[...TABLES.map((t,i)=>[String(i),t[0]]),['-1','Custom size']].map(([v,label])=>{const o=document.createElement('option');o.value=v;o.textContent=label;return o;}));
 $('world-preset').onchange=()=>{const t=TABLES[Number($('world-preset').value)];if(t){$('world-width').value=t[1];$('world-depth').value=t[2];}};
 $('world-size-apply').onclick=run(()=>{const width=Number($('world-width').value),depth=Number($('world-depth').value);if(![width,depth].every(n=>Number.isFinite(n)&&n>=203.2&&n<=10000))throw Error('Enter dimensions from 203.2 to 10,000 mm.');mutate(()=>{getProject().world.widthMm=width;getProject().world.depthMm=depth;});fitTable();});
 $('world-add-level').onclick=run(()=>{const p=getProject();if(p.world.levels.length>=32)throw Error('A world supports up to 32 levels.');const l={id:crypto.randomUUID(),name:'Level '+(p.world.levels.length+1),elevation:Math.min(9000,Math.max(...p.world.levels.map(l=>l.elevation))+50.8),visible:true};mutate(()=>{p.world.levels.push(l);p.world.activeLevel=l.id;});$('place-height').value=l.elevation;});
 $('world-level').onchange=run(()=>mutate(()=>{getProject().world.activeLevel=$('world-level').value;$('place-height').value=activeLevel(getProject()).elevation;}));
 $('world-import').onclick=async()=>{try{if(window.desktop){const data=await window.desktop.open();if(data)mutate(()=>addEncounter(getProject(),JSON.parse(data)));}else $('world-scene-file').click();}catch(e){toast('Could not add encounter: '+e.message,true);}};
 $('world-scene-file').onchange=async()=>{try{const f=$('world-scene-file').files[0];if(f){if(f.size>100000000)throw Error('Project exceeds 100 MB.');const text=await f.text();mutate(()=>addEncounter(getProject(),JSON.parse(text)));}}catch(e){toast(e.message,true);}finally{$('world-scene-file').value='';}};
 $('world-save-encounter').onclick=async()=>{try{await saveCopy(extractEncounter(getProject(),getSelected()));}catch(e){toast(e.message,true);}};
 $('world-ungroup').onclick=run(()=>mutate(()=>{const p=getProject(),item=getSelected(),id=item.encounterId;selectionItems(p,item).forEach(i=>delete i.encounterId);p.world.instances=p.world.instances.filter(g=>g.id!==id);}));
 $('world-group-level').onchange=run(()=>{const p=getProject(),item=getSelected(),old=p.world.levels.find(l=>l.id===item.levelId),next=p.world.levels.find(l=>l.id===$('world-group-level').value);mutate(()=>{transformSelection(p,item,{...item,y:item.y+next.elevation-old.elevation});selectionItems(p,item).forEach(i=>i.levelId=next.id);});});
 sync();return {sync};
}
