const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');const {atomicWrite}=require('./project-store.cjs');
const fingerprint=c=>{const {chat,revisions,revision,assistant,...rest}=c;return crypto.createHash('sha256').update(JSON.stringify(rest)).digest('hex');};
function createCampaignAgent({store,ai,actions,files,style}){let queue=Promise.resolve();
 async function paths(id){await store.load(id);const dir=path.join(await store.folder(id),'.agent');await fs.mkdir(dir,{recursive:true});if((await fs.lstat(dir)).isSymbolicLink())throw Error('Agent history must stay inside the workspace');return {dir,log:path.join(dir,'activity.json')};}
 async function history(id){const p=await paths(id);try{if((await fs.lstat(p.log)).isSymbolicLink()||(await fs.stat(p.log)).size>1000000)throw Error('Invalid agent log');return JSON.parse(await fs.readFile(p.log,'utf8'));}catch(e){if(e.code==='ENOENT')return [];throw e;}}
 async function execute(id,values){if(!(await ai.status()).agentMode)throw Error('Enable Agent mode in AI settings first');if(!Array.isArray(values)||values.length>6)throw Error('At most six workspace actions per batch');const results=[];for(const action of values){try{if(!(await ai.status()).agentMode)throw Error('Agent mode was disabled');if(['chooseProjectFile','openLinkedProject','proposeEncounter'].includes(action.type)){results.push({type:action.type,deferred:true});continue;}if(['findAssets','findSavedScenes','listWorkspaceFiles','readWorkspaceFile'].includes(action.type)){results.push(await actions.lookup(action,id));continue;}const before=await store.load(id),review=await actions.review(id,action),p=await paths(id),snapshot=crypto.randomUUID()+'.json';await atomicWrite(path.join(p.dir,snapshot),JSON.stringify(before));let result;try{result=await actions.apply(id,review.token);}catch(e){await fs.unlink(path.join(p.dir,snapshot)).catch(()=>{});throw e;}const log=await history(id);log.push({id:crypto.randomUUID(),at:new Date().toISOString(),action:review.action.type,path:action.path||null,link:action.id||null,revision:result.campaign?.revision||before.revision,snapshot,fingerprint:fingerprint(result.campaign||before),sharedStyleUndo:result.sharedStyleUndo,sharedStyleContent:result.sharedStyleContent,documentUndo:result.documentUndo||null,documentHash:action.type==='writeWorkspaceFile'?crypto.createHash('sha256').update(action.content).digest('hex'):null});while(log.length>10){const old=log.shift();if(/^[a-f0-9-]+\.json$/.test(old.snapshot))await fs.unlink(path.join(p.dir,old.snapshot)).catch(()=>{});}await atomicWrite(p.log,JSON.stringify(log));results.push({...result,action:review.action.type,applied:true});}catch(error){return {campaign:await store.load(id),results,error:error.message};}}return {campaign:await store.load(id),results};}
 function apply(id,values){const task=queue.then(()=>execute(id,values));queue=task.catch(()=>{});return task;}
 async function executeUndo(id){const log=await history(id),entry=log[log.length-1];if(!entry)throw Error('No agent action to undo');const current=await store.load(id);if(fingerprint(current)!==entry.fingerprint)throw Error('Campaign changed since the last agent action. Use the specific content or terrain history instead.');const p=await paths(id);if(!/^[a-f0-9-]+\.json$/.test(entry.snapshot))throw Error('Invalid undo snapshot');const file=path.join(p.dir,entry.snapshot);if((await fs.lstat(file)).isSymbolicLink()||(await fs.stat(file)).size>15000000)throw Error('Invalid undo snapshot');const previous=JSON.parse(await fs.readFile(file,'utf8'));if(entry.sharedStyleUndo!==undefined){if(await style.read()!==entry.sharedStyleContent)throw Error('Shared style changed after the agent action; keep its newer edits');await style.write(entry.sharedStyleUndo);}if(entry.documentUndo){const document=await files.read(id,entry.documentUndo.path);if(crypto.createHash('sha256').update(document.content).digest('hex')!==entry.documentHash)throw Error('Document changed after the agent action; keep its newer edits');await files.restore(id,entry.documentUndo);}let latest=current;if(['editLinkedProject','addWorldPieces'].includes(entry.action))latest=await store.undoProjectRevision(id,entry.link,current.revision);previous.revision=latest.revision;previous.chat=current.chat;const restored=await store.save(previous);log.pop();if(log.length)log[log.length-1].revision=restored.revision;await atomicWrite(p.log,JSON.stringify(log));await fs.unlink(file);return restored;}
 function undo(id){const task=queue.then(()=>executeUndo(id));queue=task.catch(()=>{});return task;}
 return {apply,undo,history:async id=>(await history(id)).map(({snapshot,documentUndo,sharedStyleUndo,sharedStyleContent,...entry})=>entry)};
}module.exports={createCampaignAgent};
