const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');const {atomicWrite}=require('./project-store.cjs');
function createCampaignStore(directory){let queue=Promise.resolve();const serial=fn=>{const task=queue.then(fn);queue=task.catch(()=>{});return task;};const file=id=>{if(typeof id!=='string'||!/^[a-f0-9-]{16,40}$/.test(id))throw Error('Invalid campaign identity');return path.join(directory,id+'.campaign.json');};const schema=()=>import('./campaign-schema.mjs');
 async function load(id){const p=file(id);if((await fs.stat(p)).size>15000000)throw Error('Campaign exceeds limit');return (await schema()).validateCampaign(JSON.parse(await fs.readFile(p,'utf8')));}
 async function save(value){return serial(async()=>{const c=(await schema()).validateCampaign(value);await fs.mkdir(directory,{recursive:true});let previous;try{previous=await load(c.id);}catch(e){if(e.code!=='ENOENT')throw e;}if(previous&&c.revision!==previous.revision)throw Error('Campaign changed elsewhere. Reopen before saving.');if(!previous&&c.revision!==0)throw Error('Unknown campaign revision');c.revision++;c.revisions=[...(previous?.revisions||[]),{revision:c.revision,at:new Date().toISOString(),summary:previous?'Campaign saved':'Campaign created',notes:c.notes}].slice(-50);const serialized=JSON.stringify(c);if(Buffer.byteLength(serialized,'utf8')>15000000)throw Error('Campaign history exceeds the 15 MB storage limit');await atomicWrite(file(c.id),serialized);return c;});}
 async function list(){await fs.mkdir(directory,{recursive:true});const entries=await fs.readdir(directory);const result=[];for(const f of entries.filter(f=>/^[a-f0-9-]{16,40}\.campaign\.json$/.test(f)).slice(0,1000)){const c=await load(f.split('.')[0]);result.push({id:c.id,name:c.name,revision:c.revision,modified:(await fs.stat(file(c.id))).mtimeMs});}return result.sort((a,b)=>b.modified-a.modified);}
 async function addProject(id,text,expectedRevision){if(typeof text!=='string'||text.length>100000000)throw Error('Project exceeds limit');require('./project-store.cjs').check(text);const p=JSON.parse(text),c=await load(id);if(expectedRevision!==undefined&&c.revision!==expectedRevision)throw Error('Campaign changed since review');const link={id:crypto.randomUUID(),name:p.name,kind:p.kind==='world'?'world':'scene',visible:false};const folder=path.join(directory,id,'projects');await fs.mkdir(folder,{recursive:true});await atomicWrite(path.join(folder,link.id+'.terrain'),JSON.stringify(p));c.links.push(link);return save(c);}
 async function project(id,linkId){const c=await load(id);if(!c.links.some(x=>x.id===linkId))throw Error('Campaign link unavailable');const p=path.join(directory,id,'projects',linkId+'.terrain');if((await fs.stat(p)).size>100000000)throw Error('Project exceeds limit');return JSON.parse(await fs.readFile(p,'utf8'));}
 return {load,save,list,addProject,project,flush:()=>queue,directory};
}
module.exports={createCampaignStore};
