const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');const {atomicWrite}=require('./project-store.cjs');
function documentPath(value){if(typeof value!=='string'||value.length>180||! /^(content|playbook|notes)\/[a-zA-Z0-9_/-]+\.md$/.test(value)||value.split('/').some(x=>x==='..'||x==='.'||!x))throw Error('Use a Markdown file under content/, playbook/ or notes/');return value;}
function createCampaignFiles(store){
 async function target(id,relative){documentPath(relative);await store.load(id);const root=await fs.realpath(await store.folder(id));let current=root;for(const part of relative.split('/')){current=path.join(current,part);try{const stat=await fs.lstat(current);if(stat.isSymbolicLink())throw Error('Workspace links are not allowed for agent files');const real=await fs.realpath(current);if(!real.startsWith(root+path.sep))throw Error('File is outside the campaign workspace');}catch(e){if(e.code!=='ENOENT')throw e;}}return current;}
 async function list(id){const entries=[];let scanned=0;for(const base of ['content','playbook','notes']){const dir=path.join(await store.folder(id),base);async function walk(folder,prefix){let values;try{if(++scanned>500)return;if((await fs.lstat(folder)).isSymbolicLink())return;values=await fs.readdir(folder,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return;throw e;}for(const item of values){if(entries.length>=200)return;const relative=prefix+'/'+item.name;if(item.isSymbolicLink())continue;if(item.isDirectory())await walk(path.join(folder,item.name),relative);else if(item.name.endsWith('.md')){try{const file=await target(id,relative),stat=await fs.stat(file);entries.push({path:relative,bytes:stat.size});}catch{}}}}await walk(dir,base);}return entries;}
 async function read(id,relative){const file=await target(id,relative);if((await fs.stat(file)).size>100000)throw Error('Document exceeds 100 KB');return {path:relative,content:await fs.readFile(file,'utf8')};}
 async function write(id,relative,content){if(typeof content!=='string'||Buffer.byteLength(content)>100000)throw Error('Document exceeds 100 KB');const file=await target(id,relative);let previous=null;try{previous=(await read(id,relative)).content;}catch(e){if(e.code!=='ENOENT')throw e;}if(previous!==null){const history=path.join(await store.folder(id),'.document-history');await fs.mkdir(history,{recursive:true});if((await fs.lstat(history)).isSymbolicLink())throw Error('Document history must stay in the workspace');const hash=crypto.createHash('sha256').update(previous).digest('hex');const backup=path.join(history,hash+'.md');try{await fs.writeFile(backup,previous,{flag:'wx'});}catch(e){if(e.code!=='EEXIST')throw e;}}await fs.mkdir(path.dirname(file),{recursive:true});await target(id,relative);await atomicWrite(file,content);return {path:relative,previous};}
 async function restore(id,record){if(record.previous===null){const file=await target(id,record.path);await fs.unlink(file).catch(e=>{if(e.code!=='ENOENT')throw e;});}else await write(id,record.path,record.previous);}
 return {list,read,write,restore};
}module.exports={createCampaignFiles,documentPath};
