const ID=/^[a-f0-9-]{16,40}$/;
const text=(v,max=20000)=>{if(typeof v!=='string'||v.length>max)throw Error('Campaign text exceeds its limit');return v;};
const id=v=>{if(!ID.test(v))throw Error('Invalid campaign identity');return v;};
const list=(v,max=1000)=>{if(!Array.isArray(v)||v.length>max)throw Error('Invalid campaign collection');return v;};
const visibility=v=>{if(typeof v!=='boolean')throw Error('Choose DM-only or player-visible');return v;};
const image=v=>{if(v===null||v==='')return null;if(typeof v!=='string'||v.length>6000000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v))throw Error('Use a local PNG, JPEG or WebP image');return v;};
export function createCampaign(name,setup={}){return {schema:1,kind:'campaign',id:crypto.randomUUID(),revision:0,name,setup:{genre:setup.genre||'Fantasy',theme:setup.theme||'',party:setup.party||'',missions:setup.missions||'',length:setup.length||'',rules:setup.rules||'',boundaries:setup.boundaries||''},summary:'',progress:'',categories:['Characters','Locations','Missions','Events','Lore'],items:[],relationships:[],timeline:[],notes:[],pins:[],maps:[],links:[],chat:[],characters:[],initiative:[],widgets:[],sounds:[],revisions:[],cover:null};}
export function validateCampaign(v){if(!v||v.schema!==1||v.kind!=='campaign'||!Number.isSafeInteger(v.revision)||v.revision<0)throw Error('Unsupported campaign');const c={schema:1,kind:'campaign',id:id(v.id),revision:v.revision,name:text(v.name,120),summary:text(v.summary||'',20000),progress:text(v.progress||'',10000),setup:Object.fromEntries(['genre','theme','party','missions','length','rules','boundaries'].map(k=>[k,text(v.setup?.[k]||'',2000)])),categories:list(v.categories,100).map(x=>text(x,80))};if(!c.name.trim())throw Error('Give the campaign a name');
 c.items=list(v.items).map(x=>({id:id(x.id),category:text(x.category,80),title:text(x.title,160),body:text(x.body),visible:visibility(x.visible)}));const items=new Map(c.items.map(x=>[x.id,x]));if(items.size!==c.items.length)throw Error('Duplicate campaign item');
 c.relationships=list(v.relationships).map(x=>{if(!items.has(x.from)||!items.has(x.to))throw Error('Relationship item missing');return {id:id(x.id),from:x.from,to:x.to,label:text(x.label,160),body:text(x.body||''),visible:visibility(x.visible)};});
 c.timeline=list(v.timeline).map(x=>({id:id(x.id),itemId:x.itemId===null?null:id(x.itemId),date:text(x.date,80),title:text(x.title,160),body:text(x.body),visible:visibility(x.visible)}));
 c.notes=list(v.notes).map(x=>({id:id(x.id),title:text(x.title,160),body:text(x.body),visible:visibility(x.visible),itemId:x.itemId===null?null:id(x.itemId)}));
 c.maps=list(v.maps,30).map(x=>({id:id(x.id),title:text(x.title,160),image:image(x.image),visible:visibility(x.visible)}));const maps=new Set(c.maps.map(x=>x.id));
 c.pins=list(v.pins).map(x=>{if(!maps.has(x.mapId)||![x.x,x.y].every(n=>Number.isFinite(n)&&n>=0&&n<=1))throw Error('Invalid map pin');return {id:id(x.id),mapId:x.mapId,itemId:x.itemId===null?null:id(x.itemId),x:x.x,y:x.y,title:text(x.title,160),body:text(x.body),visible:visibility(x.visible)};});
 c.characters=list(v.characters,100).map(x=>({id:id(x.id),name:text(x.name,160),details:text(x.details),abilities:text(x.abilities||''),equipment:text(x.equipment||''),spells:text(x.spells||''),portrait:image(x.portrait||null),hp:bounded(x.hp,0,100000),ac:bounded(x.ac,0,1000),visible:visibility(x.visible)}));
 c.links=list(v.links,100).map(x=>({id:id(x.id),name:text(x.name,120),kind:['world','scene'].includes(x.kind)?x.kind:'scene',visible:visibility(x.visible)}));
 c.chat=list(v.chat,500).map(x=>({role:['user','assistant'].includes(x.role)?x.role:'user',text:text(x.text,30000),at:text(x.at,80)}));
 c.diceLog=list(v.diceLog||[],100).map(x=>({at:text(x.at,80),notation:text(x.notation,40),result:text(x.result,2000)}));c.turn=bounded(v.turn||0,0,100);c.round=bounded(v.round||1,1,100000);
 c.initiative=list(v.initiative,100).map(x=>({id:id(x.id),name:text(x.name,160),score:bounded(x.score,-100,100),hp:bounded(x.hp,0,100000)}));
 c.widgets=list(v.widgets,50).map(x=>({id:id(x.id),title:text(x.title,160),body:text(x.body)}));
 c.sounds=list(v.sounds,12).map(x=>({id:id(x.id),name:text(x.name,160),slot:bounded(x.slot,1,12),loop:!!x.loop,volume:bounded(x.volume,0,1),license:text(x.license,2000)}));
 const entries=new Set([...c.items,...c.links].map(x=>x.id));const soundIds=new Set(c.sounds.map(x=>x.id));c.cues=list(v.cues||[],1000).map(x=>{if(!entries.has(x.entryId)||!soundIds.has(x.soundId))throw Error('Audio cue entry or sound is missing');return {id:id(x.id),entryId:x.entryId,soundId:x.soundId};});
 c.revisions=list(v.revisions,50).map(x=>({revision:bounded(x.revision,0,100000000),at:text(x.at,80),summary:text(x.summary,500),notes:list(x.notes||[]).map(n=>({id:id(n.id),title:text(n.title,160),body:text(n.body),visible:visibility(n.visible),itemId:n.itemId===null?null:id(n.itemId)}))}));c.cover=image(v.cover);
 for(const x of [...c.notes,...c.timeline,...c.pins])if(x.itemId&&!items.has(x.itemId))throw Error('Linked campaign item missing');
 for(const key of ['items','relationships','timeline','notes','pins','maps','links','characters','initiative','widgets','sounds'])if(new Set(c[key].map(x=>x.id)).size!==c[key].length)throw Error('Duplicate '+key+' identity');if(c.sounds.some(x=>!Number.isInteger(x.slot))||new Set(c.sounds.map(x=>x.slot)).size!==c.sounds.length)throw Error('Sound slots must be unique integers');
 if(JSON.stringify(c).length>15000000)throw Error('Campaign exceeds 15 MB');return c;
}
function bounded(v,min,max){if(!Number.isFinite(v)||v<min||v>max)throw Error('Campaign number outside limits');return v;}
export function playerCampaign(v){const c=validateCampaign(v),items=new Set(c.items.filter(x=>x.visible).map(x=>x.id)),maps=new Set(c.maps.filter(x=>x.visible).map(x=>x.id)),shown=x=>x.visible&&(!x.itemId||items.has(x.itemId));return {schema:1,kind:'campaign-player-handout',sourceCampaignId:c.id,sourceRevision:c.revision,name:c.name,items:c.items.filter(x=>x.visible),relationships:c.relationships.filter(x=>x.visible&&items.has(x.from)&&items.has(x.to)),notes:c.notes.filter(shown),timeline:c.timeline.filter(shown),maps:c.maps.filter(x=>maps.has(x.id)),pins:c.pins.filter(x=>shown(x)&&maps.has(x.mapId)),characters:c.characters.filter(x=>x.visible),cover:c.cover};}
export function reviewedLayout(value,available){if(!value||!Array.isArray(value.items)||!value.items.length||value.items.length>100)throw Error('A proposal needs 1–100 pieces');const ids=new Set(available);const seen=new Set();const items=value.items.map((x,i)=>{if(!ids.has(x.type))throw Error('Proposal uses an unavailable asset: '+String(x.type).slice(0,80));if(![x.x,x.z,x.y,x.rotation].every(Number.isFinite)||Math.abs(x.x)>12||Math.abs(x.z)>12||x.y<0||x.y>254||![0,90,180,270].includes(x.rotation))throw Error('Proposal exceeds the 24-square encounter or uses unsupported rotation');const key=[x.type,x.x,x.z,x.y,x.rotation].join(':');if(seen.has(key))throw Error('Duplicate proposed piece');seen.add(key);return {id:crypto.randomUUID(),type:x.type,x:x.x,z:x.z,y:x.y,rotation:x.rotation,color:'#ffffff'};});return {name:text(value.name||'Suggested encounter',120),items};}
