const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
function setupCampaignNative({app,win,ipcMain,dialog,BrowserWindow,safeStorage,net,sceneLibrary,premiumInventory=async()=>({assets:[]})}){
 const store=require('./campaign-store.cjs').createCampaignStore(process.env.TERRAIN_CAMPAIGN_DIR||path.join(app.getPath('documents'),'Terrain Foundry','Campaigns'));const catalogFile=path.join(__dirname,'asset-catalog.json');
 async function inventory(){const catalog=JSON.parse(await fs.readFile(catalogFile,'utf8')),available=new Set();let folders={};if(process.env.TERRAIN_ASSET_PACKS)folders=JSON.parse(process.env.TERRAIN_ASSET_PACKS);else{try{folders=Object.fromEntries((await fs.readdir(path.join(__dirname,'../release/asset-packs'),{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>[x.name,path.join(__dirname,'../release/asset-packs',x.name)]));}catch(e){if(e.code!=='ENOENT')throw e;}}for(const folder of Object.values(folders)){try{for(const id of Object.keys(JSON.parse(await fs.readFile(path.join(folder,'index.json'),'utf8'))))available.add(id);}catch(e){if(e.code!=='ENOENT')throw e;}}return Object.entries(catalog.assets).filter(([id])=>available.has(id)).map(([id,a])=>({id,name:a.name,category:a.category,widthMm:a.connection?.width,depthMm:a.connection?.depth,heightMm:a.connection?.height,footprints:a.connection?.footprints,connector:a.connection?.templateSource||'none',portCount:a.connection?.ports?.length||0})).concat((await premiumInventory()).assets.map(a=>({id:a.id,name:a.name,category:a.category,widthMm:a.openlock?.width||a.dimensionsMm?.width,depthMm:a.openlock?.depth||a.dimensionsMm?.depth,heightMm:a.openlock?.height||a.dimensionsMm?.height,footprints:a.openlock?.footprints,connector:a.openlock?.kind||'none',portCount:a.openlock?.ports?.length||0})));}
 async function savedScenes(){if(!sceneLibrary)return [];const entries=[];for(let page=0;page<84;page++){const batch=await sceneLibrary.list({page,metadataOnly:true});entries.push(...batch.entries.map(({id,name,pieces})=>({id,name,pieces})));if(page+1>=batch.pages)break;}return entries;}
 async function chooseProject(){const r=await dialog.showOpenDialog(win,{filters:[{name:'Terrain project',extensions:['terrain']}],properties:['openFile']});if(r.canceled)return null;if((await fs.stat(r.filePaths[0])).size>100000000)throw Error('Project exceeds limit');return fs.readFile(r.filePaths[0],'utf8');}
 const ai=require('./campaign-ai.cjs').createCampaignAI({directory:path.join(app.getPath('userData'),'private'),safeStorage,fetchImpl:(...args)=>net.fetch(...args),inventory,savedScenes,linkedContext:async c=>Promise.all(c.links.map(async link=>{try{const p=await store.project(c.id,link.id);return require('./campaign-terrain-context.cjs').terrainContext(p,link,await inventory());}catch{return {id:link.id,name:link.name,missing:true};}}))});
 const actions=require('./campaign-action-service.cjs').createCampaignActions({store,inventory,savedScenes,sceneLibrary,chooseProject});
 const voice=require('./campaign-voice.cjs').createCampaignVoice({store,ai,actions,inventory,fetchImpl:(...args)=>net.fetch(...args),emit:v=>{if(!win.isDestroyed())win.webContents.send('campaign-dictation-event',v);},context:async c=>Promise.all(c.links.map(async link=>{try{return require('./campaign-terrain-context.cjs').terrainContext(await store.project(c.id,link.id),link,await inventory());}catch{return {id:link.id,name:link.name,missing:true};}}))});
 win.on('closed',()=>{voice.stop();voice.stopDictation();});
 let keyDialogOpen=false;
 const handle=(name,fn)=>ipcMain.handle(name,async(event,...args)=>{if(event.sender!==win.webContents)throw Error('Unapproved campaign window');return fn(...args);});
 handle('campaign-list',()=>store.list());handle('campaign-load',id=>store.load(id));handle('campaign-save',c=>store.save(c));handle('campaign-inventory',inventory);handle('campaign-ai-status',()=>ai.status());handle('campaign-ai-configure',v=>ai.configure(v));handle('campaign-ai-forget',p=>ai.forget(p));
 handle('campaign-workspace-export',async id=>{const r=await dialog.showOpenDialog(win,{title:'Choose an empty portable campaign export folder',properties:['openDirectory','createDirectory']});return r.canceled?null:store.exportPortable(id,r.filePaths[0]);});
 handle('campaign-workspace-open',async()=>{const r=await dialog.showOpenDialog(win,{filters:[{name:'Campaign workspace',extensions:['tfcampaign']}],properties:['openFile']});return r.canceled?null:store.openWorkspace(r.filePaths[0]);});
 handle('campaign-workspace-folder',async id=>{await store.load(id);await require('electron').shell.openPath(await store.folder(id));return true;});
 handle('campaign-workspace-move',async id=>{const r=await dialog.showOpenDialog(win,{title:'Choose an empty campaign workspace folder',properties:['openDirectory','createDirectory']});return r.canceled?null:store.moveWorkspace(id,r.filePaths[0]);});
 handle('campaign-terrain-undo',(id,link,revision)=>store.undoProjectRevision(id,link,revision));
 handle('campaign-reference-status',(id,link)=>store.referenceStatus(id,link));
 handle('campaign-reference-refresh',async(id,link,revision,locate)=>{let file;if(locate){const r=await dialog.showOpenDialog(win,{filters:[{name:'Terrain project',extensions:['terrain']}],properties:['openFile']});if(r.canceled)return null;file=r.filePaths[0];}return store.refreshReference(id,link,file,revision);});
 handle('campaign-voice-start',async(id,sdp,mode,editor)=>{const answer=await dialog.showMessageBox(win,{type:'question',buttons:['Cancel','Start online voice'],defaultId:0,cancelId:0,title:'OpenAI voice · API billed',message:'Start '+(mode==='dictate'?'online dictation':'a private DM voice conversation')+'?',detail:'Your microphone audio and campaign context are sent to OpenAI using your API account. Maximum 10 minutes. No raw recordings are saved. DM secrets may be spoken aloud; use headphones. Voice costs are separate from text usage and are not estimated here.'});return answer.response===1?voice.start(id,sdp,mode,editor):null;});
 handle('campaign-voice-stop',()=>voice.stop());handle('campaign-voice-tool',(id,name,args,editor)=>voice.tool(id,name,args,editor));
 handle('campaign-dictation-start',()=>voice.dictate());handle('campaign-dictation-stop',()=>voice.stopDictation());
 handle('campaign-ai-cancel',()=>ai.cancel());handle('campaign-ai-review',(id,a)=>actions.review(id,a));handle('campaign-ai-apply',(id,token)=>actions.apply(id,token));
 handle('campaign-ai-test',async()=>{const answer=await dialog.showMessageBox(win,{type:'question',buttons:['Cancel','Test my API key'],defaultId:0,cancelId:0,title:'Test API access',message:'Send one small test request to your selected provider?',detail:'This sends no campaign content. Your API provider may charge a small amount. The test is recorded in local usage; it does not reveal your key.'});if(answer.response!==1)return null;return ai.test();});
 handle('campaign-key-dialog',async provider=>{if(keyDialogOpen)throw Error('Key entry is already open');if(!['openai','claude'].includes(provider))throw Error('Unknown provider');keyDialogOpen=true;const keyWin=new BrowserWindow({parent:win,modal:true,width:520,height:350,resizable:false,title:'Secure '+provider+' API key entry',webPreferences:{preload:path.join(__dirname,'ai-key-preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});let saved=false;const closed=new Promise(resolve=>keyWin.on('closed',()=>{keyDialogOpen=false;resolve(saved);}));keyWin.webContents.setWindowOpenHandler(()=>({action:'deny'}));keyWin.webContents.on('will-navigate',e=>e.preventDefault());const save=async(event,key)=>{if(event.sender!==keyWin.webContents)throw Error('Unapproved key entry');await ai.saveKey(provider,key);saved=true;keyWin.close();return true;};ipcMain.handle('campaign-key-entry',save);keyWin.on('closed',()=>ipcMain.removeHandler('campaign-key-entry'));await keyWin.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent('<meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; script-src \'unsafe-inline\'"><style>body{font:16px system-ui;background:#14232e;color:#eee;padding:24px}input{width:100%;padding:10px;box-sizing:border-box}button{margin-top:15px;padding:10px}</style><h2>API key</h2><p>Stored with Windows account encryption. It is never returned to the editor or included in campaign exports.</p><form><input type="password" id="key" autocomplete="off" autofocus required><button>Save encrypted key</button><p id="status"></p></form><script>document.querySelector("form").onsubmit=async e=>{e.preventDefault();const key=document.getElementById("key");try{await window.keyEntry.save(key.value);key.value="";}catch{document.getElementById("status").textContent="Key could not be saved. Check the format and OS encryption.";key.value="";}}</script>'));return closed;});
 handle('campaign-ai-generate',async(c,prompt,mode,context)=>{const s=await ai.status(),answer=await dialog.showMessageBox(win,{type:'question',buttons:['Cancel','Generate with my API account'],defaultId:0,cancelId:0,title:'Provider-billed generation',message:'Send this campaign context to '+s.provider+'?',detail:'This sends story items, DM notes, recent conversation and installed asset metadata. The provider may charge your API account. No generated text or layout is applied automatically.'});if(answer.response!==1)return null;const result=await ai.generate(c,prompt,mode,context);if(result.assistant){result.lookups=await Promise.all(result.assistant.actions.filter(a=>['findAssets','findSavedScenes'].includes(a.type)).map(a=>actions.lookup(a)));result.assistant.actions=result.assistant.actions.filter(a=>!['findAssets','findSavedScenes'].includes(a.type));}return result;});
 handle('campaign-link-project',async id=>{const r=await dialog.showOpenDialog(win,{filters:[{name:'Terrain project',extensions:['terrain']}],properties:['openFile']});if(r.canceled)return null;if((await fs.stat(r.filePaths[0])).size>100000000)throw Error('Project exceeds limit');return store.addProjectReference(id,r.filePaths[0]);});handle('campaign-linked-project',(id,link)=>store.project(id,link));
 handle('campaign-import-image',async()=>{const r=await dialog.showOpenDialog(win,{filters:[{name:'Raster artwork',extensions:['png','jpg','jpeg','webp']}],properties:['openFile']});if(r.canceled)return null;if((await fs.stat(r.filePaths[0])).size>4000000)throw Error('Artwork must be under 4 MB');const b=await fs.readFile(r.filePaths[0]),mime=b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':b[0]===255&&b[1]===216?'image/jpeg':b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP'?'image/webp':null;if(!mime)throw Error('Invalid raster image');return 'data:'+mime+';base64,'+b.toString('base64');});
 handle('campaign-import-sound',async(id,license)=>{if(typeof license!=='string'||!license.trim()||license.length>2000)throw Error('Record your sound licence/source');const c=await store.load(id);if(c.sounds.length>=12)throw Error('Twelve soundboard slots are available');const r=await dialog.showOpenDialog(win,{filters:[{name:'Licensed local audio',extensions:['wav','mp3','ogg']}],properties:['openFile']});if(r.canceled)return null;const file=r.filePaths[0];if((await fs.stat(file)).size>20000000)throw Error('Sound must be under 20 MB');const b=await fs.readFile(file),ext=b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WAVE'?'wav':b.toString('ascii',0,4)==='OggS'?'ogg':b.toString('ascii',0,3)==='ID3'||b[0]===255&&(b[1]&224)===224?'mp3':null;if(!ext)throw Error('Invalid audio format');const sound={id:crypto.randomUUID(),name:path.basename(file).slice(0,160),slot:c.sounds.length+1,loop:false,volume:1,license};const folder=path.join(await store.folder(id),'sounds');await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,sound.id+'.'+ext),b);c.sounds.push(sound);return store.save(c);});
 handle('campaign-starter-sounds',async id=>{const c=await store.load(id),{names,starterWav}=require('./campaign-sounds.cjs');if(c.sounds.length+names.length>12)throw Error('Eight empty sound slots are needed for the starter palette');const folder=path.join(await store.folder(id),'sounds');await fs.mkdir(folder,{recursive:true});for(let i=0;i<names.length;i++){const sound={id:crypto.randomUUID(),name:'Synthesized '+names[i],slot:c.sounds.length+1,loop:i<3,volume:.65,license:'Original Terrain Foundry synthesized sound · CC0'};await fs.writeFile(path.join(folder,sound.id+'.wav'),starterWav(i));c.sounds.push(sound);}return store.save(c);});
 handle('campaign-sound-bytes',async(id,soundId)=>{const c=await store.load(id);if(!c.sounds.some(s=>s.id===soundId))throw Error('Unknown sound');for(const ext of ['wav','mp3','ogg']){const f=path.join(await store.folder(id),'sounds',soundId+'.'+ext);try{if((await fs.stat(f)).size>20000000)throw Error('Sound exceeds limit');return {bytes:new Uint8Array(await fs.readFile(f)),mime:{wav:'audio/wav',mp3:'audio/mpeg',ogg:'audio/ogg'}[ext]};}catch(e){if(e.code!=='ENOENT')throw e;}}throw Error('Sound file missing');});
 handle('campaign-export',async(id,options)=>{const c=await store.load(id);if(options?.format==='player-json'){const {playerCampaign}=await import('./campaign-schema.mjs'),r=await dialog.showSaveDialog(win,{defaultPath:c.name.replace(/[^a-zA-Z0-9 -]/g,'_')+'.player.json',filters:[{name:'Player handout',extensions:['json']}]});if(r.canceled)return null;await fs.writeFile(r.filePath,JSON.stringify(playerCampaign(c),null,2));return r.filePath;}
 const html=await require('./campaign-print.cjs').campaignHTML(c,options),r=await dialog.showSaveDialog(win,{defaultPath:c.name.replace(/[^a-zA-Z0-9 -]/g,'_')+'.pdf',filters:[{name:'Campaign PDF',extensions:['pdf']}]});if(r.canceled)return null;const printing=new BrowserWindow({show:false,webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true}});try{await printing.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html));const pdf=await printing.webContents.printToPDF({printBackground:true,pageSize:'A4',preferCSSPageSize:true});await fs.writeFile(r.filePath,pdf);return r.filePath;}finally{printing.destroy();}});
 return {store,ai,voice};
}
module.exports={setupCampaignNative};
