const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const MAX_PACK=1000000000,MAX_FILE=250000000;
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const packId=s=>typeof s==='string'&&/^tf-[a-z0-9-]{1,80}$/.test(s);
const assetId=s=>typeof s==='string'&&/^[a-z][a-z0-9-]{0,80}$/.test(s)&&!['__proto__','constructor','prototype'].includes(s);
const safePath=s=>typeof s==='string'&&s.length<=240&&!/[\\:\x00-\x1f]/.test(s)&&!s.startsWith('/')&&!s.split('/').some(x=>!x||x==='.'||x==='..');
function decode(s,n){if(typeof s!=='string'||!s.length||s.length>n*2||!/^[A-Za-z0-9+/]*={0,2}$/.test(s))throw Error('Invalid signed pack encoding.');const b=Buffer.from(s,'base64');if(b.length>n||b.toString('base64')!==s)throw Error('Invalid signed pack encoding.');return b;}
function verifyManifest(grant,publicKey,expectedPack){
 if(!grant||typeof grant!=='object')throw Error('Missing signed pack inventory.');const bytes=decode(grant.payload,5000000),signature=decode(grant.signature,64);
 if(signature.length!==64||!crypto.verify(null,bytes,publicKey,signature))throw Error('Pack signature failed.');const m=JSON.parse(bytes);
 if(m.schemaVersion!==1||m.issuer!=='TerrainFoundry'||!packId(m.packId)||m.packId!==expectedPack||!/^\d{1,6}\.\d{1,6}\.\d{1,6}$/.test(m.version)||!Number.isSafeInteger(m.size)||m.size<1||m.size>MAX_PACK||!/^([a-f0-9]{64})$/.test(m.sha256)||!Array.isArray(m.files)||!m.files.length||m.files.length>10000)throw Error('Invalid signed pack inventory.');
 let end=0;const names=new Set();for(const f of m.files){if(!safePath(f.path)||names.has(f.path)||![f.offset,f.length,f.plainSize].every(Number.isSafeInteger)||f.offset!==end||f.length<1||f.length>MAX_FILE||f.plainSize!==f.length||!/^([a-f0-9]{64})$/.test(f.sha256)||decode(f.iv,12).length!==12||decode(f.tag,16).length!==16)throw Error('Unsafe pack file inventory.');names.add(f.path);end+=f.length;if(end>m.size)throw Error('Pack ranges exceed the archive.');}if(end!==m.size||!names.has('catalogue.json'))throw Error('Incomplete pack inventory.');return m;
}
function readEntrySync(file,m,key,name){const f=m.files.find(x=>x.path===name);if(!f)throw Error('Unknown pack file.');const fd=fs.openSync(file,'r');try{if(fs.fstatSync(fd).size!==m.size)throw Error('Pack size changed.');const encrypted=Buffer.alloc(f.length);if(fs.readSync(fd,encrypted,0,f.length,f.offset)!==f.length)throw Error('Truncated pack file.');const d=crypto.createDecipheriv('aes-256-gcm',key,decode(f.iv,12));d.setAAD(Buffer.from(m.packId+'\n'+m.version+'\n'+f.path));d.setAuthTag(decode(f.tag,16));const bytes=Buffer.concat([d.update(encrypted),d.final()]);if(bytes.length!==f.plainSize||hash(bytes)!==f.sha256)throw Error('Pack file integrity failed.');return bytes;}finally{fs.closeSync(fd);}}
function validateCatalogue(bytes,m,isReserved=()=>false){
 if(bytes.length>2000000)throw Error('Pack catalogue too large.');const c=JSON.parse(bytes);if(c.schemaVersion!==1||c.packId!==m.packId||!Array.isArray(c.assets)||!c.assets.length||c.assets.length>1000)throw Error('Invalid asset catalogue.');const names=new Set(),allPrintNames=new Set(),files=new Map(m.files.map(f=>[f.path,f]));
 const text=s=>typeof s==='string'&&s.length>=1&&s.length<=120&&!/[\x00-\x1f]/.test(s);
 const categories=['Floors','Walls','Doors & openings','Stairs & ramps','Roofs','Terrain','Water','Bridges','Trees & plants','Traps','Props','Details'];
 for(const a of c.assets){if(!assetId(a.id)||names.has(a.id)||isReserved(a.id)||!text(a.name)||!categories.includes(a.category)||!text(a.subcategory))throw Error('Invalid or conflicting pack asset.');names.add(a.id);
  for(const key of ['raw','connected']){const p=a[key],f=files.get(p?.path);if(!p||!f||!Number.isSafeInteger(p.vertices)||p.vertices<3||!Number.isSafeInteger(p.indices)||p.indices<3||p.indices%3||p.vertices*24+p.indices*4!==f.plainSize||f.plainSize>32*1024*1024)throw Error('Invalid preview geometry inventory.');}
  const d=a.dimensionsMm;if(!d||!['width','depth','height'].every(k=>Number.isFinite(d[k])&&d[k]>0&&d[k]<=10000))throw Error('Invalid asset dimensions.');
  if(!Array.isArray(a.printFiles)||!a.printFiles.length||a.printFiles.length>10)throw Error('Missing printable geometry.');if(a.plainPrintFiles!==undefined&&(!Array.isArray(a.plainPrintFiles)||!a.plainPrintFiles.length||a.plainPrintFiles.length>10))throw Error('Invalid plain printable inventory.');const printNames=new Set();for(const f of [...a.printFiles,...(a.plainPrintFiles||[])]){const e=files.get(f.path);if(!e||e.plainSize<84||!/^[-a-zA-Z0-9_.]+\.stl$/.test(f.name)||printNames.has(f.name.toLowerCase())||allPrintNames.has(f.name.toLowerCase()))throw Error('Invalid printable geometry inventory.');printNames.add(f.name.toLowerCase());allPrintNames.add(f.name.toLowerCase());}
  const s=a.openlock;if(!s||!text(s.kind)||!['width','depth','height'].every(k=>Number.isFinite(s[k])&&s[k]>0&&s[k]<=10000)||!Array.isArray(s.ports)||s.ports.length>100)throw Error('Invalid connector inventory.');for(const p of s.ports){if(!['x','z','nx','nz','angle'].every(k=>Number.isFinite(p[k])&&Math.abs(p[k])<=10000)||Math.abs(Math.hypot(p.nx,p.nz)-1)>.0001||p.y!==undefined&&(!Number.isFinite(p.y)||Math.abs(p.y)>10000)||p.roll!==undefined&&(!Number.isFinite(p.roll)||Math.abs(p.roll)>360))throw Error('Invalid connector port.');}if(s.footprints!==undefined&&(!Array.isArray(s.footprints)||s.footprints.length>100||s.footprints.some(poly=>!Array.isArray(poly)||poly.length<3||poly.length>100||poly.some(p=>!Array.isArray(p)||p.length!==2||p.some(n=>!Number.isFinite(n)||Math.abs(n)>10000)))))throw Error('Invalid connector footprint.');
 }
 return c.assets;
}
function validateMesh(bytes,p){const count=p.vertices*3,positions=new Float32Array(bytes.buffer,bytes.byteOffset,count),colors=new Float32Array(bytes.buffer,bytes.byteOffset+count*4,count),indices=new Uint32Array(bytes.buffer,bytes.byteOffset+count*8,p.indices);for(const n of positions)if(!Number.isFinite(n)||Math.abs(n)>10000)throw Error('Invalid mesh coordinate.');for(const n of colors)if(!Number.isFinite(n)||n<0||n>1)throw Error('Invalid mesh colour.');for(const n of indices)if(n>=p.vertices)throw Error('Invalid mesh index.');}
function validateSTL(b){if(b.length<84||b.length!==84+b.readUInt32LE(80)*50)throw Error('Invalid printable STL.');for(let i=84;i<b.length;i+=50)for(let j=0;j<12;j++){const n=b.readFloatLE(i+j*4);if(!Number.isFinite(n)||Math.abs(n)>10000)throw Error('Invalid printable coordinate.');}}
async function verifyBlob(file,m){const stat=await fsp.lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==m.size)throw Error('Pack archive size failed.');const h=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(file))h.update(chunk);if(h.digest('hex')!==m.sha256)throw Error('Pack archive integrity failed.');}
function createPremiumStore({userData,safeStorage,device,issuerPublicKey,isReserved=()=>false}){
 const root=path.join(userData,'premium','packs'),installed=new Map(),assets=new Map(),errors=new Map();let busy=false;
 function protectedStorage(){if(!safeStorage.isEncryptionAvailable()||safeStorage.getSelectedStorageBackend?.()==='basic_text')throw Error('Protected pack storage is unavailable.');}
 function publicInventory(){return {packs:[...installed].map(([id,r])=>({id,version:r.m.version,pieceCount:r.catalogue.length})),assets:[...assets.values()].map(({asset:a,pack})=>({id:a.id,name:a.name,category:a.category,subcategory:a.subcategory,explicitCategory:true,hint:'Premium scenery · available offline',packId:pack,raw:{vertices:a.raw.vertices,indices:a.raw.indices},connected:{vertices:a.connected.vertices,indices:a.connected.indices},openlock:a.openlock,dimensionsMm:a.dimensionsMm,printFiles:a.printFiles.map(f=>({file:f.name}))})),warnings:[...errors.values()]};}
 function register(record){for(const a of record.catalogue){const previous=assets.get(a.id);if(previous&&previous.pack!==record.m.packId)throw Error('Installed packs contain conflicting asset IDs.');}const old=installed.get(record.m.packId);if(old)for(const a of old.catalogue)assets.delete(a.id);installed.set(record.m.packId,record);for(const a of record.catalogue)assets.set(a.id,{asset:a,pack:record.m.packId});}
 async function openRecord(directory){const file=path.join(directory,'archive.tfc'),json=JSON.parse(await fsp.readFile(path.join(directory,'record.json'),'utf8'));const m=verifyManifest(json.manifest,issuerPublicKey,json.packId);await device.verifyEntitlement(json.entitlement,issuerPublicKey,m.packId);protectedStorage();const key=decode(safeStorage.decryptString(decode(json.protectedKey,4000)),32);if(key.length!==32)throw Error('Invalid protected content key.');await verifyBlob(file,m);const catalogue=validateCatalogue(readEntrySync(file,m,key,'catalogue.json'),m,isReserved);return {file,m,key,catalogue,entitlement:json.entitlement};}
 async function init(){await fsp.mkdir(root,{recursive:true});for(const e of await fsp.readdir(root,{withFileTypes:true})){if(!e.isFile()||!/^tf-[a-z0-9-]+\.json$/.test(e.name))continue;try{const p=JSON.parse(await fsp.readFile(path.join(root,e.name),'utf8'));if(!packId(p.packId)||e.name!==p.packId+'.json'||!/^installed-[a-f0-9]{32}$/.test(p.directory))throw Error('Invalid pack pointer.');const directory=path.join(root,p.directory);if((await fsp.lstat(directory)).isSymbolicLink())throw Error('Unsafe pack directory.');const r=await openRecord(directory);if(r.m.packId!==p.packId)throw Error('Pack pointer mismatch.');register(r);}catch{errors.set(e.name.slice(0,-5),'A premium pack could not be verified. Reopen Packs to download it again.');}}return publicInventory();}
 async function install({manifest,entitlement,key,download,signal}){
 if(busy)throw Error('A pack installation is already running.');busy=true;let stage;
 try{protectedStorage();const m=verifyManifest(manifest,issuerPublicKey,JSON.parse(decode(manifest.payload,5000000)).packId);await device.verifyEntitlement(entitlement,issuerPublicKey,m.packId);const contentKey=decode(key,32);if(contentKey.length!==32)throw Error('Invalid content key.');stage=await fsp.mkdtemp(path.join(root,'.pending-'));const file=path.join(stage,'archive.tfc');await download(file,m.size);await verifyBlob(file,m);
  const catalogue=validateCatalogue(readEntrySync(file,m,contentKey,'catalogue.json'),m,isReserved),previousPack=installed.get(m.packId);if(previousPack){const current=previousPack.m.version.split('.').map(Number),next=m.version.split('.').map(Number);let cmp=0;for(let i=0;i<3;i++)if(current[i]!==next[i]){cmp=next[i]-current[i];break;}if(cmp<0||cmp===0&&previousPack.m.sha256!==m.sha256)throw Error('Pack version would replace a newer installation.');if(previousPack.catalogue.some(a=>!catalogue.some(n=>n.id===a.id)))throw Error('Pack update removes scenery used by saved projects.');}for(const a of catalogue){const previous=assets.get(a.id);if(previous&&previous.pack!==m.packId)throw Error('Conflicting premium asset ID.');for(const k of ['raw','connected'])validateMesh(readEntrySync(file,m,contentKey,a[k].path),a[k]);for(const f of [...a.printFiles,...(a.plainPrintFiles||[])])validateSTL(readEntrySync(file,m,contentKey,f.path));}
  // Verify every signed entry before making the pack available, including future metadata.
  for(const f of m.files){if(signal?.aborted)throw Error('Pack action cancelled.');readEntrySync(file,m,contentKey,f.path);await new Promise(resolve=>setImmediate(resolve));}if(signal?.aborted)throw Error('Pack action cancelled.');
  await fsp.writeFile(path.join(stage,'record.json'),JSON.stringify({schemaVersion:1,packId:m.packId,manifest,entitlement,protectedKey:safeStorage.encryptString(contentKey.toString('base64')).toString('base64')}),{mode:0o600});
  const directory='installed-'+crypto.randomBytes(16).toString('hex'),target=path.join(root,directory);await fsp.rename(stage,target);stage=undefined;const temporary=path.join(root,'.pointer-'+crypto.randomBytes(8).toString('hex'));await fsp.writeFile(temporary,JSON.stringify({packId:m.packId,directory}),{mode:0o600});await fsp.rename(temporary,path.join(root,m.packId+'.json'));const old=installed.get(m.packId);register({file:path.join(target,'archive.tfc'),m,key:contentKey,catalogue,entitlement});errors.delete(m.packId);if(old){const oldDir=path.dirname(old.file);if(oldDir.startsWith(root+path.sep)&&/^installed-[a-f0-9]{32}$/.test(path.basename(oldDir)))await fsp.rm(oldDir,{recursive:true,force:true}).catch(()=>{});}return publicInventory();
 }finally{if(stage&&stage.startsWith(root+path.sep)&&path.basename(stage).startsWith('.pending-'))await fsp.rm(stage,{recursive:true,force:true});busy=false;}
 }
 function readShape(id,connected){if(typeof connected!=='boolean'||!assets.has(id))throw Error('Unknown premium asset.');const {asset:a,pack}=assets.get(id),r=installed.get(pack),p=connected?a.connected:a.raw,bytes=readEntrySync(r.file,r.m,r.key,p.path);validateMesh(bytes,p);return {bytes,vertices:p.vertices,indices:p.indices};}
 function readPrint(id,connected=true){const row=assets.get(id);if(!row)throw Error('Unknown premium print asset.');if(typeof connected!=='boolean')throw Error('Invalid connector selection.');const r=installed.get(row.pack),files=connected||!row.asset.openlock.ports.length?row.asset.printFiles:row.asset.plainPrintFiles;if(!files)throw Error('This pack requires Integrated OpenLOCK for full-detail print exports.');return files.map(f=>{const data=readEntrySync(r.file,r.m,r.key,f.path);validateSTL(data);return {name:f.name,data};});}
 async function matchesManifest(m){const r=installed.get(m.packId);if(!r||r.m.version!==m.version||r.m.sha256!==m.sha256)return false;try{await verifyBlob(r.file,r.m);return true;}catch{return false;}}
 return {init,install,matchesManifest,inventory:publicInventory,has:id=>assets.has(id),readShape,readPrint};
}
module.exports={createPremiumStore,verifyManifest,validateCatalogue,readEntrySync,MAX_PACK};
