const fs=require('node:fs/promises');
const trust=require('./premium-trust.cjs');
const ACTIONS=new Set(['login-start','login-verify','challenge','activate','download-challenge','download']);
function createPremiumClient({device,store,fetchImpl=fetch,issuerPublicKey=trust.issuerPublicKey,serviceBase=trust.serviceBase,storageHost=trust.storageHost,onProgress=()=>{}}){
 let requestId,session,expires=0,busy=false,abort;
 async function request(action,args,authenticated=true){
  if(!ACTIONS.has(action))throw Error('Unsupported pack request.');if(authenticated&&(!session||expires<=Date.now()))throw Error('Verify your purchase email again.');
  const body=JSON.stringify(args),response=await fetchImpl(serviceBase+action,{method:'POST',headers:{'Content-Type':'application/json',...(authenticated?{Authorization:'Bearer '+session}:{})},body,redirect:'error',signal:abort.signal});
  const chunks=[];let size=0;for await(const chunk of response.body){size+=chunk.length;if(size>8000000)throw Error('Pack service response too large.');chunks.push(Buffer.from(chunk));}let result;try{result=JSON.parse(Buffer.concat(chunks));}catch{throw Error('The pack service returned an invalid response.');}if(!response.ok){const message=typeof result.error==='string'&&result.error.length<=240?result.error:'Pack service unavailable. Please try again later.';throw Error(message);}return result;
 }
 async function run(fn){if(busy)throw Error('Another pack action is running.');busy=true;abort=new AbortController();const timer=setTimeout(()=>abort.abort(),3600000);try{return await fn();}catch(e){if(e.name==='AbortError'||abort.signal.aborted)throw Error('Pack action cancelled. Completed downloads remain installed; verify your email to resume.');if(e instanceof TypeError)throw Error('Cannot connect to the pack service. Check your internet connection.');throw e;}finally{clearTimeout(timer);busy=false;abort=undefined;}}
 async function downloadTo(url,file,m){
  const u=new URL(url);if(u.protocol!=='https:'||u.hostname!==storageHost||u.port||u.username||u.password||u.hash||u.pathname!==`/premium-packs/packs/${m.packId}/${m.version}/${m.sha256}.tfc`||u.searchParams.get('sp')!=='r'||!u.searchParams.get('sig'))throw Error('Unapproved pack download address.');
  const response=await fetchImpl(u.href,{redirect:'error',signal:abort.signal});if(!response.ok)throw Error('Pack download failed. Please try again.');const length=response.headers.get('content-length');if(length&&Number(length)!==m.size)throw Error('Pack download size does not match.');const fd=await fs.open(file,'wx',0o600);let size=0;try{for await(const chunk of response.body){if(abort.signal.aborted)throw Error('Pack action cancelled.');size+=chunk.length;if(size>m.size)throw Error('Pack download exceeds its signed size.');let offset=0;while(offset<chunk.length){const {bytesWritten}=await fd.write(chunk,offset,chunk.length-offset);if(!bytesWritten)throw Error('Pack file write failed.');offset+=bytesWritten;}onProgress({stage:'Downloading scenery',received:size,total:m.size});}if(size!==m.size)throw Error('Pack download was interrupted.');await fd.sync();}finally{await fd.close();}
 }
 return {
  loginStart:email=>run(async()=>{if(typeof email!=='string'||email.length>254||!/^\S+@\S+\.\S+$/.test(email.trim()))throw Error('Enter your purchase email address.');const identity=await device.publicIdentity(),r=await request('login-start',{email:email.trim(),publicKey:identity.publicKey},false);if(typeof r.requestId!=='string'||!/^[a-zA-Z0-9_-]{16,100}$/.test(r.requestId))throw Error('Invalid verification request.');requestId=r.requestId;session=undefined;return {sent:true};}),
  loginVerify:otp=>run(async()=>{if(!requestId||typeof otp!=='string'||!/^\d{6}$/.test(otp))throw Error('Enter the six-digit email number.');const identity=await device.publicIdentity(),r=await request('login-verify',{requestId,otp,publicKey:identity.publicKey},false);if(typeof r.session!=='string'||!/^[a-zA-Z0-9_-]{32,200}$/.test(r.session)||!Number.isFinite(r.expires)||r.expires<=Date.now()||r.expires>Date.now()+3700000)throw Error('Invalid verification session.');session=r.session;expires=r.expires;requestId=undefined;return {verified:true};}),
  activate:code=>run(async()=>{if(typeof code!=='string'||!/^TF-[A-Z2-7]{32}$/.test(code.trim()))throw Error('Enter the pack activation code from your purchase email.');code=code.trim();const {publicKey}=await device.publicIdentity();onProgress({stage:'Verifying purchase'});const c=await request('challenge',{code,publicKey});const signature=await device.signChallenge(c.message),a=await request('activate',{code,publicKey,challengeId:c.challengeId,signature});if(typeof a.packId!=='string')throw Error('Invalid pack activation.');const grant=await device.verifyEntitlement(a.entitlement,issuerPublicKey,a.packId);const d=await request('download-challenge',{entitlement:a.entitlement,publicKey});const proof=await device.signDownloadChallenge(d.message,grant.licenceId);const response=await request('download',{entitlement:a.entitlement,publicKey,challengeId:d.challengeId,signature:proof});const bundles=response.bundles||[response];if(!Array.isArray(bundles)||!bundles.length||bundles.length>30)throw Error('Invalid collection delivery.');const seen=new Set(),metadata=[];
   for(const item of bundles){const payload=JSON.parse(Buffer.from(item.manifest?.payload||'','base64')),manifest=require('./premium-store.cjs').verifyManifest(item.manifest,issuerPublicKey,payload.packId),child=await device.verifyEntitlement(item.entitlement,issuerPublicKey,manifest.packId);if(seen.has(manifest.packId)||child.licenceId!==grant.licenceId||(response.bundles&&child.parentPackId!==a.packId))throw Error('Collection entitlement does not match purchase.');seen.add(manifest.packId);metadata.push(manifest);}
   let pieceCount=0;for(let index=0;index<metadata.length;index++){const manifest=metadata[index];if(store.matchesManifest&&await store.matchesManifest(manifest)){pieceCount+=store.inventory().packs.find(p=>p.id===manifest.packId).pieceCount;onProgress({stage:`Verified installed collection ${index+1} of ${metadata.length}`});continue;}let item=bundles[index];if(response.bundles){const challenge=await request('download-challenge',{entitlement:a.entitlement,publicKey}),signature=await device.signDownloadChallenge(challenge.message,grant.licenceId),fresh=await request('download',{entitlement:a.entitlement,publicKey,challengeId:challenge.challengeId,signature,bundleId:manifest.packId});item=fresh.bundles?.[0];const renewed=await device.verifyEntitlement(item?.entitlement,issuerPublicKey,manifest.packId);if(renewed.licenceId!==grant.licenceId||renewed.parentPackId!==a.packId||item.manifest.payload!==bundles[index].manifest.payload)throw Error('Collection changed during download. Please retry.');}
    onProgress({stage:`Installing collection ${index+1} of ${metadata.length}`,received:0,total:manifest.size});const result=await store.install({...item,signal:abort.signal,download:async file=>{await downloadTo(item.url,file,manifest);onProgress({stage:`Verifying collection ${index+1} of ${metadata.length}`});}});pieceCount+=result.packs.find(p=>p.id===manifest.packId).pieceCount;}
   onProgress({stage:'Ready offline'});return {installed:true,packId:a.packId,pieceCount};}),
  cancel(){abort?.abort();session=undefined;requestId=undefined;expires=0;},
 };
}
module.exports={createPremiumClient};
