const $=id=>document.getElementById(id);let busy=false,licenceVersion;
function controls(){document.querySelectorAll('button,input').forEach(e=>e.disabled=busy);$('activate').disabled=busy||!licenceVersion||!$('accept-licence').checked;}
window.packEntry.licence().then(licence=>{licenceVersion=licence.version;$('licence-text').textContent=licence.text;controls();}).catch(()=>{$('licence-text').textContent='The licence could not be loaded. Close this window and try again.';controls();});
async function run(task){if(busy)return;busy=true;controls();try{await task();}catch(e){$('status').textContent=e.message||'Activation could not be completed.';}finally{busy=false;controls();}}
$('accept-licence').onchange=controls;
$('email-form').onsubmit=e=>{e.preventDefault();run(async()=>{await window.packEntry.start($('email').value);$('email').value='';$('email-form').hidden=true;$('verify-form').hidden=false;$('status').textContent='Check your purchase email for the six-digit verification number. This is different from the pack activation code.';});};
$('verify-form').onsubmit=e=>{e.preventDefault();run(async()=>{await window.packEntry.verify($('otp').value);$('otp').value='';$('verify-form').hidden=true;$('code-form').hidden=false;$('accept-licence').checked=false;$('licence').open=true;$('status').textContent='Email verified. Read the licence, enter your pack code and accept the terms to continue.';});};
$('code-form').onsubmit=e=>{e.preventDefault();if(!$('accept-licence').checked||!licenceVersion){$('status').textContent='Read and accept the scenery licence to continue.';return;}run(async()=>{$('licence').open=false;const result=await window.packEntry.activate({code:$('code').value.trim(),acceptLicence:true,licenceVersion});$('code').value='';$('accept-licence').checked=false;$('status').textContent=`Pack ready offline: ${result.pieceCount} pieces. Close this window to browse your scenery.`;$('code-form').hidden=true;});};
const bytes=n=>n>=1e9?(n/1e9).toFixed(2)+' GB':(n/1e6).toFixed(1)+' MB';
window.packEntry.progress(s=>{
 $('download-progress').hidden=false;$('overall-label').textContent=s.stage;
 if(Number.isFinite(s.overallTotal)&&s.overallTotal>0){const percent=s.ready?100:Math.min(99,Math.floor(s.overallReceived/s.overallTotal*100));$('progress').value=percent;$('overall-percent').textContent=percent+'% overall';$('progress-details').textContent=`${bytes(s.overallReceived)} / ${bytes(s.overallTotal)} scenery data · ${s.completedSections} of ${s.sectionCount} sections ready${s.cachedSections?' · '+s.cachedSections+' already installed':''}`;}
 else{$('progress').removeAttribute('value');$('overall-percent').textContent='';$('progress-details').textContent='Checking your licence and preparing the collection…';}
});
$('restart').onclick=()=>{if(busy)return;for(const id of ['email','otp','code'])$(id).value='';$('accept-licence').checked=false;$('email-form').hidden=false;$('verify-form').hidden=true;$('code-form').hidden=true;$('download-progress').hidden=true;$('status').textContent='Enter your purchase email to verify again.';controls();};
